const DATA: Dictionary = {

	"Fiery Aura": {
		"description": "Any creature that starts its turn within 5 feet of the creature takes fire damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "All creatures within 5 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Deals fire damage to any creature that starts its turn within 5 ft. No save required.",
	},
	"Heated Body": {
		"description": "A creature that touches this creature or hits it with a melee attack while within 5 feet of it takes fire damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "Any creature touching or striking in melee",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Punishes melee attackers and anything that makes physical contact with fire damage.",
	},
	"Heated Weapons": {
		"description": "Any metal melee weapon the creature wields deals extra fire damage on a hit.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "1d6",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "All of the creature's metal melee attacks deal an additional 1d6 fire damage.",
	},
	"Aura of Fear": {
		"description": "While the creature is not incapacitated, each creature of its choice that starts its turn within 20 feet of it and can see and hear it must succeed on a Wisdom saving throw or be frightened until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "20 ft.",
		"duration": "Permanent",
		"target": "Creatures of the creature's choice within 20 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Enemies starting their turn within 20 ft. must save or be Frightened until the start of their next turn.",
	},
	"Divine Aura": {
		"description": "Any creature that starts its turn within 30 feet of the creature must make a Charisma saving throw. On a failed save, the creature is charmed or frightened (creature's choice) until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All creatures within 30 ft.",
		"saving_throw": "CHA",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed", "Frightened"],
		"effect": "Creatures starting their turn within 30 ft. must save or be Charmed or Frightened (creature's choice) until the start of their next turn.",
	},
	"Storm Aura": {
		"description": "A storm aura surrounds the creature. Any creature that starts its turn within 30 feet of it takes lightning damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All creatures within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "lightning",
		"conditions_applied": [],
		"effect": "Deals lightning damage to all creatures that start their turn within 30 ft. No save required.",
	},
	"Barbed Hide": {
		"description": "At the start of each of its turns, the creature deals piercing damage to any creature grappling it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Touch",
		"duration": "Permanent",
		"target": "Any creature grappling the creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "1d10",
		"damage_type": "piercing",
		"conditions_applied": [],
		"effect": "Any creature grappling this creature takes 1d10 piercing damage at the start of the creature's turn.",
	},
	"Rotting Presence": {
		"description": "Any creature (other than a troll) that starts its turn within 30 feet of this creature must make a Constitution saving throw. On a failed save, the creature loses hit points. On a success, the creature is immune to this creature's Rotting Presence for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All non-troll creatures within 30 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "necrotic",
		"conditions_applied": [],
		"effect": "Creatures starting their turn within 30 ft. must save or take necrotic damage. Success grants 24-hour immunity.",
	},
	"Stench of Death": {
		"description": "Any creature that starts its turn within 10 feet of this creature must make a Constitution saving throw or be poisoned until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft.",
		"duration": "Permanent",
		"target": "All creatures within 10 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned"],
		"effect": "Creatures starting their turn within 10 ft. must save or be Poisoned until the start of their next turn.",
	},
	"Stench": {
		"description": "Any creature that starts its turn within 5 feet of this creature must succeed on a Constitution saving throw or be poisoned until the start of its next turn. On a successful saving throw, the creature is immune to this creature's Stench for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "All creatures within 5 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned"],
		"effect": "Creatures starting their turn within 5 ft. must save or be Poisoned. Success grants 24-hour immunity.",
	},
	"Darkness Aura": {
		"description": "Magical darkness spreads from this creature to a 15-foot radius, moving with it. The darkness spreads around corners. Darkvision cannot pierce it and no light source can illuminate it. Overlapping light spells of 2nd level or lower are dispelled.",
		"action_type": "Passive",
		"recharge": "",
		"range": "15 ft. radius",
		"duration": "Permanent",
		"target": "15 ft. radius area",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature is always surrounded by a 15 ft. radius of magical darkness that suppresses darkvision and dispels low-level light spells.",
	},
	"Darkness": {
		"description": "The creature magically creates an area of nonmagical darkness in a 15-foot-radius sphere. The darkness spreads around corners and lasts for 1 minute. Darkvision cannot pierce it.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "1 minute",
		"target": "15 ft. radius sphere",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates a sphere of magical darkness in a target area that blocks darkvision and normal sight.",
	},
	"Aura of Doom": {
		"description": "While this creature is not incapacitated, any creature within 30 feet of it has disadvantage on saving throws.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All creatures within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "All creatures within 30 ft. have disadvantage on saving throws.",
	},
	"Blazing Presence": {
		"description": "Any creature that starts its turn within 5 feet of this creature takes fire damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "All creatures within 5 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Deals fire damage to any creature that starts its turn within 5 ft. No save required.",
	},
	"Terror Aura": {
		"description": "Any creature that starts its turn within 120 feet of this creature and can see it must succeed on a Wisdom saving throw or be frightened. A frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
		"action_type": "Passive",
		"recharge": "",
		"range": "120 ft.",
		"duration": "Until save succeeds",
		"target": "All creatures within 120 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Creatures within 120 ft. that can see the creature must save or be Frightened. They may re-save each turn.",
	},
	"Chardalyn Aura": {
		"description": "This creature's body radiates an aura of corrupted chardalyn magic. Creatures that start their turn within 30 feet of it must succeed on a Constitution saving throw or have their hit point maximum reduced.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All creatures within 30 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Corrupted chardalyn magic reduces the max HP of creatures within 30 ft. that fail a CON save.",
	},
	"Artistic Magnificence": {
		"description": "Any creature that starts its turn within 30 feet of this creature and can see it must succeed on a Wisdom saving throw or be stunned until the start of its next turn. On a successful save, the creature is immune to this creature's Artistic Magnificence for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "All creatures within 30 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Stunned"],
		"effect": "Creatures starting their turn within 30 ft. must save or be Stunned. Success grants 24-hour immunity.",
	},
	"Sorrowful Presence": {
		"description": "Any non-eladrin creature that starts its turn within 60 feet of this creature must make a Wisdom saving throw. On a failed save, the creature has the charmed condition until the start of its next turn. On a successful save, the creature is immune to this ability for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "All non-eladrin creatures within 60 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "Non-eladrin creatures starting their turn within 60 ft. must save or be Charmed by sorrow. Success grants 24-hour immunity.",
	},
	"Joyful Presence": {
		"description": "Any non-eladrin creature that starts its turn within 60 feet of this creature must make a Wisdom saving throw. On a failed save, the creature has the charmed condition and must spend its action to engage in joyful activity until the start of its next turn. On a successful save, the creature is immune to this ability for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "All non-eladrin creatures within 60 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "Non-eladrin creatures starting their turn within 60 ft. must save or be Charmed by joy, wasting their action. Success grants 24-hour immunity.",
	},
	"Fearsome Presence": {
		"description": "Any non-eladrin creature that starts its turn within 60 feet of this creature must make a Wisdom saving throw. On a failed save, the creature has the frightened condition until the start of its next turn. On a successful save, the creature is immune to this ability for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "All non-eladrin creatures within 60 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Non-eladrin creatures starting their turn within 60 ft. must save or be Frightened. Success grants 24-hour immunity.",
	},
	"Mournful Presence": {
		"description": "Any non-eladrin creature that starts its turn within 60 feet of this creature must make a Wisdom saving throw. On a failed save, the creature has the charmed condition and is overwhelmed with grief until the start of its next turn. On a successful save, the creature is immune to this ability for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "All non-eladrin creatures within 60 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "Non-eladrin creatures starting their turn within 60 ft. must save or be Charmed by grief. Success grants 24-hour immunity.",
	},
	"Frightful Presence": {
		"description": "Each creature of this creature's choice that is within 120 feet of it and aware of it must succeed on a Wisdom saving throw or become frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a creature's saving throw is successful or the effect ends for it, the creature is immune to this creature's Frightful Presence for the next 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "120 ft.",
		"duration": "1 minute",
		"target": "Creatures of the creature's choice within 120 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Chosen creatures within 120 ft. must save or be Frightened for 1 minute. They may re-save each turn. Success grants 24-hour immunity.",
	},
	"Divine Presence": {
		"description": "If a non-divine creature starts its turn within 120 feet of this creature, it must succeed on a Wisdom saving throw or become frightened for 1 minute. A frightened creature can repeat this saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Passive",
		"recharge": "",
		"range": "120 ft.",
		"duration": "1 minute",
		"target": "All non-divine creatures within 120 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Non-divine creatures starting their turn within 120 ft. must save or be Frightened for 1 minute. They may re-save each turn.",
	},
	"Illumination": {
		"description": "The creature sheds bright light in a 10-foot radius and dim light for an additional 10 feet.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. bright / 20 ft. dim",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature constantly emits bright light in a 10 ft. radius and dim light for an additional 10 ft.",
	},
	"Variable Illumination": {
		"description": "The creature sheds bright light in a 5- to 20-foot radius and dim light for an additional number of feet equal to the chosen radius. The creature can alter the radius as a bonus action.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5-20 ft. bright / 10-40 ft. dim",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature emits a variable-radius light. The radius can be changed as a Bonus Action.",
	},
	"Radiance": {
		"description": "The creature sheds bright light in a 20-foot radius and dim light for an additional 20 feet.",
		"action_type": "Passive",
		"recharge": "",
		"range": "20 ft. bright / 40 ft. dim",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature constantly emits bright light in a 20 ft. radius and dim light for an additional 20 ft.",
	},
	"Fetid Cloud": {
		"description": "A 10-foot radius of disgusting gas extends from this creature. The gas spreads around corners and lightly obscures the area. It lasts until the start of the creature's next turn. Any creature that starts its turn in the area must succeed on a Constitution saving throw or be poisoned until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "Until start of creature's next turn",
		"target": "All creatures in 10 ft. radius",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned"],
		"effect": "Lightly obscures a 10 ft. radius around the creature. Creatures starting their turn in the area must save or be Poisoned.",
	},
}
