const DATA: Dictionary = {

	"Fire Breath": {
		"description": "The creature exhales fire in a cone. Each creature in that area must make a Dexterity saving throw, taking fire damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature (30-90 ft. cone)",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Deals fire damage in a cone. Half damage on a successful DEX save.",
	},
	"Frost Breath": {
		"description": "The creature exhales an icy blast in a cone. Each creature in that area must make a Constitution saving throw, taking cold damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature (30-90 ft. cone)",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "cold",
		"conditions_applied": [],
		"effect": "Deals cold damage in a cone. Half damage on a successful CON save.",
	},
	"Lightning Breath": {
		"description": "The creature exhales lightning in a line that is 10 feet wide. Each creature in that line must make a Dexterity saving throw, taking lightning damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature (60-120 ft. line)",
		"duration": "Instantaneous",
		"target": "All creatures in line",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "lightning",
		"conditions_applied": [],
		"effect": "Deals lightning damage in a 10 ft. wide line. Half damage on a successful DEX save.",
	},
	"Acid Breath": {
		"description": "The creature exhales acid in a line that is 5 feet wide. Each creature in that line must make a Dexterity saving throw, taking acid damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature (30-90 ft. line)",
		"duration": "Instantaneous",
		"target": "All creatures in line",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "acid",
		"conditions_applied": [],
		"effect": "Deals acid damage in a 5 ft. wide line. Half damage on a successful DEX save.",
	},
	"Poison Breath": {
		"description": "The creature exhales poisonous gas in a cone. Each creature in that area must make a Constitution saving throw, taking poison damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature (30-90 ft. cone)",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "poison",
		"conditions_applied": [],
		"effect": "Deals poison damage in a cone. Half damage on a successful CON save.",
	},
	"Steam Breath": {
		"description": "The creature exhales a cloud of scalding steam in a 60-foot cone. Each creature in that area must make a Constitution saving throw, taking fire damage on a failed save, or half as much on a successful one. Being underwater doesn't grant resistance against this damage.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft. cone",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "15d6",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Deals fire damage in a 60 ft. cone. Underwater does not grant resistance. Half damage on a successful CON save.",
	},
	"Weakening Breath": {
		"description": "The creature exhales weakening gas in a 60-foot cone. Each creature in that area must succeed on a Strength saving throw or have disadvantage on Strength-based attack rolls, Strength checks, and Strength saving throws for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft. cone",
		"duration": "1 minute",
		"target": "All creatures in cone",
		"saving_throw": "STR",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disadvantage on STR attacks, checks, and saves"],
		"effect": "Inflicts disadvantage on all STR-based rolls for 1 minute. No damage. Creatures may re-save each turn.",
	},
	"Blinding Breath": {
		"description": "The creature exhales a 15-foot cone of blinding dust or gas. Each creature in that area must succeed on a Dexterity saving throw or be blinded until the end of its next turn.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "15 ft. cone",
		"duration": "Until end of target's next turn",
		"target": "All creatures in cone",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Blinded"],
		"effect": "Blinds all creatures in a 15 ft. cone that fail a DEX save until the end of their next turn.",
	},
	"Mud Breath": {
		"description": "The creature exhales a 15-foot cone of mud. Each creature in that area must succeed on a Dexterity saving throw or be restrained until the end of its next turn.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "15 ft. cone",
		"duration": "Until end of target's next turn",
		"target": "All creatures in cone",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained"],
		"effect": "Restrains all creatures in a 15 ft. cone that fail a DEX save until the end of their next turn.",
	},
	"Cinder Breath": {
		"description": "The creature exhales a 15-foot cone of smoldering cinders. Each creature in that area must succeed on a Dexterity saving throw or take fire damage and have disadvantage on attack rolls and ability checks that rely on sight until the end of its next turn.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "15 ft. cone",
		"duration": "Until end of target's next turn",
		"target": "All creatures in cone",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "1d6",
		"damage_type": "fire",
		"conditions_applied": ["Disadvantage on sight-based attacks and checks"],
		"effect": "Deals 1d6 fire damage and inflicts disadvantage on sight-reliant rolls until the end of the target's next turn on a failed DEX save.",
	},
	"Psychic Breath": {
		"description": "The creature exhales psychic energy in a 60-foot cone. Each creature in that area must make an Intelligence saving throw, taking psychic damage on a failed save, or half as much on a successful one. A creature that fails the saving throw is also stunned until the end of its next turn.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft. cone",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "INT",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "psychic",
		"conditions_applied": ["Stunned"],
		"effect": "Deals psychic damage in a 60 ft. cone and stuns creatures that fail the INT save until the end of their next turn. Half damage on success.",
	},
	"Shadow Breath": {
		"description": "The creature exhales a 60-foot cone of shadow energy. Each creature in that area must make a Constitution saving throw, taking necrotic damage on a failed save, or half as much on a successful one. A humanoid killed by this damage rises as a shadow under the creature's control.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft. cone",
		"duration": "Instantaneous",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "necrotic",
		"conditions_applied": [],
		"effect": "Deals necrotic damage in a 60 ft. cone. Humanoids killed by this damage rise as shadows under the creature's control. Half damage on success.",
	},
	"Petrifying Breath": {
		"description": "The creature exhales petrifying gas in a 30-foot cone. Each creature in that area must succeed on a Constitution saving throw. On a failed save, the target is restrained and must repeat the saving throw at the end of its next turn. On a second failure, the target is petrified until freed by greater restoration or similar magic.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "30 ft. cone",
		"duration": "Until cured",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained", "Petrified"],
		"effect": "Restrains creatures that fail a CON save. A second failed save permanently petrifies them until cured by greater restoration or similar magic.",
	},
	"Antimagic Cone": {
		"description": "The creature's central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the creature decides which way the cone faces and whether the cone is active. The area works against the creature's own eye rays.",
		"action_type": "Passive",
		"recharge": "",
		"range": "150 ft. cone",
		"duration": "Permanent while active",
		"target": "All creatures and magic in cone",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates a 150 ft. antimagic cone that suppresses all magic, including the creature's own eye rays. Direction is chosen at the start of each turn.",
	},
	"Paralysis Gas": {
		"description": "The creature exhales a 30-foot cone of paralytic gas. Each creature in that area must succeed on a Constitution saving throw or be paralyzed for 1 minute. A paralyzed creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "30 ft. cone",
		"duration": "1 minute",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Paralyzed"],
		"effect": "Paralyzes creatures in a 30 ft. cone that fail a CON save for up to 1 minute. Creatures may re-save each turn.",
	},
	"Euphoria Breath": {
		"description": "The creature exhales a puff of euphoric gas at one creature within 5 feet of it. The target must succeed on a Wisdom saving throw or become poisoned for 1 minute. While poisoned in this way, the creature is incapacitated and experiences euphoria. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "5 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned", "Incapacitated"],
		"effect": "Target that fails a WIS save is Poisoned and Incapacitated for up to 1 minute while experiencing euphoria. Target may re-save each turn.",
	},
	"Stunning Breath": {
		"description": "The creature exhales stunning gas in a cone. Each creature in that area must succeed on a Constitution saving throw or be stunned until the end of its next turn.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature",
		"duration": "Until end of target's next turn",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Stunned"],
		"effect": "Stuns all creatures in a cone that fail a CON save until the end of their next turn.",
	},
}
