const DATA: Dictionary = {

	"Stone Camouflage": {
		"description": "The creature has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on Stealth checks while in rocky terrain.",
	},
	"Plant Camouflage": {
		"description": "The creature has advantage on Dexterity (Stealth) checks made to hide in terrain with ample plant life.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on Stealth checks while in areas with abundant vegetation.",
	},
	"Snow Camouflage": {
		"description": "The creature has advantage on Dexterity (Stealth) checks made to hide in snowy terrain.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on Stealth checks while in snowy terrain.",
	},
	"Light Sensitivity": {
		"description": "While in bright light, the creature has disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disadvantage on attacks and sight-based Perception in bright light"],
		"effect": "Disadvantage on attack rolls and sight-based Perception checks whenever the creature is in bright light.",
	},
	"Sunlight Sensitivity": {
		"description": "While in sunlight, the creature has disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disadvantage on attacks and sight-based Perception in sunlight"],
		"effect": "Disadvantage on attack rolls and sight-based Perception checks whenever the creature is in sunlight. Does not trigger in other bright light sources.",
	},
	"Sunlight Hypersensitivity": {
		"description": "The creature takes 20 radiant damage when it starts its turn in sunlight. While in sunlight, it has disadvantage on attack rolls and ability checks.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "20",
		"damage_type": "radiant",
		"conditions_applied": ["Disadvantage on attacks and ability checks in sunlight"],
		"effect": "Takes 20 radiant damage at the start of each turn in sunlight and suffers disadvantage on all attack rolls and ability checks.",
	},
	"Sunlight Banishment": {
		"description": "If the creature starts its turn in sunlight, it is instantly banished to the Ethereal Plane and remains there until the start of its next turn, at which point it returns to the space it left.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Until start of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature is automatically banished to the Ethereal Plane whenever it starts a turn in sunlight, returning at the start of its next turn.",
	},
	"Sun Sickness": {
		"description": "While in sunlight, the creature has disadvantage on ability checks, attack rolls, and saving throws. The creature dies if it spends more than 1 hour in direct sunlight.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disadvantage on all rolls in sunlight"],
		"effect": "Disadvantage on all rolls while in sunlight. Dies after 1 hour of direct sunlight exposure.",
	},
	"Devil's Sight": {
		"description": "Magical darkness doesn't impede the creature's darkvision. The creature can see normally in both natural and magical darkness.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can see through both natural and magical darkness as if it were normal light.",
	},
	"Water Bound": {
		"description": "The creature is mystically bound to a specific body of water and dies if it leaves that water.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature is permanently bound to a specific body of water. Leaving that water causes the creature to die.",
	},
	"Rooted": {
		"description": "The creature is anchored to the ground and cannot willingly move from its current position. It can still attack and use abilities against creatures within its reach.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature cannot move from its position but can still attack anything within reach.",
	},
	"Hellfire Vulnerability": {
		"description": "If the creature takes fire damage from any source other than hellfire, it is instantly destroyed. The creature can only regenerate in a location where hellfire is present.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Any fire damage not from hellfire instantly destroys the creature. Regeneration only functions in the presence of hellfire.",
	},
	"Fear of Fire": {
		"description": "If the creature takes fire damage, it has disadvantage on attack rolls and ability checks until the end of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Until end of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disadvantage on attacks and ability checks"],
		"effect": "Taking any fire damage imposes disadvantage on all attack rolls and ability checks until the end of the creature's next turn.",
	},
	"Shock Susceptibility": {
		"description": "If the creature takes lightning damage, its speed is halved and it has disadvantage on Dexterity saving throws until the end of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Until end of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Speed halved", "Disadvantage on DEX saves"],
		"effect": "Taking any lightning damage halves the creature's speed and imposes disadvantage on DEX saving throws until the end of its next turn.",
	},
	"Antimagic Susceptibility": {
		"description": "The creature is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the creature must succeed on a Constitution saving throw against the caster's spell save DC or fall unconscious for 1 minute.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Incapacitated in antimagic fields", "Unconscious if dispel magic succeeds"],
		"effect": "Incapacitated inside antimagic fields. Dispel magic forces a CON save or renders the creature unconscious for 1 minute.",
	},
	"Hold Breath": {
		"description": "The creature can hold its breath for an extended period of time before it begins to suffocate. The exact duration varies per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Varies per creature",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can remain submerged or in airless environments far longer than normal. Duration is defined per-creature.",
	},
	"Boneless": {
		"description": "The creature can move through and occupy a space as narrow as 6 inches wide without squeezing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can pass through gaps as narrow as 6 inches without any movement penalty.",
	},
	"Amorphous": {
		"description": "The creature can move through a space as narrow as 1 inch wide without squeezing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can pass through any gap at least 1 inch wide without squeezing.",
	},
	"Transparent": {
		"description": "Even when in plain sight, it takes a successful DC 15 Wisdom (Perception) check to spot the creature if it has neither moved nor attacked. A creature that enters the transparent creature's space while unaware of it is surprised.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Nearly invisible while stationary. Creatures that enter its space without knowing it's there are surprised.",
	},
	"Aberrant Ground": {
		"description": "The ground in a 10-foot radius around the creature is doughlike difficult terrain. Each creature that starts its turn in that area must succeed on a DC 10 Strength saving throw or have its speed reduced to 0 until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "Permanent",
		"target": "All creatures in 10 ft. radius",
		"saving_throw": "STR",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Speed reduced to 0"],
		"effect": "Creates a 10 ft. radius of difficult terrain. Creatures starting their turn in it must save or have their speed reduced to 0 until their next turn.",
	},
}
