const DATA: Dictionary = {

	"Life Drain": {
		"description": "The creature makes a melee attack that deals necrotic damage. The target must succeed on a Constitution saving throw or have its hit point maximum reduced by an amount equal to the damage taken. This reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until long rest",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "Varies per creature",
		"damage_type": "necrotic",
		"conditions_applied": ["HP maximum reduced by damage dealt"],
		"effect": "Deals necrotic damage and reduces the target's HP maximum by the same amount on a failed CON save. Lasts until a long rest. Target dies if HP maximum reaches 0.",
	},
	"Blood Drain": {
		"description": "The creature makes a melee attack that deals piercing and necrotic damage. Only usable against a willing, grappled, incapacitated, or restrained target. The target's hit point maximum is reduced by the necrotic damage dealt, and the creature regains hit points equal to the necrotic damage dealt.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until long rest",
		"target": "One willing, grappled, incapacitated, or restrained creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "piercing and necrotic",
		"conditions_applied": ["HP maximum reduced by necrotic damage dealt"],
		"effect": "Deals piercing and necrotic damage. Reduces the target's HP maximum by the necrotic portion and heals the attacker by the same amount. Requires a helpless or willing target.",
	},
	"Extract Brain": {
		"description": "The creature makes a melee attack targeting one incapacitated humanoid it has grappled. On a hit, the attack deals massive piercing damage. If this damage reduces the target to 0 hit points, the creature kills the target by extracting and devouring its brain.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One incapacitated humanoid grappled by the creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "10d10",
		"damage_type": "piercing",
		"conditions_applied": [],
		"effect": "Deals 10d10 piercing damage to a grappled, incapacitated humanoid. Instantly kills the target if it is reduced to 0 hit points.",
	},
	"Consume Life": {
		"description": "As a bonus action, the creature targets one creature it can see within 5 feet that has 0 hit points and is still alive. The target must succeed on a DC 10 Constitution saving throw or die. If the target dies, the creature regains 10 (3d6) hit points.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One creature at 0 HP that is still alive",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "3d6",
		"damage_type": "necrotic",
		"conditions_applied": ["Death on failed save"],
		"effect": "Forces a dying creature to save or die outright. If the creature dies, the attacker regains 3d6 hit points.",
	},
	"Psychic Feast": {
		"description": "The creature drains the memories and life energy of one incapacitated creature within 5 feet of it. The target takes psychic damage, and the creature gains temporary hit points equal to the damage dealt.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One incapacitated creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "4d10",
		"damage_type": "psychic",
		"conditions_applied": [],
		"effect": "Deals 4d10 psychic damage to an incapacitated target. The attacker gains temporary hit points equal to the damage dealt.",
	},
	"Brain Collection": {
		"description": "When the creature kills a humanoid, it can harvest that creature's brain as a bonus action if the body is within 5 feet. The creature can store up to 6 brains at a time, and each stored brain enhances its spellcasting and psychic abilities.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "One humanoid killed by the creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Harvests a brain from a humanoid the creature has just killed. Up to 6 brains can be stored, each increasing the creature's psychic and spellcasting power.",
	},
}
