const DATA: Dictionary = {

	"Fly": {
		"description": "The creature has a flying speed and can move through the air. It falls if knocked prone or its flying speed is reduced to 0 feet.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants a flying speed. Creature falls if knocked prone or flying speed is reduced to 0.",
	},
	"Spider Climb": {
		"description": "The creature can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can climb any surface, including ceilings, without an ability check.",
	},
	"Burrow": {
		"description": "The creature can burrow through nonmagical, unworked earth and stone. While doing so, it doesn't disturb the material it moves through unless it has a specific trait stating otherwise.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants a burrowing speed through earth and stone without disturbing the material. Speed is defined per-creature.",
	},
	"Teleport": {
		"description": "The creature magically teleports, along with any equipment it is wearing or carrying, up to a set distance to an unoccupied space it can see.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature instantly moves to any unoccupied space it can see within range. Range is defined per-creature.",
	},
	"Levitate": {
		"description": "The creature can magically rise or descend vertically and remain suspended in the air. It cannot move horizontally under its own power while levitating unless it has another form of movement.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can rise and descend vertically without wings or climbing. Cannot move horizontally unless another movement trait allows it.",
	},
	"Incorporeal Movement": {
		"description": "The creature can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "1d10",
		"damage_type": "force",
		"conditions_applied": [],
		"effect": "Creature passes through other creatures and objects. Takes 1d10 force damage if it ends its turn inside an object.",
	},
	"Earth Glide": {
		"description": "The creature can glide through nonmagical, unworked earth and stone as effortlessly as a fish moves through water. While doing so, it doesn't disturb the material it moves through.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature moves through earth and stone without effort and without leaving a tunnel or disturbing the material.",
	},
	"Air Form": {
		"description": "The creature can enter a hostile creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can pass through any gap 1 inch or wider and occupy enemy spaces.",
	},
	"Water Form": {
		"description": "The creature can enter a hostile creature's space and stop there. It can move through a space as narrow as 1 inch wide without squeezing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can pass through any gap 1 inch or wider and occupy enemy spaces.",
	},
	"Liquid Form": {
		"description": "The creature can move through a space as narrow as 1 inch wide without squeezing and can enter a hostile creature's space and stop there.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can squeeze through gaps as narrow as 1 inch and occupy enemy spaces.",
	},
	"Amphibious": {
		"description": "The creature can breathe both air and water.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can survive and breathe in both air and water environments.",
	},
	"Water Breathing": {
		"description": "The creature can breathe only underwater.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can breathe underwater but cannot breathe air unless another trait states otherwise.",
	},
	"Tree Stride": {
		"description": "Once on each of the creature's turns, it can use 10 feet of its movement to step magically into one living tree within its reach and emerge from a second living tree within 60 feet of the first tree, appearing in an unoccupied space within 5 feet of the second tree.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can teleport between two living trees within 60 ft. of each other, costing only 10 ft. of movement.",
	},
	"Shadow Teleportation": {
		"description": "The creature magically teleports to an unoccupied space it can see within range, provided that both the creature and the destination are in dim light or darkness.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Teleports up to 30 ft. to a visible unoccupied space. Both origin and destination must be in dim light or darkness.",
	},
	"Fey Step": {
		"description": "The creature magically teleports up to 30 feet to an unoccupied space it can see.",
		"action_type": "Bonus Action",
		"recharge": "Short Rest",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Teleports up to 30 ft. to any visible unoccupied space. Recharges on a short or long rest.",
	},
	"Ethereal Jaunt": {
		"description": "As a bonus action, the creature can magically shift from the Material Plane to the Ethereal Plane, or vice versa.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until start of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature shifts between the Material and Ethereal Planes. While ethereal it is invisible and can pass through solid objects.",
	},
	"Etherealness": {
		"description": "The creature enters the Ethereal Plane from the Material Plane, or vice versa. It is visible on the Material Plane while in the Border Ethereal, yet it can't affect or be affected by anything on the other plane.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Up to 1 hour",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature fully transitions to the Ethereal Plane and cannot interact with creatures on the Material Plane, and vice versa.",
	},
	"Telekinetic Leap": {
		"description": "The creature uses telekinetic force to cause itself or one creature within 30 feet of it to jump up to 30 feet in any direction, including upward.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "Self or one creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Propels itself or a creature within 30 ft. up to 30 ft. in any direction.",
	},
	"Running Leap": {
		"description": "With a 10-foot running start, the creature can long jump up to a distance defined by its stat block.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Greatly extends long jump distance when the creature has a 10 ft. running start. Distance is defined per-creature.",
	},
	"Standing Leap": {
		"description": "The creature's long jump and high jump distances are unusually large, and it can achieve these distances with or without a running start.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can jump exceptional distances from a standing position. Distances are defined per-creature.",
	},
	"Deadly Leap": {
		"description": "If the creature jumps at least 15 feet as part of its movement, it can use this action to land on its feet in a space containing one or more creatures. Each creature in that space must succeed on a Strength or Dexterity saving throw or be knocked prone and take bludgeoning and slashing damage. On a success, the target takes half damage, isn't knocked prone, and is pushed 5 feet out of the creature's space.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "All creatures in landing space",
		"saving_throw": "STR or DEX",
		"save_dc_stat": "STR",
		"damage_dice": "Varies per creature",
		"damage_type": "bludgeoning and slashing",
		"conditions_applied": ["Prone"],
		"effect": "After a 15 ft. jump, creature lands on enemies dealing damage and knocking them prone on a failed STR or DEX save.",
	},
	"Web Walk": {
		"description": "The creature ignores movement restrictions caused by webbing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature moves freely through webs and webbing without any movement penalty or restrained condition.",
	},
	"Flyby": {
		"description": "The creature doesn't provoke opportunity attacks when it flies out of an enemy's reach.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature can fly past and away from enemies without triggering opportunity attacks.",
	},
	"Ride the Wind": {
		"description": "Until the end of its next turn, the creature's flying speed increases to 100 feet and it is immune to the stunned condition.",
		"action_type": "Bonus Action",
		"recharge": "5-6",
		"range": "Self",
		"duration": "Until end of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Flying speed surges to 100 ft. and creature becomes immune to stunned until the end of its next turn.",
	},
}
