const DATA: Dictionary = {

	"Multiattack": {
		"description": "The creature makes multiple attacks on its turn. The number and type of attacks vary per creature.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Varies per creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature makes multiple attacks in a single action. Number and type of attacks are defined per-creature.",
	},
	"Pack Tactics": {
		"description": "The creature has advantage on an attack roll against a creature if at least one of the attacker's allies is within 5 feet of the target and that ally isn't incapacitated.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants advantage on attack rolls whenever an unincapacitated ally is within 5 ft. of the target.",
	},
	"Pounce": {
		"description": "If the creature moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a Strength saving throw or be knocked prone. If the target is knocked prone, the creature can make one additional attack against it as a bonus action.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Prone"],
		"effect": "After moving 20 ft. straight toward a target and hitting with a claw, the target must save or be knocked prone. A prone target can be struck with a bonus action attack.",
	},
	"Charge": {
		"description": "If the creature moves at least 20 feet straight toward a target and then hits it with an attack on the same turn, the target takes extra damage. Some variants also force the target to make a Strength saving throw or be knocked prone.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "Varies per creature",
		"damage_type": "Varies per creature",
		"conditions_applied": ["Prone"],
		"effect": "After moving 20 ft. straight toward a target and hitting, deals extra damage. Some variants also knock the target prone on a failed STR save.",
	},
	"Trampling Charge": {
		"description": "If the creature moves at least 20 feet straight toward a creature and then hits it with an attack on the same turn, that target must succeed on a Strength saving throw or be knocked prone. If the target is knocked prone, the creature can make one stomp attack against it as a bonus action.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Prone"],
		"effect": "After moving 20 ft. and hitting, target must save or be knocked prone. A prone target can be hit with a bonus action stomp.",
	},
	"Rolling Charge": {
		"description": "If the creature moves at least 20 feet straight toward a target in a rolling or tumbling motion and then hits it with a slam attack on the same turn, the target takes extra bludgeoning damage and must succeed on a Strength saving throw or be knocked prone.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "Varies per creature",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Prone"],
		"effect": "After rolling 20 ft. toward a target and hitting with a slam, deals extra bludgeoning damage and knocks the target prone on a failed STR save.",
	},
	"Blood Frenzy": {
		"description": "The creature has advantage on melee attack rolls against any creature that doesn't have all its hit points.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all melee attack rolls against any creature that is missing at least 1 hit point.",
	},
	"Martial Advantage": {
		"description": "Once per turn, the creature can deal extra damage to a creature it hits with a weapon attack if that creature is within 5 feet of an ally of the creature that isn't incapacitated.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "One creature within 5 ft. of an ally",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d6",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "Once per turn, deals an extra 2d6 damage on a weapon hit when an unincapacitated ally is within 5 ft. of the target.",
	},
	"Sneak Attack": {
		"description": "Once per turn, the creature deals extra damage when it hits a target with a finesse or ranged weapon attack and has advantage on the roll, or when at least one ally is within 5 feet of the target and the creature doesn't have disadvantage on the roll.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "Once per turn, deals extra damage when attacking with advantage or when an ally is adjacent to the target. Amount scales per creature.",
	},
	"Assassinate": {
		"description": "During its first turn in combat, the creature has advantage on attack rolls against any creature that hasn't taken a turn yet. Any hit the creature scores against a surprised creature is a critical hit.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "First turn of combat",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on attacks against creatures that haven't acted yet. All hits against surprised creatures are automatically critical hits.",
	},
	"Surprise Attack": {
		"description": "If the creature surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 2d6 damage from the attack.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "First round of combat",
		"target": "One surprised creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d6",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "Deals an extra 2d6 damage on the first hit against a surprised creature in the opening round of combat.",
	},
	"Ambusher": {
		"description": "The creature has advantage on attack rolls against any creature it has surprised.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all attack rolls against any creature that is currently surprised.",
	},
	"Dive Attack": {
		"description": "If the creature is flying and dives at least 30 feet straight toward a target and then hits it with a melee weapon attack, the attack deals an extra 2d8 damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d8",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "Deals an extra 2d8 damage when diving at least 30 ft. from flight before landing a melee hit.",
	},
	"Reckless": {
		"description": "At the start of its turn, the creature can choose to gain advantage on all melee weapon attack rolls during that turn. If it does, attack rolls against it have advantage until the start of its next turn.",
		"action_type": "Free Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until start of next turn",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Optionally grants advantage on all melee attacks for the turn in exchange for granting enemies advantage on attacks against the creature until its next turn.",
	},
	"Siege Monster": {
		"description": "The creature deals double damage to objects and structures.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Objects and structures",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "All damage dealt to objects and structures is doubled.",
	},
	"Brute": {
		"description": "A melee weapon deals one extra die of its damage when the creature hits with it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "+1 weapon damage die",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "All melee weapon attacks roll one additional damage die.",
	},
	"Rampage": {
		"description": "When the creature reduces a creature to 0 hit points with a melee attack on its turn, it can take a bonus action to move up to half its speed and make a bite attack.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Killing a creature with a melee attack triggers a free bonus action: move up to half speed and make one bite attack.",
	},
	"Hunger Frenzy": {
		"description": "When the creature starts its turn within 5 feet of a creature, it must use its action to make one bite attack against that creature. If no creature is within reach, it must take the Dash action to move toward the nearest creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "Nearest creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature is compelled to bite the nearest creature within reach each turn. If none are in reach, it must dash toward the closest one.",
	},
	"Battle Cry": {
		"description": "Each creature of the creature's choice within 30 feet that can hear it gains advantage on attack rolls until the start of the creature's next turn. The creature can then make one weapon attack as a bonus action.",
		"action_type": "Bonus Action",
		"recharge": "Short Rest",
		"range": "30 ft.",
		"duration": "Until start of creature's next turn",
		"target": "All chosen allies within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Chosen allies within 30 ft. gain advantage on attack rolls until the next turn. The creature also makes one free weapon attack as a bonus action.",
	},
	"Leadership": {
		"description": "For 1 minute, the creature can utter a special command whenever a nonhostile creature it can see within 30 feet makes an attack roll or saving throw. The target can add a d4 to its roll provided it can hear and understand the creature. Only one Leadership die can benefit a creature at a time. This effect ends if the creature is incapacitated.",
		"action_type": "Action",
		"recharge": "Short Rest",
		"range": "30 ft.",
		"duration": "1 minute",
		"target": "All nonhostile creatures within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "For 1 minute, allies within 30 ft. can add 1d4 to their attack rolls and saving throws. Ends early if the creature is incapacitated.",
	},
	"Rally": {
		"description": "The creature lets out a rallying cry, causing each ally of its choice within 30 feet that can hear it to regain hit points.",
		"action_type": "Action",
		"recharge": "Short Rest",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "Chosen allies within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d6",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Chosen allies within 30 ft. regain 2d6 hit points.",
	},
	"Cunning Action": {
		"description": "On each of its turns, the creature can use a bonus action to take the Dash, Disengage, or Hide action.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can Dash, Disengage, or Hide as a bonus action on every turn.",
	},
	"Nimble Escape": {
		"description": "The creature can take the Disengage or Hide action as a bonus action on each of its turns.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can Disengage or Hide as a bonus action on every turn.",
	},
	"Redirect Attack": {
		"description": "When a creature misses this creature with a melee attack, it can choose another ally within 5 feet of itself. The missed attack instead targets that ally.",
		"action_type": "Reaction",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One ally within 5 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "When a melee attack misses, redirects it to a nearby ally as a reaction.",
	},
	"Reaping Arms": {
		"description": "As a bonus action, the creature sweeps its arms in a wide arc, forcing each creature within 10 feet to make a Dexterity saving throw. On a failed save, a target takes 4d8 bludgeoning damage. On a successful save, it takes half damage.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "Instantaneous",
		"target": "All creatures within 10 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "STR",
		"damage_dice": "4d8",
		"damage_type": "bludgeoning",
		"conditions_applied": [],
		"effect": "Deals 4d8 bludgeoning damage to all creatures within 10 ft. Half damage on a successful DEX save.",
	},
	"Crushing Advance": {
		"description": "While the creature is moving, it can move through the space of any creature that is Huge or smaller. Each creature whose space it enters must make a Dexterity saving throw. On a failed save, the creature is knocked prone and takes 4d10 bludgeoning damage. On a successful save, it takes half the damage and isn't knocked prone.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "All Huge or smaller creatures in movement path",
		"saving_throw": "DEX",
		"save_dc_stat": "STR",
		"damage_dice": "4d10",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Prone"],
		"effect": "While moving, tramples through Huge and smaller creatures. Each takes 4d10 bludgeoning damage and is knocked prone on a failed DEX save. Half damage and no prone on success.",
	},
	"Acid Spray": {
		"description": "The creature spits acid in a 30-foot line that is 5 feet wide. Each creature in that line must make a Dexterity saving throw, taking 3d6 acid damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "6",
		"range": "30 ft. line",
		"duration": "Instantaneous",
		"target": "All creatures in line",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "3d6",
		"damage_type": "acid",
		"conditions_applied": [],
		"effect": "Sprays a 30 ft. line of acid dealing 3d6 acid damage. Half damage on a successful DEX save.",
	},
	"Lightning Blood": {
		"description": "When the creature takes piercing or slashing damage while it has at least 1 hit point, each creature within 5 feet of it takes 2d6 lightning damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "All creatures within 5 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d6",
		"damage_type": "lightning",
		"conditions_applied": [],
		"effect": "Retaliates automatically with 2d6 lightning damage to all nearby creatures whenever it takes piercing or slashing damage.",
	},
	"Fiendish Blessing": {
		"description": "The creature is blessed by fiendish power. Its Armor Class includes its Charisma modifier in addition to any other AC bonuses.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature's Charisma modifier is added to its Armor Class.",
	},
	"Gruumsh's Fury": {
		"description": "When the creature hits with any weapon, the weapon deals one extra die of its damage type.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "+1 weapon damage die",
		"damage_type": "same as weapon",
		"conditions_applied": [],
		"effect": "Every weapon attack rolls one additional damage die.",
	},
	"Vorpal Jaws": {
		"description": "A critical hit from this creature's bite attack decapitates the target if the target is not more than one size larger than the creature. A decapitated creature dies immediately unless it can survive without its head.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Death"],
		"effect": "Critical hits with the bite decapitate the target (up to one size larger), causing instant death unless they can survive without a head.",
	},
}
