const DATA: Dictionary = {

	"Magic Resistance": {
		"description": "The creature has advantage on saving throws against spells and other magical effects.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all saving throws against spells and magical effects.",
	},
	"Legendary Resistance": {
		"description": "If the creature fails a saving throw, it can choose to succeed instead. It can use this ability a limited number of times per day, typically three.",
		"action_type": "Free Action",
		"recharge": "3/Day",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Converts a failed saving throw into a success. Usable 3 times per day. Uses per day vary per creature.",
	},
	"Undead Fortitude": {
		"description": "If damage reduces the creature to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the creature drops to 1 hit point instead.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "When reduced to 0 HP, makes a CON save (DC 5 + damage taken) to drop to 1 HP instead. Fails automatically against radiant damage or critical hits.",
	},
	"Turn Immunity": {
		"description": "The creature is immune to effects that turn undead, such as a cleric's Turn Undead feature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Cannot be turned by Turn Undead or any similar effect.",
	},
	"Turn Resistance": {
		"description": "The creature has advantage on saving throws against any effect that turns undead.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all saving throws against Turn Undead and similar effects.",
	},
	"Immutable Form": {
		"description": "The creature is immune to any spell or effect that would alter its form, such as polymorph or petrification.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to polymorph, petrification, and any other effect that would change the creature's physical form.",
	},
	"False Appearance": {
		"description": "While the creature remains motionless, it is indistinguishable from an ordinary inanimate object or a natural feature of its environment.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Perfectly mimics an inanimate object while motionless. Creatures must inspect it closely to detect the deception.",
	},
	"Avoidance": {
		"description": "If the creature is subjected to an effect that allows it to make a saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "On any save-for-half-damage effect: success means no damage, failure means half damage.",
	},
	"Reflective Carapace": {
		"description": "Any time the creature is targeted by a magic missile spell, a line spell, or a spell that requires a ranged attack roll, roll a d6. On a 1-5, the creature is unaffected. On a 6, the creature is unaffected and the effect is reflected back at the caster as if it originated from the creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Roll 1d6 whenever targeted by magic missile, a line spell, or a ranged spell attack. 1-5: no effect on creature. 6: spell is reflected back at the caster.",
	},
	"Displacement": {
		"description": "The creature projects a magical illusion that makes it appear to be standing near its actual location, causing attack rolls against it to have disadvantage. If it is hit by an attack, this trait is disrupted until the end of its next turn. This trait is also disrupted while the creature is incapacitated or has a speed of 0.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "All attack rolls against the creature have disadvantage. Disrupted until the end of the creature's next turn whenever it is hit.",
	},
	"Psychic Defense": {
		"description": "While the creature is not wearing armor, its Armor Class includes its Wisdom modifier.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Wisdom modifier is added to AC while the creature is unarmored.",
	},
	"Shielded Mind": {
		"description": "The creature is immune to scrying and to any effect that would sense its emotions, read its thoughts, or detect its location.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to scrying, thought-reading, emotion-sensing, and magical location detection of any kind.",
	},
	"Limited Magic Immunity": {
		"description": "The creature can't be affected or detected by spells of a set level or lower unless it wishes to be. It has advantage on saving throws against all other spells and magical effects. The level threshold varies per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to spells at or below a set spell level. Advantage on saves against higher-level magic. Immunity threshold is defined per-creature.",
	},
	"Fey Ancestry": {
		"description": "The creature has advantage on saving throws against being charmed, and magic can't put the creature to sleep.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on saving throws against the charmed condition. Completely immune to magical sleep effects.",
	},
	"Axiomatic Mind": {
		"description": "The creature can't be compelled to act against its hierarchical nature by magical or mundane means.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Cannot be magically or mundanely forced to act against its innate nature or hierarchy.",
	},
	"Steadfast": {
		"description": "The creature can't be frightened while it can see an allied creature within 30 feet of it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to the frightened condition as long as at least one ally is visible within 30 ft.",
	},
	"Spell Immunity": {
		"description": "The creature is immune to specific named spells as chosen when the creature is created. The spells it is immune to are defined per-creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Completely immune to a defined set of specific spells. Which spells are immune is defined per-creature.",
	},
	"Magic Weapons": {
		"description": "The creature's weapon attacks are magical, allowing them to bypass resistance and immunity to nonmagical attacks and damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "All weapon attacks count as magical for the purpose of overcoming damage resistance and immunity.",
	},
	"Sure-Footed": {
		"description": "The creature has advantage on Strength and Dexterity saving throws made against effects that would knock it prone.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on STR and DEX saving throws against any effect that would knock the creature prone.",
	},
	"Evasion": {
		"description": "If the creature is subjected to an effect that allows it to make a Dexterity saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "On DEX save-for-half-damage effects: success means no damage, failure means half damage.",
	},
	"Selective Senses": {
		"description": "The creature can focus its senses on one creature it can see within 60 feet. Whenever that creature attempts to hide or escape the creature's notice, it is automatically detected. The creature can track its quarry across planar boundaries.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Until changed",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Locks onto one target within 60 ft. That target cannot hide from or escape the creature's detection, even across planes.",
	},
	"Reactive": {
		"description": "The creature can take one reaction on every turn in combat, rather than just once per round.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creature gains one reaction at the start of every turn in combat, not just at the start of each round.",
	},
	"Parry": {
		"description": "The creature adds a bonus to its AC against one melee attack that would hit it. To do so, the creature must see the attacker and be wielding a melee weapon. The AC bonus varies per creature.",
		"action_type": "Reaction",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "As a reaction, adds a bonus to AC against one incoming melee attack. Requires sight of the attacker and a wielded melee weapon. Bonus amount varies per creature.",
	},
	"Shield": {
		"description": "When a creature makes an attack against the wearer of the guardian's amulet, the guardian grants a +2 bonus to the wearer's AC if the guardian is within 5 feet of the wearer.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "Bonded creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants a +2 AC bonus to a bonded creature whenever it is attacked, provided the creature is within 5 ft. of it.",
	},
	"Dark Devotion": {
		"description": "The creature's devotion to its dark master grants it advantage on saving throws against being charmed or frightened.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on saving throws against both the charmed and frightened conditions.",
	},
	"Brave": {
		"description": "The creature has advantage on saving throws against being frightened.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all saving throws against the frightened condition.",
	},
}
