const DATA: Dictionary = {

	"Mind Blast": {
		"description": "The creature magically emits psychic energy in a 60-foot cone. Each creature in that area must succeed on an Intelligence saving throw or take psychic damage and be stunned for 1 minute. A stunned creature can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft. cone",
		"duration": "1 minute",
		"target": "All creatures in cone",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "4d8+4",
		"damage_type": "psychic",
		"conditions_applied": ["Stunned"],
		"effect": "Deals psychic damage in a 60 ft. cone and stuns creatures on a failed INT save for up to 1 minute. Creatures may re-save each turn.",
	},
	"Psychic Feast": {
		"description": "The creature drains the memories and life energy of one incapacitated creature within 5 feet. The target takes psychic damage, and the creature gains temporary hit points equal to the damage dealt.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One incapacitated creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "4d10",
		"damage_type": "psychic",
		"conditions_applied": [],
		"effect": "Deals 4d10 psychic damage to an incapacitated target. The attacker gains temporary hit points equal to the damage dealt.",
	},
	"Devour Intellect": {
		"description": "The creature targets one creature it can see within 10 feet that has a brain. The target must make an Intelligence saving throw. On a failed save, the target takes psychic damage and rolls a d6. If the roll is less than or equal to the target's Intelligence score, that score is reduced by the rolled amount. If the target's Intelligence is reduced to 0, it is stunned until it regains at least 1 point of Intelligence.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "Until Intelligence is restored",
		"target": "One creature with a brain",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "2d10",
		"damage_type": "psychic",
		"conditions_applied": ["Intelligence score reduced", "Stunned if INT reduced to 0"],
		"effect": "Deals 2d10 psychic damage and rolls a d6 to potentially reduce the target's Intelligence score by that amount on a failed save. Target is stunned if INT drops to 0.",
	},
	"Body Thief": {
		"description": "The creature initiates a contest of wills with one incapacitated humanoid within 5 feet. If it wins the contest, it magically consumes the target's brain, teleports into the target's skull, and takes full control of the target's body. The creature uses the host's physical statistics but retains its own Intelligence, Wisdom, Charisma, telepathy, and traits.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until evicted or host dies",
		"target": "One incapacitated humanoid",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Host body controlled", "Brain consumed"],
		"effect": "On a won contest, consumes the target's brain and possesses the body. Creature has total cover inside the host and adopts the host's physical stats while keeping its own mental stats.",
	},
	"Eat Memories": {
		"description": "The creature targets one creature it can see within 5 feet. The target must make an Intelligence saving throw. On a failed save, the creature consumes the target's memories, dealing psychic damage. The target must succeed on a second Intelligence saving throw or lose all memory of events from the past 24 hours.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent until restored",
		"target": "One creature",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "4d8",
		"damage_type": "psychic",
		"conditions_applied": ["24 hours of memories erased on second failed save"],
		"effect": "Deals 4d8 psychic damage on a failed INT save. A second failed INT save erases all memories from the past 24 hours.",
	},
	"Psychic Link": {
		"description": "The creature targets one incapacitated creature within 1 mile that has a brain. The target must succeed on a Wisdom saving throw or become psionically linked to the creature. While linked, the creature always knows the target's location and can communicate telepathically with it over any distance. The target can repeat the saving throw at the end of each long rest.",
		"action_type": "Action",
		"recharge": "",
		"range": "1 mile",
		"duration": "Until save succeeds on long rest",
		"target": "One incapacitated creature with a brain",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Location always known to caster", "Telepathic link established"],
		"effect": "Establishes a psionic link on a failed WIS save. Creature always knows the target's location and can communicate telepathically at any range. Target re-saves on each long rest.",
	},
	"Psychic Orb": {
		"description": "The creature hurls a ball of concentrated psychic energy at one creature it can see within 90 feet. The target must make an Intelligence saving throw, taking psychic damage on a failed save, or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "",
		"range": "90 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "6d8",
		"damage_type": "psychic",
		"conditions_applied": [],
		"effect": "Deals 6d8 psychic damage to one target on a failed INT save. Half damage on success.",
	},
	"Psychic Spittle": {
		"description": "The creature spits a wad of psychic energy at one creature within 60 feet. The target must make an Intelligence saving throw, taking psychic damage on a failed save, or half as much on a successful one. On a failed save, the target is also frightened until the end of its next turn.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Until end of target's next turn",
		"target": "One creature",
		"saving_throw": "INT",
		"save_dc_stat": "INT",
		"damage_dice": "3d6",
		"damage_type": "psychic",
		"conditions_applied": ["Frightened"],
		"effect": "Deals 3d6 psychic damage and frightens the target until the end of its next turn on a failed INT save. Half damage and no fear on success.",
	},
	"Whispers of Madness": {
		"description": "The creature targets up to three creatures within 60 feet that it can see. Each target must succeed on a Wisdom saving throw or take psychic damage and use its reaction to immediately make a melee attack against one creature of the attacker's choice. Creatures immune to the charmed condition are unaffected.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Instantaneous",
		"target": "Up to three creatures",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "1d8+3",
		"damage_type": "psychic",
		"conditions_applied": ["Forced reaction melee attack"],
		"effect": "Deals 1d8+3 psychic damage and forces each failed target to use their reaction to make a melee attack against a chosen creature. Targets immune to charm are unaffected.",
	},
	"Bolts of Madness": {
		"description": "The creature targets one creature it can see within 90 feet. The target must make a Wisdom saving throw, taking psychic damage on a failed save, or half as much on a successful one. On a failed save, the target also has disadvantage on its next attack roll, ability check, or saving throw.",
		"action_type": "Action",
		"recharge": "",
		"range": "90 ft.",
		"duration": "Until next roll",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "4d10",
		"damage_type": "psychic",
		"conditions_applied": ["Disadvantage on next attack roll, ability check, or saving throw"],
		"effect": "Deals 4d10 psychic damage and inflicts disadvantage on the target's next roll on a failed WIS save. Half damage and no disadvantage on success.",
	},
	"Nightmare Haunting": {
		"description": "While a humanoid sleeps, the creature can magically enter its dreams if on the same plane of existence. If successful, the target must make a Wisdom saving throw. On a failed save, the target's hit point maximum is reduced by 2d6 and the creature regains hit points equal to that amount. The reduction lasts until removed by greater restoration or similar magic. The target dies if this reduces its hit point maximum to 0.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "Same plane of existence",
		"duration": "Until magically cured",
		"target": "One sleeping humanoid",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "2d6",
		"damage_type": "necrotic",
		"conditions_applied": ["HP maximum reduced by damage dealt"],
		"effect": "Invades a sleeping humanoid's dreams. On a failed WIS save, reduces the target's HP maximum by 2d6 and heals the creature by the same amount. Requires greater restoration to cure. Target dies if HP max reaches 0.",
	},
	"Dominate": {
		"description": "The creature targets one creature it can see within 300 feet. The target must succeed on a Wisdom saving throw or be magically dominated. While dominated, the target must obey the creature's commands and cannot take reactions. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "300 ft.",
		"duration": "Until save succeeds",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Dominated", "Cannot take reactions"],
		"effect": "Forces total obedience on a failed WIS save. Dominated target obeys all commands and loses reactions. Target re-saves at the end of each of its turns.",
	},
	"Enslave": {
		"description": "The creature targets one creature it can see within 30 feet. The target must succeed on a Wisdom saving throw or be magically enslaved until the creature dies or is on a different plane of existence. The enslaved target is charmed, can't take reactions, and can communicate telepathically with its enslaver over any distance.",
		"action_type": "Action",
		"recharge": "3/Day",
		"range": "30 ft.",
		"duration": "Until enslaver dies or changes plane",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed", "Cannot take reactions", "Telepathic link with enslaver"],
		"effect": "Permanently enslaves a target on a failed WIS save until the enslaver dies or leaves the plane. Enslaved creatures are charmed, lose reactions, and share a telepathic link.",
	},
	"Mental Bondage": {
		"description": "The creature targets one creature it can see within 30 feet. The target must succeed on a Wisdom saving throw or be magically charmed until the creature dies or is on a different plane of existence. The charmed target obeys the creature's commands and can communicate telepathically with it over any distance, but can't take reactions.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until enslaver dies or changes plane",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed", "Cannot take reactions", "Telepathic link with enslaver"],
		"effect": "Charms a target on a failed WIS save, compelling obedience and establishing a telepathic link. Lasts until the creature dies or leaves the plane.",
	},
	"Fear": {
		"description": "The creature targets one creature it can see within 60 feet. The target must succeed on a Wisdom saving throw or become frightened for 1 minute. The frightened creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Frightens one target on a failed WIS save for up to 1 minute. Target may re-save at the end of each of its turns.",
	},
	"Confusing Gaze": {
		"description": "When a creature starts its turn within 30 feet of this creature and can see its eyes, it must make a Charisma saving throw or lose control of its actions. On a failed save, it can't take reactions and rolls a d8 to determine its action: 1-4 it does nothing, 5-6 it moves in a random direction, 7-8 it makes a melee attack against a random creature in reach.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until start of target's next turn",
		"target": "All creatures within 30 ft. that can see the creature's eyes",
		"saving_throw": "CHA",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Cannot take reactions", "Random action (d8 table)"],
		"effect": "Creatures starting their turn within 30 ft. that see the creature's eyes must save or lose control of their turn and reactions, rolling randomly to determine behavior.",
	},
	"Weird Insight": {
		"description": "The creature targets one creature it can see within 30 feet. The target must contest its Charisma (Deception) check against the creature's Wisdom (Insight) check. If the creature wins, it magically learns one fact or secret about the target. The target is aware that something probed its mind.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "Contested (Deception vs Insight)",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Contests Deception vs Insight. On a win, learns one secret or fact about the target. The target knows its mind was probed.",
	},
	"Rotting Gaze": {
		"description": "The creature targets one creature it can see within 30 feet. The target must succeed on a Constitution saving throw or take necrotic damage as the creature's withering gaze decays the target's flesh.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "WIS",
		"damage_dice": "3d6",
		"damage_type": "necrotic",
		"conditions_applied": [],
		"effect": "Deals 3d6 necrotic damage to one target on a failed CON save.",
	},
	"Rebus Speech": {
		"description": "The creature communicates by projecting floating pictograms and symbols into the air rather than using spoken language. These rebuses can only be understood by creatures under the effect of comprehend languages or a similar magical effect.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Communicates exclusively through floating pictograms. Speech is unintelligible without comprehend languages or equivalent magic.",
	},
}
