const DATA: Dictionary = {

	"Regeneration": {
		"description": "The creature regains a set number of hit points at the start of each of its turns if it has at least 1 hit point. The creature does not regenerate if it took a specific damage type during the previous turn. The amount regained and the suppressing damage type vary per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Regains a set amount of HP at the start of each turn. Suppressed for one turn if the creature took a specific damage type the previous turn. Both the HP amount and suppressing damage type are defined per-creature.",
	},
	"Rejuvenation": {
		"description": "If the creature is destroyed, it re-forms after a set period of time with all its hit points, unless a specific condition was met at the time of its destruction. The re-formation time and the condition that permanently prevents it vary per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Returns to life with full HP after being destroyed unless a specific condition was fulfilled at death. Re-formation time and the permanent-death condition are defined per-creature.",
	},
	"Relentless": {
		"description": "If damage reduces the creature to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken. On a success, the creature drops to 1 hit point instead. This ability recharges on a short or long rest.",
		"action_type": "Passive",
		"recharge": "Short Rest",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "When reduced to 0 HP, makes a CON save (DC 5 + damage taken) to survive at 1 HP instead. Recharges on a short or long rest.",
	},
	"Healing Touch": {
		"description": "The creature touches another creature. The target magically regains hit points and is freed from any curse, disease, poison, blindness, and deafness. The amount healed and the number of daily uses vary per creature.",
		"action_type": "Action",
		"recharge": "3/Day",
		"range": "Touch",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "4d8+2",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Target regains 4d8+2 HP and is instantly cured of all curses, diseases, poisons, blindness, and deafness. Usable 3 times per day.",
	},
	"Berserk": {
		"description": "Whenever the creature starts its turn at or below a HP threshold, roll a d6. On a 6, the creature goes berserk. While berserk, it attacks the nearest creature each turn regardless of allegiance. If no creature is in reach, it attacks an object. Once berserk, it remains so until it is destroyed or regains all its hit points. The HP threshold varies per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Until destroyed or fully healed",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Berserk"],
		"effect": "When below a set HP threshold, rolls a d6 at the start of each turn. On a 6, enters an uncontrolled rage, attacking the nearest creature or object with no regard for allegiance until destroyed or fully healed. HP threshold is defined per-creature.",
	},
}
