const DATA: Dictionary = {

	"Keen Sight": {
		"description": "The creature has advantage on Wisdom (Perception) checks that rely on sight.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all Perception checks that rely on sight.",
	},
	"Keen Smell": {
		"description": "The creature has advantage on Wisdom (Perception) checks that rely on smell.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all Perception checks that rely on smell.",
	},
	"Keen Hearing": {
		"description": "The creature has advantage on Wisdom (Perception) checks that rely on hearing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all Perception checks that rely on hearing.",
	},
	"Keen Hearing and Smell": {
		"description": "The creature has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all Perception checks that rely on hearing or smell.",
	},
	"Keen Sight and Smell": {
		"description": "The creature has advantage on Wisdom (Perception) checks that rely on sight or smell.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all Perception checks that rely on sight or smell.",
	},
	"Echolocation": {
		"description": "The creature navigates and perceives its surroundings using sound waves, granting it blindsight within a set range. This sense is entirely disabled while the creature is deafened.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants blindsight within a set range. Completely non-functional while the creature is deafened. Range is defined per-creature.",
	},
	"Tremorsense": {
		"description": "The creature can detect and pinpoint the origin of vibrations within a specific range, provided that the creature and the source of the vibrations are in contact with the same ground or substance. Tremorsense cannot detect flying or incorporeal creatures.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Detects and pinpoints creatures in contact with the same ground or substance. Cannot detect flying or incorporeal creatures. Range is defined per-creature.",
	},
	"Blind Senses": {
		"description": "The creature navigates using a combination of hearing and smell rather than sight, granting it blindsight within a set range. This sense is disabled if the creature is simultaneously deafened and unable to smell.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants blindsight that depends on both hearing and smell. Disabled only when both senses are simultaneously suppressed. Range is defined per-creature.",
	},
	"Blindsight": {
		"description": "The creature can perceive its surroundings without relying on sight within a specific radius, allowing it to detect invisible creatures and objects within that range.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Perceives and locates all creatures and objects within range without needing sight, including invisible ones. Range is defined per-creature.",
	},
	"Detect Magic": {
		"description": "The creature can sense the presence and location of magic within 30 feet of it. This functions like the detect magic spell but is always active and requires no concentration.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Passively and continuously detects the presence and location of all magic within 30 ft. Always active, requires no concentration.",
	},
	"Detect Sentience": {
		"description": "The creature can sense the presence and location of any creature within 300 feet of it that has an Intelligence score of 3 or higher, regardless of interposing barriers, unless the creature is protected by a mind blank spell.",
		"action_type": "Passive",
		"recharge": "",
		"range": "300 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Continuously detects any creature with INT 3+ within 300 ft., ignoring all physical barriers. Blocked by mind blank.",
	},
	"Detect Life": {
		"description": "The creature magically senses the presence of living creatures within 5 miles of it that aren't undead or constructs. It knows the general direction they are in but not their exact locations.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 miles",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Senses the presence and general direction of all living non-undead, non-construct creatures within 5 miles. Does not reveal exact locations.",
	},
	"Creature Sense": {
		"description": "The creature is aware of the presence of any creature within 5 miles that has an Intelligence score of 4 or higher. It knows the distance, direction, and Intelligence score of each such creature, but nothing else about it. Creatures protected by mind blank or nondetection cannot be perceived this way.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 miles",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Knows the distance, direction, and Intelligence score of every creature with INT 4+ within 5 miles. Blocked by mind blank and nondetection.",
	},
	"Telepathy": {
		"description": "The creature can magically communicate with any creature that knows at least one language within a set range. The communication is two-way and does not require a shared language. Range varies per creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature (120 ft. commonly)",
		"duration": "Permanent",
		"target": "Any creature within range that knows a language",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can communicate telepathically with any creature within range that knows at least one language. No shared language is required. Range is defined per-creature.",
	},
	"Advanced Telepathy": {
		"description": "The creature can perceive the content of any telepathic communication used within 60 feet of it. Additionally, the creature cannot be surprised by any creature that has telepathy.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Passively eavesdrops on all telepathic communication within 60 ft. Cannot be surprised by any creature possessing telepathy.",
	},
	"Limited Telepathy": {
		"description": "The creature can magically transmit simple ideas, emotions, and images telepathically to any creature within a short range that understands at least one language. It cannot receive telepathic replies.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature (30 ft. commonly)",
		"duration": "Permanent",
		"target": "Any creature within range that knows a language",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can broadcast simple concepts, emotions, and images telepathically to nearby creatures that know a language. One-way only — cannot receive replies. Range is defined per-creature.",
	},
	"Truesight": {
		"description": "The creature can see in normal and magical darkness, see invisible creatures and objects, automatically detect visual illusions and succeed on saving throws against them, perceive the original form of a shapechanger or a creature transformed by magic, and see into the Ethereal Plane, all within a set range.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Sees through magical and natural darkness, invisibility, illusions, and shapeshifting. Also sees into the Ethereal Plane. All within a set range defined per-creature.",
	},
	"Iron Scent": {
		"description": "The creature can pinpoint, by scent, the location of ferrous metal such as iron and steel within 30 feet of it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can precisely locate any ferrous metal (iron, steel) within 30 ft. by smell alone.",
	},
	"Faultless Tracker": {
		"description": "The creature is assigned a quarry by its summoner. The creature always knows the direction and distance to its quarry as long as both are on the same plane of existence. The creature also always knows the location of its summoner.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Same plane of existence",
		"duration": "Permanent",
		"target": "Assigned quarry and summoner",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Always knows the exact direction and distance to its assigned quarry and its summoner. Functions across any distance on the same plane.",
	},
	"Shark Telepathy": {
		"description": "The creature can magically command any shark within 120 feet of it using a limited form of telepathy.",
		"action_type": "Passive",
		"recharge": "",
		"range": "120 ft.",
		"duration": "Permanent",
		"target": "Any shark within range",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can telepathically issue commands to any shark within 120 ft. Sharks are compelled to obey.",
	},
	"Heart Sight": {
		"description": "The creature touches a creature and magically knows its current emotional state. If the target fails a DC 10 Charisma saving throw, the creature also learns the target's alignment. Celestials, fiends, and undead automatically fail the saving throw.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "CHA",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Instantly reads a touched creature's emotional state. On a failed CHA save, also reveals its alignment. Celestials, fiends, and undead always fail.",
	},
	"Otherworldly Perception": {
		"description": "The creature can sense the presence of any creature within 30 feet that is invisible or on the Ethereal Plane. It can pinpoint the location of such a creature if it is moving.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Detects invisible creatures and creatures on the Ethereal Plane within 30 ft. Can pinpoint their location if they are moving.",
	},
	"Divine Awareness": {
		"description": "The creature always knows when it hears a lie, detecting falsehoods instinctively through divine power.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Hearing range",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Automatically and instantly knows whenever a creature within hearing range speaks a deliberate lie.",
	},
	"Ethereal Sight": {
		"description": "The creature can see 60 feet into the Ethereal Plane when on the Material Plane, and vice versa.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can see 60 ft. into the Ethereal Plane from the Material Plane, or 60 ft. into the Material Plane from the Ethereal Plane.",
	},
	"Treasure Sense": {
		"description": "The creature can pinpoint, by scent, the location of precious metals and stones such as coins and gems within 60 feet of it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can precisely locate any precious metals and gemstones within 60 ft. by smell alone.",
	},
	"Web Sense": {
		"description": "While in contact with a web, the creature knows the exact location of any other creature in contact with the same web.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Web network",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "While touching a web, knows the exact position of every creature also touching that same web, regardless of distance.",
	},
	"Sense Magic": {
		"description": "The creature senses magic within 120 feet of it at will. This functions like the detect magic spell but is not itself magical and requires no action or concentration.",
		"action_type": "Passive",
		"recharge": "",
		"range": "120 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Continuously and passively detects magic within 120 ft. Identical to detect magic but is not itself magical and requires no action or concentration.",
	},
}
