const DATA: Dictionary = {

	"Shapechanger": {
		"description": "The creature can use its action to polymorph into a specific alternate form, or back into its true form. Its statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed. It reverts to its true form if it dies.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until changed or death",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Transforms into one specific alternate form or back into its true form. Statistics remain the same except size. Equipment does not transform. Reverts on death. Available forms are defined per-creature.",
	},
	"Shapechange": {
		"description": "The creature can use its action to polymorph into one of several specific forms or back into its true form. Unlike Shapechanger, this ability typically offers multiple form options. The creature reverts to its true form if it dies. Its statistics change based on the chosen form.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until changed or death",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Transforms between multiple specific forms. Statistics shift based on the chosen form. Reverts on death. Available forms and any retained statistics are defined per-creature.",
	},
	"Change Shape": {
		"description": "The creature magically polymorphs into any humanoid or beast with a challenge rating no higher than its own, or back into its true form. It reverts to its true form if it dies. In a new form, the creature retains its alignment, hit points, Hit Dice, speech, proficiencies, Legendary Resistance, and mental ability scores. Its physical statistics are otherwise replaced by those of the new form.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until changed or death",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Polymorphs into any humanoid or beast of equal or lower CR. Retains HP, mental stats, proficiencies, speech, and legendary abilities. Physical stats are replaced by the new form. Reverts on death.",
	},
	"Mimicry": {
		"description": "The creature can mimic sounds it has heard, including voices and other creatures. A creature that hears the sounds can identify them as imitations with a successful Wisdom (Insight) check contested by the creature's Charisma (Deception) check.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "Contested (Insight vs Deception)",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can reproduce any sound or voice it has previously heard. Listeners can detect the imitation with a successful contested Insight vs Deception check.",
	},
	"Disguise Self": {
		"description": "The creature can cast disguise self at will, requiring no material components or spell slot. The illusion changes the creature's appearance but not its underlying form. A creature can use its action to inspect the disguise and make an Intelligence (Investigation) check against a DC of 8 plus the creature's proficiency bonus and Charisma modifier to see through it.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "1 hour",
		"target": "Self",
		"saving_throw": "INT",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates an illusory change to the creature's appearance for 1 hour. Does not alter the physical form. Can be seen through with an INT (Investigation) check against the creature's spell save DC.",
	},
	"Hidden Step": {
		"description": "As a bonus action, the creature magically turns invisible until the start of its next turn or until it attacks, makes a damage roll, or forces a creature to make a saving throw. This ability recharges on a short or long rest.",
		"action_type": "Bonus Action",
		"recharge": "Short Rest",
		"range": "Self",
		"duration": "Until start of next turn or aggressive action",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Invisible"],
		"effect": "Turns invisible until the start of its next turn. Invisibility ends immediately if the creature attacks, deals damage, or forces a saving throw. Recharges on a short or long rest.",
	},
	"Superior Invisibility": {
		"description": "The creature magically turns invisible until its concentration ends, as if concentrating on a spell. Any equipment the creature wears or carries turns invisible with it. Unlike standard invisibility, this is not broken by attacking or casting spells.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Concentration",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Invisible"],
		"effect": "Becomes fully invisible along with all worn and carried equipment. Persists through attacks and spellcasting. Only ends when concentration is broken.",
	},
	"Invisibility": {
		"description": "The creature magically turns invisible until it attacks or until its concentration ends, as if concentrating on a spell. Any equipment the creature wears or carries turns invisible with it.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until attack or concentration ends",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Invisible"],
		"effect": "Becomes invisible along with all equipment. Ends immediately when the creature makes an attack or when concentration is broken.",
	},
	"Invisible Passage": {
		"description": "The creature magically turns invisible until it attacks or casts a spell, or until its concentration ends. While invisible, the creature leaves no physical evidence of its passage and can only be tracked by magic.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self",
		"duration": "Until attacks, casts a spell, or concentration ends",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Invisible"],
		"effect": "Becomes invisible and leaves no physical trace while moving. Can only be tracked by magical means. Ends on attacking, spellcasting, or broken concentration.",
	},
	"Sulfurous Impersonation": {
		"description": "As a bonus action, the creature extrudes a piece of itself that assumes the appearance of one Medium or smaller creature whose memories it has consumed. The simulacrum appears, feels, and sounds like that creature but smells faintly of sulfur. It remains connected to the creature by a thin, nearly transparent strand of slime that can be detected with a DC 10 Perception check.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self (connected by slime strand)",
		"duration": "Until dismissed or strand severed",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Extrudes a physical simulacrum of a creature whose memories were consumed. The copy looks, sounds, and feels real but smells of sulfur and is tethered by a slime strand detectable with a DC 10 Perception check.",
	},
	"Spectral Duplicate": {
		"description": "The creature creates one spectral duplicate of itself in an unoccupied space it can see within 30 feet. The duplicate has 1 hit point and uses the creature's statistics in all other ways. While the duplicate exists, the original creature is unconscious. The duplicate acts on the creature's turn and disappears after 1 minute, when it drops to 0 hit points, or when the creature ends the duplication as a bonus action.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "30 ft.",
		"duration": "1 minute or until destroyed or dismissed",
		"target": "Unoccupied space within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Original creature is Unconscious while duplicate exists"],
		"effect": "Spawns a spectral copy with 1 HP that uses the creature's full stat block. While the duplicate exists the original falls unconscious. Duplicate lasts 1 minute, until destroyed, or until dismissed as a bonus action.",
	},
}
