const DATA: Dictionary = {

	"Death Burst": {
		"description": "When the creature dies, it explodes in a burst of elemental energy. Each creature within 5 feet must make a Dexterity saving throw, taking damage on a failed save or half as much on a successful one. The damage type matches the creature's elemental nature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft. radius",
		"duration": "Instantaneous",
		"target": "All creatures within 5 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "2d6",
		"damage_type": "Varies per creature",
		"conditions_applied": [],
		"effect": "Explodes on death dealing elemental damage in a 5 ft. radius. Damage type and amount vary per creature.",
	},
	"Death Flash": {
		"description": "When the creature dies, magical darkness flashes out from it in a 10-foot radius. Each creature in the area must succeed on a Constitution saving throw or be blinded until the end of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "Until end of target's next turn",
		"target": "All creatures within 10 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Blinded"],
		"effect": "Releases a burst of magical darkness on death. Creatures in range that fail a CON save are blinded until the end of their next turn.",
	},
	"Death Throes": {
		"description": "When the creature dies, it explodes in a catastrophic burst. Each creature within 30 feet must make a Dexterity saving throw, taking 20d6 fire damage on a failed save or half on a successful one. The explosion ignites flammable objects in the area and destroys the creature's weapons.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft. radius",
		"duration": "Instantaneous",
		"target": "All creatures within 30 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "",
		"damage_dice": "20d6",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Massive fiery explosion on death dealing 20d6 fire damage in a 30 ft. radius. Ignites flammable objects and destroys the creature's own weapons.",
	},
	"Lycanthropy": {
		"description": "A humanoid bitten by this creature must succeed on a Constitution saving throw or contract lycanthropy. The afflicted creature transforms into the same lycanthrope type at the next full moon and gains its statistics.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Touch",
		"duration": "Permanent until cured",
		"target": "One humanoid bitten by the creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Lycanthropy curse"],
		"effect": "Bitten humanoids that fail a CON save contract lycanthropy and transform into the same lycanthrope type at the next full moon. Curable by remove curse before the first transformation.",
	},
	"Tidal Wave": {
		"description": "The creature conjures a massive wave of water that crashes over creatures in a line. Each creature in the path must make a Strength saving throw, taking bludgeoning damage and being knocked prone on a failed save or taking half damage and remaining standing on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "Varies per creature",
		"duration": "Instantaneous",
		"target": "All creatures in path",
		"saving_throw": "STR",
		"save_dc_stat": "CON",
		"damage_dice": "6d8",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Prone"],
		"effect": "Unleashes a massive wave dealing 6d8 bludgeoning damage and knocking creatures prone on a failed STR save. Half damage and no prone on success.",
	},
	"Web Walker": {
		"description": "The creature ignores movement restrictions caused by webbing.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Moves freely through webs and webbing with no movement penalty or restrained condition. See also: Web Walk (Movement).",
	},
	"Aberrant Quickness": {
		"description": "The creature can take one extra action on each of its turns. After using Aberrant Quickness, it must make a DC 13 Constitution saving throw at the end of its turn or become incapacitated until the end of its next turn. Recharges on a long rest.",
		"action_type": "Passive",
		"recharge": "Long Rest",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Incapacitated on failed CON save"],
		"effect": "Grants one additional action each turn. After using it, must pass a DC 13 CON save or become incapacitated until the end of its next turn.",
	},
	"Fiery Death and Rebirth": {
		"description": "When the creature dies, it explodes in a burst of fire. Each creature within 60 feet must make a Dexterity saving throw, taking 4d6 fire damage on a failed save or half on a successful one. The fire ignites flammable objects in the area. After 1 minute, the creature re-forms with all its hit points.",
		"action_type": "Passive",
		"recharge": "",
		"range": "60 ft. radius",
		"duration": "Instantaneous (1 minute to rebirth)",
		"target": "All creatures within 60 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "",
		"damage_dice": "4d6",
		"damage_type": "fire",
		"conditions_applied": [],
		"effect": "Explodes on death dealing 4d6 fire damage in a 60 ft. radius and igniting flammable objects. Re-forms with full HP after 1 minute.",
	},
	"Misty Escape": {
		"description": "When reduced to 0 hit points outside its resting place, the creature transforms into mist instead of falling unconscious, provided it isn't in running water or sunlight. In mist form it must reach its resting place within 2 hours or be permanently destroyed. Once there, it reverts and is paralyzed until it regains at least 1 hit point, which takes 1 hour of rest.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Until resting place reached or 2 hours",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Mist form at 0 HP", "Paralyzed on arrival at resting place"],
		"effect": "Transforms into mist at 0 HP instead of dying. Must reach its resting place within 2 hours or be destroyed. Arrives paralyzed and regains 1 HP after 1 hour of rest. Disabled by sunlight or running water.",
	},
	"Soul Swap": {
		"description": "The creature targets one paralyzed humanoid within 5 feet. The target must succeed on a Charisma saving throw or have its soul trapped in the creature's body while the creature's soul possesses the target's body. The creature can end the effect at any time, returning each soul to its original body.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until ended by the creature",
		"target": "One paralyzed humanoid",
		"saving_throw": "CHA",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Soul trapped in creature's body", "Target's body controlled by creature"],
		"effect": "On a failed CHA save, swaps souls with a paralyzed humanoid. The creature controls the target's body while the target is imprisoned in the creature's body. Voluntarily reversible.",
	},
	"Void Touch": {
		"description": "The creature touches one creature within 5 feet. The target must make a Constitution saving throw, taking 4d8 psychic damage on a failed save or half on a successful one. On a failed save, until the end of its next turn, whenever the target makes an attack roll or saving throw, it must use the lower of the two rolls it makes.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until end of target's next turn",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "INT",
		"damage_dice": "4d8",
		"damage_type": "psychic",
		"conditions_applied": ["Must use lower of two rolls on attacks and saves"],
		"effect": "Deals 4d8 psychic damage and forces the target to always use the worse of two rolls on attacks and saving throws until the end of its next turn. Half damage and no penalty on success.",
	},
	"Void Passage": {
		"description": "The creature targets one creature it can see within 30 feet. The target must succeed on a Wisdom saving throw or be teleported to a random unoccupied space within 30 feet of the creature that the creature can see.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Teleports a target that fails a WIS save to a random unoccupied space within 30 ft. of the creature.",
	},
	"Reality Rewrite": {
		"description": "The creature targets one creature it can see within 500 feet that has a place of comfort and safety. It creates a perfect illusion of that location within 30 feet of itself. A creature that enters the illusion must succeed on a Wisdom saving throw or be teleported into the illusory space and grappled by the creature.",
		"action_type": "Action",
		"recharge": "3/Day",
		"range": "500 ft. (detection) / 30 ft. (illusion)",
		"duration": "Until dismissed",
		"target": "One creature with a known place of comfort",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Grappled"],
		"effect": "Creates a perfect illusion of a target's safe place to lure them. Creatures entering the illusion that fail a WIS save are teleported into it and grappled.",
	},
	"Warp Space": {
		"description": "The creature magically warps the space around it. Each creature within 30 feet that can see it must make a Wisdom saving throw or become disoriented until the end of its next turn. While disoriented, the creature can't take reactions and moves in a random direction when it tries to move.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until end of target's next turn",
		"target": "All creatures within 30 ft. that can see it",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Disoriented", "Cannot take reactions", "Random movement direction"],
		"effect": "Creatures within 30 ft. that fail a WIS save lose reactions and move in random directions until the end of their next turn.",
	},
	"Labyrinthine Recall": {
		"description": "The creature can perfectly recall any path it has traveled, making it impossible for it to become lost.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Has perfect memory of every path ever traveled. Cannot become lost by any means.",
	},
	"Dual Minds": {
		"description": "The creature possesses two independent minds that work in tandem. It has advantage on saving throws against being charmed or stunned, and can maintain concentration on two spells simultaneously.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on saves against being charmed or stunned. Can concentrate on two different spells at the same time.",
	},
	"Multiple Limbs": {
		"description": "The creature possesses more limbs than a typical creature of its type, allowing it to wield additional weapons or shields simultaneously and potentially make more attacks on its turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can wield multiple weapons or shields simultaneously and may make additional attacks. Number of extra limbs and their benefits are defined per-creature.",
	},
	"Multiple Heads": {
		"description": "The creature has more than one head. While it has more than one head, it has advantage on saving throws against being blinded, charmed, deafened, frightened, stunned, and unconscious. If it loses all but one head, this advantage is lost.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on saves against blinded, charmed, deafened, frightened, stunned, and unconscious conditions while the creature has more than one head.",
	},
	"Reactive Heads": {
		"description": "For each head the creature has beyond one, it gains an extra reaction that can be used only to make opportunity attacks.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Gains one additional opportunity-attack reaction per head beyond the first. Number of bonus reactions scales with current head count.",
	},
	"Wakeful": {
		"description": "The creature can never be fully caught off guard while it sleeps. When one of the creature's heads is asleep, its other heads remain awake and aware.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "At least one head is always awake and alert. The creature cannot be surprised while sleeping.",
	},
	"Ooze Cube": {
		"description": "The creature occupies its entire space. Any other creature can enter the space, but upon doing so is immediately subjected to the creature's Engulf ability and has disadvantage on the saving throw against it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Fills its entire space. Any creature entering the space is automatically subjected to Engulf with disadvantage on the saving throw.",
	},
	"Engulf": {
		"description": "The creature moves up to its speed, passing through Large or smaller creatures' spaces. Each creature whose space it enters must make a Dexterity saving throw or be engulfed, taking 3d6 acid damage and becoming blinded and restrained with total cover against outside attacks. An engulfed creature takes 3d6 acid damage at the start of each of the creature's turns.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self (movement)",
		"duration": "Until escaped",
		"target": "All Large or smaller creatures in movement path",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "3d6",
		"damage_type": "acid",
		"conditions_applied": ["Blinded", "Restrained", "Total cover from outside attacks"],
		"effect": "Moves through creatures' spaces. Failed DEX save engulfs the target: blinded, restrained, total cover, and takes 3d6 acid damage per turn. Escape requires an action and a STR check.",
	},
	"Split": {
		"description": "When the creature takes lightning or slashing damage while Medium or larger and has at least 10 hit points, it splits into two new creatures of the same type. Each new creature has hit points equal to half the original's, rounded down, and is one size smaller.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Taking lightning or slashing damage causes the creature to split into two smaller copies, each with half the original's HP. Only triggers while Medium or larger and above 10 HP.",
	},
	"Corrode Metal": {
		"description": "Any nonmagical metal weapon that hits the creature corrodes. After dealing damage, the weapon takes a permanent cumulative -1 penalty to damage rolls. A weapon with a -5 penalty is destroyed. Nonmagical metal ammunition is destroyed on contact.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Any nonmagical metal weapon that hits it",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Weapon damage penalty: -1 per hit (cumulative, max -5 then destroyed)"],
		"effect": "Corrodes metal weapons that strike it. Each hit applies a cumulative -1 damage penalty. At -5 the weapon is destroyed. Metal ammunition is destroyed instantly on contact.",
	},
	"Corrosive Form": {
		"description": "A creature that touches or hits the creature with a melee attack while within 5 feet takes acid damage. Any nonmagical metal or wooden weapon that hits the creature corrodes, taking a cumulative -1 damage penalty per hit and being destroyed at -5. The creature can eat through 2 inches of nonmagical metal or wood in 1 round.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent",
		"target": "Any creature or weapon making contact",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "acid",
		"conditions_applied": ["Weapon damage penalty: -1 per hit (cumulative, max -5 then destroyed)"],
		"effect": "Deals acid damage on contact. Corrodes metal and wooden weapons on hit with a cumulative -1 damage penalty up to -5 before destruction. Can dissolve 2 inches of nonmagical metal or wood per round.",
	},
	"Rust Metal": {
		"description": "Any nonmagical metal weapon that hits the creature corrodes. After dealing damage, the weapon takes a permanent cumulative -1 penalty to damage rolls. A weapon with a -5 penalty is destroyed. Nonmagical metal ammunition is destroyed on contact.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Any nonmagical metal weapon that hits it",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Weapon damage penalty: -1 per hit (cumulative, max -5 then destroyed)"],
		"effect": "Rusts metal weapons on contact. Each hit applies a cumulative -1 damage penalty. At -5 the weapon is destroyed. Metal ammunition is destroyed instantly on contact.",
	},
	"Damage Transfer": {
		"description": "While the creature is attached to another creature, it takes only half the damage dealt to it, rounded down, and the attached creature takes the remaining half.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "While attached",
		"target": "Attached creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "While attached to a host, all damage dealt to this creature is split: half to itself, half transferred to the host.",
	},
	"Swallow": {
		"description": "The creature makes a bite attack against a Medium or smaller creature it is grappling. On a hit, the target is swallowed, ending the grapple. While swallowed, the target is blinded and restrained with total cover against outside attacks, and takes acid damage at the start of each of the creature's turns. The creature can regurgitate all swallowed creatures as a bonus action.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until escaped or regurgitated",
		"target": "One grappled Medium or smaller creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "6d6",
		"damage_type": "acid",
		"conditions_applied": ["Blinded", "Restrained", "Total cover from outside attacks"],
		"effect": "Bites a grappled target to swallow it. Swallowed creatures are blinded, restrained, have total cover, and take 6d6 acid damage per turn. Damage and capacity vary per creature.",
	},
	"Phasing": {
		"description": "The creature can move through solid objects and surfaces as part of its movement. It must end its turn in a clear space or take force damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "1d10",
		"damage_type": "force",
		"conditions_applied": [],
		"effect": "Can move through solid objects and surfaces. Takes 1d10 force damage if it ends its turn inside a solid object.",
	},
	"Possession": {
		"description": "The creature targets one humanoid within 5 feet. The target must succeed on a Charisma saving throw or be possessed. The creature disappears into the target's body, which it controls. The target is incapacitated and loses control of its body but remains aware. The creature retains its alignment and mental stats, uses the host's physical stats, and can't be targeted by attacks except those that affect the host body.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until ended, host succeeds on save, or host dies",
		"target": "One humanoid",
		"saving_throw": "CHA",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Host is Incapacitated", "Host loses control of body"],
		"effect": "On a failed CHA save, possesses the humanoid target. The creature disappears into the host, controls all actions, retains its mental stats, and uses the host's physical stats. Host is aware but powerless.",
	},
	"Instill Oblex": {
		"description": "As a bonus action, the creature touches a sleeping humanoid within 5 feet. The target must make a Constitution saving throw or fall into a deeper sleep for 1 hour from which they cannot be roused. If the save fails by 5 or more, the creature extracts a memory, weakening the target's personality and generating a simulacrum of the target.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "1 hour (deep sleep)",
		"target": "One sleeping humanoid",
		"saving_throw": "CON",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Deeper sleep for 1 hour", "Memory extracted on save failure by 5+"],
		"effect": "Sends a sleeping humanoid into a deeper 1-hour sleep on a failed CON save. If the save fails by 5 or more, a memory is extracted and a simulacrum of the target may be generated.",
	},
	"Oil Puddle": {
		"description": "As a bonus action, the creature creates a 5-foot square of slippery oil on a surface within 5 feet of it. The area is difficult terrain. Creatures moving into or within the area must succeed on a Dexterity saving throw or fall prone.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until cleaned",
		"target": "5 ft. square on a surface",
		"saving_throw": "DEX",
		"save_dc_stat": "DEX",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Difficult terrain", "Prone on failed DEX save"],
		"effect": "Creates a slippery 5 ft. oil patch within 5 ft. The patch is difficult terrain. Creatures moving through it must save or fall prone.",
	},
	"Slippery": {
		"description": "The creature has advantage on ability checks and saving throws made to escape a grapple.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Advantage on all checks and saving throws made to escape being grappled.",
	},
	"Speedy": {
		"description": "The creature can take the Dash action as a bonus action on each of its turns. Additionally, the creature's speed cannot be reduced by spells or other magical effects.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can Dash as a bonus action every turn. Speed is immune to magical reduction.",
	},
	"Aberrant Mutations": {
		"description": "The creature has one or more unpredictable physical mutations that grant it random combat advantages or unusual traits. The nature of its mutations shifts over time and may be rerolled between encounters.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants one or more random physical mutations providing unpredictable combat benefits. Specific mutations are defined or rolled per-creature.",
	},
	"Unpredictable Attack": {
		"description": "At the start of each of the creature's turns, roll a die to determine which attack or ability it uses. The creature has no control over which attack it makes.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Randomly determines the creature's attack or ability at the start of each turn. Attack table is defined per-creature.",
	},
	"Whirlwind": {
		"description": "Each creature in the elemental's space must make a Strength saving throw. On a failed save, a target takes 3d8+2 bludgeoning damage and is flung up to 20 feet away in a random direction and knocked prone. If the target strikes an object it takes 1d6 bludgeoning damage per 10 feet traveled. If thrown into another creature, that creature must make a DC 13 Dexterity saving throw or take the same damage and be knocked prone.",
		"action_type": "Action",
		"recharge": "4-6",
		"range": "Self (occupying space)",
		"duration": "Instantaneous",
		"target": "All creatures in the elemental's space",
		"saving_throw": "STR",
		"save_dc_stat": "CON",
		"damage_dice": "3d8+2",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Prone", "Flung up to 20 ft. in random direction"],
		"effect": "Flings creatures in its space up to 20 ft. in a random direction on a failed STR save, dealing 3d8+2 bludgeoning damage and knocking them prone. Creatures and objects struck on landing take additional impact damage.",
	},
	"Whirlwind Strike": {
		"description": "The elemental makes a melee attack against all creatures within 5 feet of it. Each creature hit takes weapon damage and must succeed on a Strength saving throw or be knocked prone.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "All creatures within 5 ft.",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "Varies per creature",
		"damage_type": "slashing",
		"conditions_applied": ["Prone on failed STR save"],
		"effect": "Attacks every creature within 5 ft. simultaneously. Creatures hit must save or be knocked prone.",
	},
	"Whirlwind of Madness": {
		"description": "The creature emits psychic energy in a 10-foot radius. Each creature in the area must make a Wisdom saving throw, taking 4d10 psychic damage on a failed save or half on a successful one. On a failed save, the creature is also confused until the end of its next turn, acting as if under the confusion spell.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "10 ft. radius",
		"duration": "Until end of target's next turn",
		"target": "All creatures within 10 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "4d10",
		"damage_type": "psychic",
		"conditions_applied": ["Confused (as confusion spell)"],
		"effect": "Deals 4d10 psychic damage in a 10 ft. radius and confuses creatures on a failed WIS save until the end of their next turn. Half damage and no confusion on success.",
	},
	"Thorn Burst": {
		"description": "When the creature dies, it explodes in a burst of thorns. Each creature within 10 feet must make a Dexterity saving throw, taking 2d10 piercing damage on a failed save or half as much on a successful one.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "Instantaneous",
		"target": "All creatures within 10 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "",
		"damage_dice": "2d10",
		"damage_type": "piercing",
		"conditions_applied": [],
		"effect": "Explodes in thorns on death, dealing 2d10 piercing damage to all creatures within 10 ft. Half damage on a successful DEX save.",
	},
	"Crystal Burst": {
		"description": "When the creature takes bludgeoning damage, it erupts in a spray of crystal shards. Each creature within 5 feet must make a Dexterity saving throw, taking piercing damage on a failed save or half as much on a successful one.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft. radius",
		"duration": "Instantaneous",
		"target": "All creatures within 5 ft.",
		"saving_throw": "DEX",
		"save_dc_stat": "",
		"damage_dice": "2d6",
		"damage_type": "piercing",
		"conditions_applied": [],
		"effect": "Triggered by taking bludgeoning damage. Sprays crystal shards in a 5 ft. radius dealing 2d6 piercing damage. Half damage on a successful DEX save.",
	},
	"Light Refraction": {
		"description": "The creature bends and refracts light through its crystalline or glass body, shedding bright light in a 10-foot radius. Any creature that starts its turn in the bright light must succeed on a Constitution saving throw or be blinded until the end of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "Permanent",
		"target": "All creatures in bright light radius",
		"saving_throw": "CON",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Blinded"],
		"effect": "Sheds bright light in a 10 ft. radius. Creatures starting their turn in that light must save or be blinded until the end of their next turn.",
	},
	"Trumpet of Blasting": {
		"description": "The creature blows its trumpet, creating a blast of sound in a 30-foot cone. Each creature in the area must make a Constitution saving throw, taking 5d6 thunder damage and becoming deafened and stunned until the end of the creature's next turn on a failed save. On a successful save, the creature takes half damage and is neither deafened nor stunned.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "30 ft. cone",
		"duration": "Until end of creature's next turn",
		"target": "All creatures in cone",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "5d6",
		"damage_type": "thunder",
		"conditions_applied": ["Deafened", "Stunned"],
		"effect": "Deals 5d6 thunder damage in a 30 ft. cone and deafens and stuns creatures on a failed CON save. Half damage and no conditions on success.",
	},
	"Healing Horn": {
		"description": "The creature touches another creature with its horn. The target magically regains 2d8+2 hit points. In addition, the touch removes all diseases and neutralizes all poisons afflicting the target.",
		"action_type": "Action",
		"recharge": "3/Day",
		"range": "Touch",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d8+2",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Heals 2d8+2 HP on touch and instantly removes all diseases and poisons from the target. Usable 3 times per day.",
	},
	"Healing Spores": {
		"description": "The creature releases a cloud of restorative spores in a 10-foot radius. Each creature of the creature's choice in that area regains hit points at the start of its next turn.",
		"action_type": "Action",
		"recharge": "Short Rest",
		"range": "10 ft. radius",
		"duration": "Until start of targets' next turn",
		"target": "Chosen creatures within 10 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "1d8",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Releases healing spores in a 10 ft. radius. Chosen creatures regain 1d8 HP at the start of their next turn.",
	},
	"Rapport Spores": {
		"description": "A 20-foot radius of spores extends from the creature. These spores affect only creatures with an Intelligence of 2 or higher that aren't undead, constructs, or elementals. Affected creatures can communicate telepathically with one another while within 30 feet of each other. The effect lasts for 1 hour.",
		"action_type": "Action",
		"recharge": "",
		"range": "20 ft. radius",
		"duration": "1 hour",
		"target": "All eligible creatures within 20 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates a 1-hour telepathic network among all affected creatures within 30 ft. of each other. Affects creatures with INT 2+ that aren't undead, constructs, or elementals.",
	},
	"Distress Spores": {
		"description": "When the creature takes damage, all other creatures of the same type within 240 feet of it can sense its pain and distress through a shared spore network.",
		"action_type": "Passive",
		"recharge": "",
		"range": "240 ft.",
		"duration": "Instantaneous",
		"target": "All allied creatures within 240 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Automatically alerts all allied creatures within 240 ft. whenever this creature takes damage, allowing a coordinated response.",
	},
	"Pacifying Spores": {
		"description": "The creature ejects spores at one creature it can see within 5 feet. The target must succeed on a Constitution saving throw or be stunned for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Stunned"],
		"effect": "Stuns one target within 5 ft. on a failed CON save for up to 1 minute. Target may re-save at the end of each of its turns.",
	},
	"Hallucination Spores": {
		"description": "The creature ejects spores at one creature it can see within 5 feet. The target must succeed on a Constitution saving throw or be poisoned for 1 minute. While poisoned this way, the target is incapacitated and sees vivid hallucinations. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned", "Incapacitated"],
		"effect": "On a failed CON save, target is Poisoned and Incapacitated by hallucinations for up to 1 minute. Target may re-save each turn.",
	},
	"Poison Spores": {
		"description": "The creature releases a cloud of poisonous spores in a 10-foot radius. Each creature in the area must succeed on a Constitution saving throw or take poison damage and become poisoned for 1 minute.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft. radius",
		"duration": "1 minute",
		"target": "All creatures within 10 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "2d6",
		"damage_type": "poison",
		"conditions_applied": ["Poisoned"],
		"effect": "Releases poisonous spores in a 10 ft. radius. Creatures that fail a CON save take 2d6 poison damage and become Poisoned for 1 minute.",
	},
	"Mucous Cloud": {
		"description": "While underwater, the creature is surrounded by transformative mucus. A creature that touches or hits it with a melee attack within 5 feet must make a Constitution saving throw or become diseased for 1d4 hours. While diseased this way, the creature can breathe only underwater.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "1d4 hours",
		"target": "Any creature touching it or hitting it in melee",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Diseased: can only breathe underwater"],
		"effect": "Active only underwater. Melee attackers within 5 ft. must save or contract a disease for 1d4 hours that allows breathing only underwater.",
	},
	"Probing Telepathy": {
		"description": "If a creature communicates telepathically with the creature, it learns that creature's greatest desires if it succeeds on a Wisdom check. The probed creature is unaware that its desires have been read.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Telepathic contact",
		"duration": "Instantaneous",
		"target": "Any creature communicating telepathically with it",
		"saving_throw": "WIS",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Whenever any creature initiates telepathic contact, the creature makes a WIS check to learn that creature's deepest desires. The target is unaware.",
	},
	"Rebirth": {
		"description": "When the creature is destroyed, its essence persists and it is reborn in a new body after a set period of time, typically at a location of significance to it. The creature returns with all its hit points and memories.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "On death, the creature's essence survives and manifests a new body after a set period. Returns with full HP and all memories. Conditions for permanent death vary per creature.",
	},
	"Regrowth": {
		"description": "If the creature is killed, a new specimen grows from its remains within 24 hours, provided the remains are not destroyed. The new creature is identical to the original.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "24 hours",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "A new copy grows from the creature's remains within 24 hours after death. Prevented only by destroying the remains entirely before regrowth completes.",
	},
	"Iron Token": {
		"description": "The creature can magically create a small bent iron nail. A creature carrying the token cannot attune to magic items. As an action, a carrier can touch a target, forcing a Charisma saving throw or causing the token to magically teleport to within 5 feet of that target, applying its effect to the new carrier.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "Touch",
		"duration": "Until destroyed",
		"target": "One creature",
		"saving_throw": "CHA",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Cannot attune to magic items while carrying token"],
		"effect": "Creates a small iron token that blocks attunement for its carrier. Can be transferred to an unwilling target with a touch and a failed CHA save.",
	},
	"Iron Boots": {
		"description": "While wearing its iron boots, the creature has advantage on Strength checks and Strength saving throws. In addition, its stomp attack deals an extra 2d8 bludgeoning damage.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d8",
		"damage_type": "bludgeoning",
		"conditions_applied": [],
		"effect": "Grants advantage on all STR checks and saves. Stomp attack deals an additional 2d8 bludgeoning damage.",
	},
	"Earth Shaker": {
		"description": "The creature stomps or strikes the ground, creating a shockwave. Each creature within 30 feet that is in contact with the ground must succeed on a Strength saving throw or be knocked prone.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "All grounded creatures within 30 ft.",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Prone"],
		"effect": "Creates a ground shockwave that knocks prone any grounded creature within 30 ft. that fails a STR save. Does not affect flying or hovering creatures.",
	},
	"Watery Strikes": {
		"description": "The creature's weapon attacks deal an extra die of cold damage on a hit.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "+1 weapon damage die",
		"damage_type": "cold",
		"conditions_applied": [],
		"effect": "All weapon attacks deal one additional die of cold damage.",
	},
	"Elemental Demise": {
		"description": "If the creature dies, its body disintegrates into its native element, leaving behind any objects it was carrying. Its essence returns to its home plane and the creature cannot take physical form for a period of time before it can potentially manifest again.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "On death, the body dissolves into its native element and the essence returns to its home plane. Cannot manifest physically for a set time. Carried objects are left behind.",
	},
	"Scaladar Link": {
		"description": "The creature is immune to lightning damage dealt by other creatures of its own kind. Whenever this creature deals lightning damage, all other creatures of the same kind within 100 feet sense the discharge.",
		"action_type": "Passive",
		"recharge": "",
		"range": "100 ft.",
		"duration": "Permanent",
		"target": "Self and allied creatures within 100 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to lightning from its own kind. When it deals lightning damage, all allied creatures within 100 ft. detect the discharge as a shared sense.",
	},
	"Hive Mind": {
		"description": "The creature is immune to the frightened and charmed conditions. While at least two creatures of this kind are within 300 feet of each other, they share a collective consciousness and can communicate instantaneously.",
		"action_type": "Passive",
		"recharge": "",
		"range": "300 ft.",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Immune to frightened and charmed. Shares a collective mind with all allied creatures within 300 ft., enabling instant communication and coordination.",
	},
	"Disintegration": {
		"description": "If the creature dies, it disintegrates into dust instantly, leaving only its possessions behind.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Body immediately turns to dust on death. No corpse remains. Only carried possessions are left behind.",
	},
	"Disintegrating Beam": {
		"description": "The creature fires a disintegrating beam at one creature it can see within 60 feet. The target must make a Dexterity saving throw, taking 10d8 force damage on a failed save or half as much on a successful one. If this damage reduces the target to 0 hit points, the target is disintegrated.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "60 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "DEX",
		"save_dc_stat": "CON",
		"damage_dice": "10d8",
		"damage_type": "force",
		"conditions_applied": ["Disintegrated if reduced to 0 HP"],
		"effect": "Deals 10d8 force damage on a failed DEX save. Targets reduced to 0 HP are completely disintegrated, leaving nothing behind. Half damage on success.",
	},
	"Tentacle Whip": {
		"description": "The creature lashes out with a powerful tentacle, making a melee attack. On a hit, the target is grappled and the creature can use the tentacle to pull the target toward it or restrain it.",
		"action_type": "Action",
		"recharge": "",
		"range": "15 ft.",
		"duration": "Until escaped",
		"target": "One creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "Varies per creature",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Grappled"],
		"effect": "Melee tentacle attack that grapples the target on a hit. The creature can drag or restrain the grappled target. Escape DC varies per creature.",
	},
	"Heartstone": {
		"description": "The creature possesses a lustrous black gemstone that allows it to become ethereal while on the Material Plane, and vice versa. The heartstone can also cure any disease on touch. Creating a new heartstone takes 30 days.",
		"action_type": "Action",
		"recharge": "",
		"range": "Self or Touch",
		"duration": "Instantaneous (plane shift) or Permanent (disease cure)",
		"target": "Self or one creature",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Grants the ability to shift between the Material and Ethereal planes at will. Can also cure any disease on touch. If destroyed, takes 30 days to create a new one.",
	},
	"Telepathic Bond": {
		"description": "The creature shares a permanent telepathic bond with its owner. While on the same plane of existence, both can communicate telepathically at any distance. The owner can see through the creature's eyes and hear through its ears as a bonus action, lasting until the owner uses a bonus action to return to their own senses.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Same plane of existence",
		"duration": "Permanent",
		"target": "Bonded owner",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Permanent two-way telepathic link with a bonded owner across any distance on the same plane. Owner can use a bonus action to share the creature's senses.",
	},
	"Dragon Bond": {
		"description": "The creature is magically bonded to a specific dragon. The bonded dragon can see and hear through the creature's senses at will. The creature acts as a remote sensory conduit for the dragon.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Unlimited (same plane)",
		"duration": "Permanent",
		"target": "Bonded dragon",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "The bonded dragon can see and hear through this creature's senses at any time, at any distance on the same plane.",
	},
	"Soothing Mist": {
		"description": "The creature exhales a calming mist in a 15-foot cone. Each creature in the area must make a Wisdom saving throw or be calmed for 1 round and unable to make attacks until the start of its next turn.",
		"action_type": "Action",
		"recharge": "",
		"range": "15 ft. cone",
		"duration": "Until start of target's next turn",
		"target": "All creatures in cone",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Cannot attack until start of next turn"],
		"effect": "Creatures in the cone that fail a WIS save are pacified and cannot attack until the start of their next turn.",
	},
	"Lightning Strike": {
		"description": "The creature hurls a magical lightning bolt at a point it can see within 500 feet. Each creature within 10 feet of that point must make a Dexterity saving throw, taking 12d8 lightning damage on a failed save or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "500 ft.",
		"duration": "Instantaneous",
		"target": "All creatures within 10 ft. of target point",
		"saving_throw": "DEX",
		"save_dc_stat": "STR",
		"damage_dice": "12d8",
		"damage_type": "lightning",
		"conditions_applied": [],
		"effect": "Calls a massive lightning strike at a visible point within 500 ft. Deals 12d8 lightning damage in a 10 ft. radius. Half damage on a successful DEX save.",
	},
	"Lightning Touch": {
		"description": "The creature touches one creature within 5 feet. The target must make a Dexterity saving throw, taking 6d8 lightning damage on a failed save or half as much on a successful one.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "DEX",
		"save_dc_stat": "STR",
		"damage_dice": "6d8",
		"damage_type": "lightning",
		"conditions_applied": [],
		"effect": "Deals 6d8 lightning damage to one creature on touch. Half damage on a successful DEX save.",
	},
	"Speak with Frogs": {
		"description": "The creature can communicate simple concepts and commands to frogs and toads using its native language.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Hearing range",
		"duration": "Permanent",
		"target": "Any frog or toad",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can convey simple concepts and commands to frogs and toads. Frogs and toads understand but cannot hold complex conversations.",
	},
	"Speak with Beasts and Plants": {
		"description": "The creature can communicate with beasts and plants as if they shared a common language. Beasts and plants can understand it and respond in kind, though their responses are limited by their intelligence.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Hearing range",
		"duration": "Permanent",
		"target": "Any beast or plant",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can hold two-way communication with any beast or plant. Responses are limited by the intelligence and awareness of the beast or plant.",
	},
	"Inescapable Stride": {
		"description": "The creature can move through the space of any creature that is frightened of it.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Self",
		"duration": "Permanent",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Can freely move through the occupied space of any creature that has the frightened condition and is frightened of this creature.",
	},
	"Pacify": {
		"description": "The creature targets one creature it can see within 30 feet. The target must succeed on a Wisdom saving throw or become frightened until the end of its next turn. While frightened this way, the target's speed is 0 and it cannot benefit from any bonus to its speed.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until end of target's next turn",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened", "Speed reduced to 0"],
		"effect": "Frightens one target on a failed WIS save until the end of its next turn. The frightened target's speed drops to 0 and cannot be increased by any means.",
	},
	"Unhappy Ending": {
		"description": "The creature targets one frightened creature it can see within 30 feet. The target must succeed on a Charisma saving throw or take 2d10 psychic damage and fall unconscious for 1 hour. An unconscious creature awakens if it takes damage or if another creature uses its action to rouse it.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "1 hour",
		"target": "One frightened creature",
		"saving_throw": "CHA",
		"save_dc_stat": "CHA",
		"damage_dice": "2d10",
		"damage_type": "psychic",
		"conditions_applied": ["Unconscious for 1 hour"],
		"effect": "Deals 2d10 psychic damage and knocks a frightened target unconscious for 1 hour on a failed CHA save. The unconscious creature wakes if it takes damage or is roused by another creature's action.",
	},
	"Aura of Menace": {
		"description": "A magical aura of menace radiates from the creature in a 20-foot radius. Any hostile creature in the aura that isn't immune to the frightened condition must succeed on a Wisdom saving throw at the start of its turn or become frightened until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "20 ft. radius",
		"duration": "Permanent",
		"target": "All hostile creatures within 20 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Hostile creatures starting their turn within 20 ft. must save or be Frightened until the start of their next turn. Creatures immune to frightened are unaffected.",
	},
}
