const DATA: Dictionary = {

	"Spellcasting": {
		"description": "The creature is a spellcaster. It has a set number of spell slots and uses a chosen spellcasting ability to cast spells from a class spell list. The creature's spell save DC, spell attack bonus, and available spells are defined per-creature.",
		"action_type": "Varies per spell",
		"recharge": "",
		"range": "Varies per spell",
		"duration": "Varies per spell",
		"target": "Varies per spell",
		"saving_throw": "Varies per spell",
		"save_dc_stat": "Varies per creature",
		"damage_dice": "Varies per spell",
		"damage_type": "Varies per spell",
		"conditions_applied": [],
		"effect": "Casts spells using class spell slots. Spellcasting ability, spell save DC, spell attack modifier, and available spells are all defined per-creature.",
	},
	"Innate Spellcasting": {
		"description": "The creature's spellcasting is innate and doesn't require spell slots or material components (unless noted otherwise). The creature uses a chosen ability as its spellcasting ability. The available spells and their frequency are defined per-creature.",
		"action_type": "Varies per spell",
		"recharge": "",
		"range": "Varies per spell",
		"duration": "Varies per spell",
		"target": "Varies per spell",
		"saving_throw": "Varies per spell",
		"save_dc_stat": "Varies per creature",
		"damage_dice": "Varies per spell",
		"damage_type": "Varies per spell",
		"conditions_applied": [],
		"effect": "Casts a fixed list of spells without spell slots or material components. Available spells, their use frequency (at will, 3/day, 1/day, etc.), and the spellcasting ability are defined per-creature.",
	},
	"Psionics": {
		"description": "The creature's spellcasting is psionic in nature. It doesn't require components of any kind. The creature uses Intelligence as its spellcasting ability (spell save DC X, +Y to hit with spell attacks). The available psionic spells and their frequency are defined per-creature.",
		"action_type": "Varies per spell",
		"recharge": "",
		"range": "Varies per spell",
		"duration": "Varies per spell",
		"target": "Varies per spell",
		"saving_throw": "Varies per spell",
		"save_dc_stat": "INT",
		"damage_dice": "Varies per spell",
		"damage_type": "Varies per spell",
		"conditions_applied": [],
		"effect": "Casts spells psionically with no components of any kind. Always uses Intelligence as spellcasting ability. Available spells and use frequency are defined per-creature.",
	},
	"Psionic Powers": {
		"description": "The creature possesses a suite of psionic powers that function similarly to spells but require no components of any kind. It uses Intelligence as its spellcasting ability. The available powers and their recharge rates are defined per-creature.",
		"action_type": "Varies per power",
		"recharge": "",
		"range": "Varies per power",
		"duration": "Varies per power",
		"target": "Varies per power",
		"saving_throw": "Varies per power",
		"save_dc_stat": "INT",
		"damage_dice": "Varies per power",
		"damage_type": "Varies per power",
		"conditions_applied": [],
		"effect": "Exercises a suite of psionic abilities that function as spells requiring no components. Always Intelligence-based. Available powers and their recharge rates are defined per-creature.",
	},
	"Spell Storing": {
		"description": "The creature can store one spell of up to 3rd level placed inside it by a spellcaster. While a spell is stored, the creature can cast it as a bonus action at will, using the original caster's spell save DC and attack modifier. The creature loses the stored spell when it uses it or when it finishes a long rest.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "Varies per stored spell",
		"duration": "Varies per stored spell",
		"target": "Varies per stored spell",
		"saving_throw": "Varies per stored spell",
		"save_dc_stat": "Varies per stored spell",
		"damage_dice": "Varies per stored spell",
		"damage_type": "Varies per stored spell",
		"conditions_applied": [],
		"effect": "Stores one spell (up to 3rd level) placed into it by its creator. Releases the stored spell as a bonus action using the original caster's spell save DC and attack bonus. Stored spell is lost after use or after a long rest.",
	},
	"Reflect Spell": {
		"description": "When the creature is targeted by a spell that requires an attack roll or allows a saving throw, it can use its reaction to reflect the spell back at the caster. The reflected spell uses the original caster's attack roll or the creature's spell save DC and uses the original caster as the new target.",
		"action_type": "Reaction",
		"recharge": "1/Day",
		"range": "Self",
		"duration": "Instantaneous",
		"target": "The creature that cast the triggering spell",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "When targeted by a qualifying spell, uses a reaction to redirect it back at the original caster. The reflected spell uses the creature's spell save DC. Usable once per day.",
	},
	"Spell Redirect": {
		"description": "When the creature is targeted by a spell that requires an attack roll or allows a saving throw, it can use its reaction to redirect that spell to a new target of its choice within the spell's original range. The spell uses the original caster's attack roll or save DC against the new target.",
		"action_type": "Reaction",
		"recharge": "",
		"range": "Varies per redirected spell",
		"duration": "Instantaneous",
		"target": "A new target within the original spell's range",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "When targeted by a qualifying spell, uses a reaction to redirect it to a new target within the spell's range. The redirected spell uses the original caster's attack roll or spell save DC against the new target.",
	},
	"Graystaff Magic": {
		"description": "The creature wields a graystaff, a magical crystalline staff that serves as its spellcasting focus and channels powerful illusory and telepathic magic. The creature can use the staff to cast a set of spells innately, requiring no material components. The specific spells available and their frequency are defined per-creature.",
		"action_type": "Varies per spell",
		"recharge": "",
		"range": "Varies per spell",
		"duration": "Varies per spell",
		"target": "Varies per spell",
		"saving_throw": "Varies per spell",
		"save_dc_stat": "INT",
		"damage_dice": "Varies per spell",
		"damage_type": "Varies per spell",
		"conditions_applied": [],
		"effect": "Channels innate spellcasting through a magical graystaff. Spells are typically illusion- or telepathy-based and require no material components. Available spells and frequencies are defined per-creature.",
	},
	"Psionic Hub": {
		"description": "The creature acts as the central node of a psionic network, extending and amplifying psionic abilities and communication among allied creatures within range. All creatures linked to the hub can communicate and share sensory information through it. Range and the number of linked creatures are defined per-creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "All linked psionic creatures within range",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Serves as the central node of a psionic network, relaying communication and amplifying psionic effects between all linked creatures within range. Range and the pool of linked creatures are defined per-creature.",
	},
	"Telepathic Hub": {
		"description": "The creature acts as a relay point for telepathic communication, allowing all allied creatures within range to communicate with each other through the hub at any distance within the hub's range. The hub creature is aware of all communications passing through it. Range and linked creature types are defined per-creature.",
		"action_type": "Passive",
		"recharge": "",
		"range": "Varies per creature",
		"duration": "Permanent",
		"target": "All allied creatures within range",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Relays telepathic communication between all allied creatures within range, allowing them to speak to one another through the hub regardless of individual telepathy ranges. Hub creature is aware of all relayed messages. Range is defined per-creature.",
	},
	"Scrying": {
		"description": "The creature can magically observe a creature or location on the same plane of existence. The creature must succeed on its scrying check against the target's resistance. While scrying, an invisible sensor appears within 10 feet of the target, which can see and hear the target and anything within 30 feet of it.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "Same plane of existence",
		"duration": "Concentration, up to 10 minutes",
		"target": "One creature or location known to the creature",
		"saving_throw": "WIS",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates an invisible sensor near a known target on the same plane, allowing the creature to see and hear through it for up to 10 minutes. Target creatures must succeed on a WIS save or be observed. Familiarity with the target affects save difficulty.",
	},
	"Clairvoyance": {
		"description": "The creature magically creates an invisible sensor at a location it is familiar with within a set range. Through the sensor it can see and hear as if it were physically present there for up to 10 minutes. It cannot target creatures with this ability, only locations.",
		"action_type": "Action",
		"recharge": "3/Day",
		"range": "1 mile",
		"duration": "Concentration, up to 10 minutes",
		"target": "A known or previously visited location within 1 mile",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Creates an invisible magical sensor at a known location within 1 mile. The creature can see and hear through the sensor for up to 10 minutes. Targets locations only, not specific creatures.",
	},
}
