const DATA: Dictionary = {

	"Paralyzing Tentacles": {
		"description": "The creature lashes out with venom-coated tentacles. On a hit, the target must succeed on a Constitution saving throw or become paralyzed by the injected venom. The paralysis lasts up to 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "2d6+4",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Paralyzed"],
		"effect": "Melee tentacle attack that deals bludgeoning damage and injects venom. On a hit, target must succeed on a CON save or be paralyzed for up to 1 minute. Target re-saves at end of each turn.",
	},
	"Paralyzing Touch": {
		"description": "The creature's touch carries paralytic energy. The target must succeed on a Constitution saving throw or become paralyzed for up to 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success. This ability is common to undead and aberrations.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Paralyzed"],
		"effect": "Touch attack that carries no physical damage but forces a CON save. On failure, target is paralyzed for up to 1 minute. Target re-saves at end of each turn.",
	},
	"Paralyzing Needles": {
		"description": "The creature fires or injects paralyzing needles into a target. On a hit, the target must succeed on a Constitution saving throw or become paralyzed by the injected venom for up to 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "1d6",
		"damage_type": "piercing",
		"conditions_applied": ["Paralyzed"],
		"effect": "Attack that deals piercing damage and injects paralyzing venom. On a hit, target must succeed on a CON save or be paralyzed for up to 1 minute. Target re-saves at end of each turn.",
	},
	"Paralyzing Field": {
		"description": "The creature emits a field of paralytic energy in a radius around itself. All creatures in the area must succeed on a Constitution saving throw or become paralyzed for up to 1 minute. Affected creatures can repeat the saving throw at the end of each of their turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "15 ft. radius (self-centered)",
		"duration": "1 minute",
		"target": "All creatures within 15 ft.",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Paralyzed"],
		"effect": "Emits a paralysis field in a 15 ft. radius. All creatures in the area must succeed on a CON save or be paralyzed for up to 1 minute. Creatures re-save at end of each turn.",
	},
	"Petrifying Gaze": {
		"description": "When a creature that can see this creature's eyes starts its turn within 30 feet of it, it must make a Constitution saving throw. On a failed save it is restrained as its flesh begins to harden. A restrained creature must repeat the save at the start of its next turn. On a second failure the creature is permanently petrified. On a success the restrained condition ends.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Permanent until cured",
		"target": "All creatures within 30 ft. that can see the creature's eyes",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained (first failed save)", "Petrified (second failed save)"],
		"effect": "Creatures starting their turn within 30 ft. while seeing the creature's eyes must make a CON save. One failure = restrained; a second consecutive failure = permanently petrified. A successful save while restrained ends the effect.",
	},
	"Petrifying Bite": {
		"description": "The creature's bite injects a petrifying agent into the target. On a hit, the target must succeed on a Constitution saving throw or begin turning to stone. A restrained creature must repeat the save at the end of its next turn. On a second failure the creature is permanently petrified. Some variants allow a time-delayed petrification that can be cured within 24 hours.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent until cured",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "1d4+2",
		"damage_type": "piercing",
		"conditions_applied": ["Restrained (first failed save)", "Petrified (second failed save)"],
		"effect": "Melee bite attack that injects a petrifying agent. On a hit, target must make a CON save. First failure = restrained; second consecutive failure = permanently petrified. A successful save while restrained ends the effect.",
	},
	"Petrifying Touch": {
		"description": "The creature's touch begins the petrification process in its target. The target must succeed on a Constitution saving throw or be restrained as its flesh hardens. A restrained creature must repeat the save at the start of its next turn. On a second failure the target is permanently petrified. A successful save while restrained ends the effect.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "Permanent until cured",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained (first failed save)", "Petrified (second failed save)"],
		"effect": "Touch attack that begins a two-stage petrification. First failed CON save = restrained; second consecutive failure = permanently petrified. Successful save while restrained ends the effect.",
	},
	"Horrific Appearance": {
		"description": "Any humanoid that starts its turn within 30 feet of this creature and can see its true form must make a Wisdom saving throw. On a failed save, the creature is frightened for 1 minute. A frightened creature can repeat the saving throw at the end of each of its turns, ending the effect on a success. If a creature's saving throw is successful or the effect ends for it, the creature is immune to this ability for the next 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "1 minute",
		"target": "All humanoids within 30 ft. that can see the creature's true form",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Humanoids within 30 ft. that see the creature's true form must succeed on a WIS save or be frightened for 1 minute. Creatures that successfully save are immune for 24 hours. Frightened creatures re-save at end of each turn.",
	},
	"Horrifying Visage": {
		"description": "Each non-undead creature within 60 feet that can see this creature must succeed on a Wisdom saving throw or be frightened for 1 minute. A frightened creature can repeat the saving throw at the end of each of its turns, with disadvantage if the creature is within line of sight, ending the effect on a success. If a target's saving throw is successful or the effect ends for it, the target is immune to this ability for the next 24 hours.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "1 minute",
		"target": "All non-undead creatures within 60 ft. that can see the creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "All non-undead creatures within 60 ft. that can see the creature must succeed on a WIS save or be frightened for 1 minute. Re-saves have disadvantage while the creature is in line of sight. Successful savers are immune for 24 hours.",
	},
	"Death Gaze": {
		"description": "When a creature that can see this creature's eyes starts its turn within 30 feet of it, the creature can force it to make a Constitution saving throw. On a failed save, the target's hit point maximum is reduced and it takes psychic damage. If the saving throw fails by 5 or more, the creature drops to 0 hit points instead. A creature that succeeds is immune for 24 hours.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Instantaneous",
		"target": "One creature within 30 ft. that can see the creature's eyes",
		"saving_throw": "CON",
		"save_dc_stat": "WIS",
		"damage_dice": "3d10",
		"damage_type": "psychic",
		"conditions_applied": ["Instant death (if failed by 5 or more)"],
		"effect": "Creatures starting their turn within 30 ft. while seeing the creature's eyes must make a CON save or take 3d10 psychic damage. Failing by 5 or more drops the target to 0 HP. Successful savers are immune for 24 hours.",
	},
	"Death Ray": {
		"description": "The creature fires a ray of necromantic energy at one target it can see within 150 feet. The target must succeed on a Dexterity saving throw or take necrotic damage. If this damage reduces the target to 0 hit points, it dies.",
		"action_type": "Action",
		"recharge": "",
		"range": "150 ft.",
		"duration": "Instantaneous",
		"target": "One creature",
		"saving_throw": "DEX",
		"save_dc_stat": "INT",
		"damage_dice": "10d10",
		"damage_type": "necrotic",
		"conditions_applied": ["Death (if reduced to 0 HP)"],
		"effect": "Fires a death ray at one target. On a failed DEX save, target takes 10d10 necrotic damage. If this damage reduces the target to 0 HP, it dies instantly.",
	},
	"Chilling Gaze": {
		"description": "The creature fixes its supernaturally cold gaze on one creature within 30 feet it can see. The target must succeed on a Constitution saving throw or take cold damage and be paralyzed until the end of its next turn as lethal cold seizes its muscles.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until end of target's next turn",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "2d6",
		"damage_type": "cold",
		"conditions_applied": ["Paralyzed"],
		"effect": "On a failed CON save, target takes 2d6 cold damage and is paralyzed until the end of its next turn.",
	},
	"Stunning Gaze": {
		"description": "The creature fixes its unnerving gaze on one creature within 30 feet it can see. The target must succeed on a Wisdom saving throw or be stunned until the end of its next turn.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until end of target's next turn",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Stunned"],
		"effect": "One creature within 30 ft. must succeed on a WIS save or be stunned until the end of its next turn.",
	},
	"Weakening Gaze": {
		"description": "The creature turns its withering gaze on one creature within 30 feet it can see. The target must succeed on a Constitution saving throw or have its Strength score reduced by 1d4+2 for 1 minute. If the target's Strength is reduced to 0, the target falls unconscious. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Strength reduced by 1d4+2", "Unconscious (if Strength drops to 0)"],
		"effect": "On a failed CON save, target's Strength is reduced by 1d4+2 for 1 minute. Target falls unconscious if Strength drops to 0. Target re-saves at end of each turn.",
	},
	"Hypnotic Gaze": {
		"description": "The creature's eyes shimmer with hypnotic power. One creature the creature can see within 5 feet of it must succeed on a Wisdom saving throw or be magically charmed and stunned until the end of the creature's next turn.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until end of creature's next turn",
		"target": "One creature within 5 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed", "Stunned"],
		"effect": "One creature within 5 ft. must succeed on a WIS save or be magically charmed and stunned until the end of the creature's next turn. A creature that succeeds is immune to this ability for 24 hours.",
	},
	"Hypnosis": {
		"description": "The creature attempts to hypnotize one creature it can see within 30 feet. The target must succeed on a Wisdom saving throw or be charmed by the creature for 1 hour. While charmed, the creature obeys simple verbal commands from the hypnotist unless the command would harm it. The charmed creature repeats the saving throw if it takes damage.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "1 hour",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "One creature must succeed on a WIS save or be charmed for 1 hour, compelled to follow simple verbal commands that don't harm it. The effect immediately ends if the charmed creature takes damage.",
	},
	"Hypnotic Touch": {
		"description": "The creature touches one humanoid, magically hypnotizing it. The target must succeed on a Wisdom saving throw or be charmed by the creature for 1 hour. While charmed, the target regards the creature as a trusted friend and ally and will heed its suggestions. The target repeats the saving throw if it takes damage or the creature commands it to act against its nature.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "1 hour",
		"target": "One humanoid",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "Touch attack. Target must succeed on a WIS save or be charmed for 1 hour, treating the creature as a trusted friend and following its suggestions. The effect ends if the target takes damage.",
	},
	"Intoxicating Touch": {
		"description": "The creature's touch carries an intoxicating magical substance that simultaneously poisons and charms its target. The target must succeed on a Constitution saving throw or become poisoned and charmed for 1 minute. While poisoned and charmed, the target is inclined to comply with the creature's requests. The target can repeat the saving throw at the end of each of its turns, ending both conditions on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "1 minute",
		"target": "One humanoid",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Poisoned", "Charmed"],
		"effect": "Touch attack. On a failed CON save, target is both poisoned and charmed for 1 minute, inclined to obey the creature's requests. Target re-saves at end of each turn.",
	},
	"Charm": {
		"description": "The creature targets one humanoid it can see within 30 feet of it. If the target can see the creature, the target must succeed on a Wisdom saving throw or be magically charmed for 1 day. The charmed target obeys the creature's spoken commands. Whenever the target takes damage, it can repeat the saving throw, ending the effect on itself on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "1 day",
		"target": "One humanoid",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed"],
		"effect": "One humanoid must succeed on a WIS save or be charmed for 1 day, obeying the creature's spoken commands. Target re-saves when it takes damage.",
	},
	"Draining Kiss": {
		"description": "The creature kisses a creature charmed by it or a willing creature. The target must make a Constitution saving throw against this magic. On a failed save, the target takes psychic damage and the maximum of this damage is subtracted from the target's hit point maximum. The reduction lasts until removed by greater restoration or similar magic. The target dies if its hit point maximum is reduced to 0.",
		"action_type": "Action",
		"recharge": "",
		"range": "Touch",
		"duration": "Until magically cured",
		"target": "One willing or charmed creature",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "5d10+5",
		"damage_type": "psychic",
		"conditions_applied": ["HP maximum reduced by damage dealt"],
		"effect": "Deals 5d10+5 psychic damage on a failed CON save (half on success). The target's HP maximum is reduced by the full damage dealt. The reduction lasts until cured by greater restoration. Target dies if HP max reaches 0.",
	},
	"Moan": {
		"description": "The creature emits a low, haunting moan that fills nearby creatures with dread. Each creature within 30 feet that can hear the moan and isn't an undead must succeed on a Wisdom saving throw or be frightened until the end of its next turn.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until end of target's next turn",
		"target": "All non-undead creatures within 30 ft. that can hear",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "Non-undead creatures within 30 ft. that hear the moan must succeed on a WIS save or be frightened until the end of their next turn. Undead are immune.",
	},
	"Wail": {
		"description": "The creature lets out a mournful wail, provided it isn't in sunlight. This wail has no effect on constructs and undead. All other creatures within 60 feet that can hear it must succeed on a Constitution saving throw. On a failed save, a creature drops to 0 hit points. On a successful save, a creature takes 3d6 psychic damage.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "60 ft.",
		"duration": "Instantaneous",
		"target": "All non-construct, non-undead creatures within 60 ft. that can hear",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "3d6",
		"damage_type": "psychic",
		"conditions_applied": ["Dropped to 0 HP (on failed save)"],
		"effect": "All non-undead, non-construct creatures within 60 ft. that can hear must make a CON save. Failure drops the creature to 0 HP. Success deals 3d6 psychic damage.",
	},
	"Shriek": {
		"description": "When triggered by bright light or another stimulus (such as movement within a set range), the creature emits a piercing shriek that is audible within 300 feet for 1 minute or until it is no longer stimulated. The shriek alerts other creatures of the same type within range and can trigger a hostile response. The specific triggering conditions are defined per-creature.",
		"action_type": "Reaction",
		"recharge": "",
		"range": "300 ft. (audible range)",
		"duration": "1 minute (while stimulus persists)",
		"target": "Self",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Triggered by a specific stimulus (light, movement, etc.). Emits a continuous piercing shriek for 1 minute, audible within 300 ft., alerting all creatures of the same type and drawing hostile attention.",
	},
	"Drone": {
		"description": "The creature emits a continuous droning sound while it can see any creature and isn't incapacitated. Each creature that starts its turn within 30 feet of the creature and can hear the drone must succeed on a Wisdom saving throw or be incapacitated until the start of its next turn.",
		"action_type": "Passive",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Until start of target's next turn",
		"target": "All creatures within 30 ft. that can hear",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Incapacitated"],
		"effect": "Continuously drones while able to see creatures. Creatures starting their turn within 30 ft. while hearing the drone must succeed on a WIS save or be incapacitated until the start of their next turn.",
	},
	"Luring Song": {
		"description": "The creature sings a magical melody. Every humanoid and giant within 300 feet that can hear the song must succeed on a Wisdom saving throw or be charmed until the song ends. The creature must take a bonus action on its subsequent turns to continue singing. While charmed by this ability, a creature is incapacitated and ignores the songs of other such creatures. On each of its turns, a charmed creature must move toward the singer by the most direct route available. The charmed target can repeat the saving throw at the end of each of its turns if it is more than 5 feet from the creature.",
		"action_type": "Action",
		"recharge": "",
		"range": "300 ft.",
		"duration": "Concentration (sustained by Bonus Action each turn)",
		"target": "All humanoids and giants within 300 ft. that can hear",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Charmed", "Incapacitated", "Compelled to move toward singer"],
		"effect": "Creatures within 300 ft. that hear the song must succeed on a WIS save or be charmed and incapacitated, using all movement to approach the singer each turn. Target re-saves at end of each turn if more than 5 ft. from the singer.",
	},
	"Baleful Baying": {
		"description": "The creature lets out a baleful howl. Every creature within 300 feet that can hear the howl must succeed on a Wisdom saving throw or be frightened of this creature until the end of its next turn.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "300 ft.",
		"duration": "Until end of target's next turn",
		"target": "All creatures within 300 ft. that can hear",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Frightened"],
		"effect": "All creatures within 300 ft. that hear the howl must succeed on a WIS save or be frightened until the end of their next turn.",
	},
	"Gibbering": {
		"description": "The creature babbles incoherently while it can see any creature and isn't incapacitated. Each creature that starts its turn within 20 feet of the creature and can hear the gibbering must succeed on a Wisdom saving throw or be unable to take reactions until the start of its next turn, and must roll a d8 to determine what it does during its turn: 1-4, it does nothing; 5-6, it takes no action or bonus action and uses all its movement to move in a randomly determined direction; 7-8, it makes a melee attack against a randomly determined creature within its reach, or it does nothing if it can't make such an attack.",
		"action_type": "Passive",
		"recharge": "",
		"range": "20 ft.",
		"duration": "Until start of target's next turn",
		"target": "All creatures within 20 ft. that can hear",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Cannot take reactions", "Random action (d8 table)"],
		"effect": "Creatures starting their turn within 20 ft. while hearing the gibbering must save or lose reactions and roll a d8 for their action: 1-4 = nothing; 5-6 = random movement only; 7-8 = melee attack against a random creature in reach.",
	},
	"Mummy Rot": {
		"description": "A creature cursed by this ability can't regain hit points and its hit point maximum decreases by 10 (3d6) for every 24 hours that elapse. If the curse reduces the target's hit point maximum to 0, the target dies and its body turns to dust. The curse lasts until removed by a remove curse spell or similar magic.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until removed by magic",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CHA",
		"damage_dice": "3d6",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Cursed (Mummy Rot): cannot regain HP, HP maximum decreases 10 per day"],
		"effect": "Attack deals bludgeoning damage and curses the target on a failed CON save. Cursed targets cannot regain HP and lose 10 max HP every 24 hours. Target dies and crumbles to dust if max HP reaches 0. Only remove curse ends the effect.",
	},
	"Diseased Bite": {
		"description": "The creature's bite carries a contagious disease. On a hit, the target must succeed on a Constitution saving throw or contract the creature's disease. The specific disease, its mechanical effects, incubation period, and how it can be cured are defined per-creature.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until cured",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "1d6+3",
		"damage_type": "piercing",
		"conditions_applied": ["Diseased"],
		"effect": "Melee bite attack that deals piercing damage. On a hit, target must succeed on a CON save or contract a disease. The specific disease, its effects, and cure are defined per-creature.",
	},
	"Spore Infection": {
		"description": "When a creature takes damage from this creature's attack or comes into contact with its spores, it must succeed on a Constitution saving throw or contract a spore infection. While infected, the creature has disadvantage on ability checks and saving throws using a specific ability score. The infection ends when the creature succeeds on a saving throw at the end of a long rest.",
		"action_type": "Passive",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until cured",
		"target": "One creature that takes damage from or is exposed to the creature's spores",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Diseased (Spore Infection)"],
		"effect": "Creatures taking damage from or exposed to the creature's spores must succeed on a CON save or contract a spore infection, imposing disadvantage on checks using a specific ability score. Infection clears after a successful long rest save. Specific ability score affected is defined per-creature.",
	},
	"Implant Egg": {
		"description": "The creature implants an egg in an incapacitated or successfully grappled creature. A humanoid can carry only one such egg at a time. While an egg is implanted, the host's speed is reduced and it has disadvantage on attack rolls, ability checks, and saving throws. After a set number of days, the egg hatches, tearing out of the host's body. The egg can be removed by a successful DC 20 Wisdom (Medicine) check or by magic such as cure disease.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Until egg hatches or is removed",
		"target": "One incapacitated or grappled creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "2d6",
		"damage_type": "piercing",
		"conditions_applied": ["Speed reduced by 10 ft.", "Disadvantage on attacks, checks, and saves while egg gestates"],
		"effect": "Implants an egg in an incapacitated or grappled target. The host has reduced speed and disadvantage on all attacks, checks, and saves while the egg gestates. After a set number of days the egg hatches, killing the host. Only a Medicine check (DC 20) or cure disease removes it safely. Gestation time and hatched creature type are defined per-creature.",
	},
	"Slow": {
		"description": "The creature targets up to six creatures it can see within 120 feet in a 40-foot cube. Each target must succeed on a Wisdom saving throw or be affected for 1 minute. An affected target's speed is halved, it takes a -2 penalty to AC and Dexterity saving throws, and it can't use reactions. On its turn, it can use either an action or a bonus action, not both. Regardless of the creature's abilities or magic items, it can't make more than one melee or ranged attack during its turn. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
		"action_type": "Action",
		"recharge": "",
		"range": "120 ft. (40 ft. cube)",
		"duration": "Concentration, up to 1 minute",
		"target": "Up to 6 creatures in a 40 ft. cube",
		"saving_throw": "WIS",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Slowed: half speed, -2 AC and DEX saves, no reactions, only action or bonus action (not both), max one attack per turn"],
		"effect": "Targets that fail a WIS save are slowed for up to 1 minute. Slowed creatures have halved speed, -2 AC and DEX saves, cannot use reactions, can only take an action or bonus action (not both), and are limited to one attack per turn. Re-save at end of each turn.",
	},
	"Phantasms": {
		"description": "The creature seeds phantasmal images directly into a target's mind. One creature within 120 feet must succeed on a Wisdom saving throw. On a failed save, the target takes psychic damage and is frightened of an illusory threat created by the creature for up to 1 minute. The frightened creature can repeat the saving throw at the end of each of its turns, ending the effect on a success.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "120 ft.",
		"duration": "Concentration, up to 1 minute",
		"target": "One creature",
		"saving_throw": "WIS",
		"save_dc_stat": "INT",
		"damage_dice": "1d10",
		"damage_type": "psychic",
		"conditions_applied": ["Frightened"],
		"effect": "On a failed WIS save, deals 1d10 psychic damage and frightens the target for up to 1 minute with a phantasmal illusion. Target re-saves at end of each turn.",
	},
}
