const DATA: Dictionary = {

	"Marshal Undead": {
		"description": "The creature can command and direct undead creatures within 60 feet that are not currently under another creature's control. Undead that fail a Wisdom saving throw must obey the creature's commands for 24 hours or until the creature uses this ability again. Undead that succeed on the saving throw are immune to this ability for 24 hours.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "24 hours",
		"target": "All uncontrolled undead within 60 ft.",
		"saving_throw": "WIS",
		"save_dc_stat": "CHA",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Commands all uncontrolled undead within 60 ft. Undead that fail a WIS save obey the creature's commands for 24 hours or until this ability is used again. Undead that succeed are immune for 24 hours.",
	},
	"Animate Chains": {
		"description": "The creature magically animates up to four chains it can see within 60 feet. Each animated chain has AC 20, 20 HP, immunity to fire and psychic damage, and can make attacks using the creature's statistics. The chains are immune to conditions and act on the creature's initiative. The creature can direct the chains as a bonus action. Chains revert to normal if the creature dies.",
		"action_type": "Bonus Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "Until creature dies or dismisses",
		"target": "Up to 4 chains within 60 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Animates up to 4 chains within 60 ft. Animated chains are AC 20, have 20 HP, and are immune to fire, psychic damage, and all conditions. They act on the creature's initiative and are directed as a bonus action.",
	},
	"Animate Trees": {
		"description": "The creature magically animates one or two trees it can see within 60 feet. These trees have the same statistics as Treants but lack the Animate Trees ability. They act on the creature's initiative and obey its commands. An animated tree reverts to being an ordinary tree when it drops to 0 hit points or when the creature dies or is more than 120 feet from it.",
		"action_type": "Action",
		"recharge": "",
		"range": "60 ft.",
		"duration": "1 day or until destroyed",
		"target": "Up to two nonmagical trees within 60 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Animates up to two nonmagical trees within 60 ft. Animated trees use Treant statistics without Animate Trees. They obey commands and revert when reduced to 0 HP, when the creature dies, or when it moves more than 120 ft. away.",
	},
	"Animate Boulders": {
		"description": "The creature magically animates up to three boulders it can see within 60 feet. Each animated boulder has AC 14, 20 hit points, and uses the creature's attack modifier for its slam attacks. Animated boulders act on the creature's initiative and obey its commands. They revert to inert boulders when they drop to 0 hit points or when the creature dies.",
		"action_type": "Action",
		"recharge": "Short Rest",
		"range": "60 ft.",
		"duration": "Until destroyed or creature dies",
		"target": "Up to three boulders within 60 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "2d10+4",
		"damage_type": "bludgeoning",
		"conditions_applied": [],
		"effect": "Animates up to three boulders within 60 ft. Each animated boulder has AC 14, 20 HP, and deals 2d10+4 bludgeoning damage on a slam. They act on the creature's initiative and revert when destroyed or when the creature dies.",
	},
	"Animating Spores": {
		"description": "The creature releases animating spores into the corpse of a Small or Medium beast or humanoid within 5 feet of it. After 24 hours, the target rises as a spore servant using the spore servant stat block for its type. The spore servant obeys the creature's commands indefinitely and never takes a short or long rest.",
		"action_type": "Action",
		"recharge": "",
		"range": "5 ft.",
		"duration": "Permanent until destroyed",
		"target": "One corpse of a Small or Medium beast or humanoid within 5 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Infects a nearby corpse of a Small or Medium beast or humanoid with animating spores. After 24 hours it rises as a spore servant that obeys the creature's commands indefinitely.",
	},
	"Create Specter": {
		"description": "The creature targets one humanoid within 10 feet that died within the past minute. The target's spirit rises as a specter in the space of its corpse or in the nearest unoccupied space. The specter is under the creature's control, acts on the creature's turn, and is added to the creature's pool of controlled specters. The creature can have no more than a set number of specters under its control at one time.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "Permanent until destroyed",
		"target": "One humanoid that died within the last minute within 10 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Raises the spirit of a recently slain humanoid as a specter under the creature's control. The specter acts on the creature's initiative. Maximum number of simultaneously controlled specters is defined per-creature.",
	},
	"Summon Specters": {
		"description": "The creature summons a group of specters from the realm of the dead. The specters appear in unoccupied spaces within 30 feet of the creature, act on the creature's initiative, and obey its verbal commands. The summoned specters remain for 1 hour or until the creature dies, at which point they return to the realm of the dead. The number of specters summoned is defined per-creature.",
		"action_type": "Action",
		"recharge": "1/Day",
		"range": "30 ft.",
		"duration": "1 hour",
		"target": "Unoccupied spaces within 30 ft.",
		"saving_throw": "",
		"save_dc_stat": "",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": [],
		"effect": "Summons a number of specters in unoccupied spaces within 30 ft. Specters act on the creature's initiative and obey its commands. They disappear after 1 hour or when the creature dies. Number summoned is defined per-creature.",
	},
	"Entangle": {
		"description": "Grasping plants and vines sprout from the ground in a 20-foot square area within 90 feet. For the duration, the area is difficult terrain. A creature in the area when the plants appear must succeed on a Strength saving throw or be restrained by the entangling plants until the area's plants disappear. A creature restrained by the plants can use its action to make a Strength check against the saving throw DC. On a success, it frees itself.",
		"action_type": "Action",
		"recharge": "",
		"range": "90 ft. (20 ft. square area)",
		"duration": "Concentration, up to 1 minute",
		"target": "All creatures in a 20 ft. square area within 90 ft.",
		"saving_throw": "STR",
		"save_dc_stat": "WIS",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained"],
		"effect": "Creates a 20 ft. square of difficult terrain. Creatures in the area must succeed on a STR save or be restrained. Restrained creatures can re-attempt the STR check as an action each turn to escape.",
	},
	"Hair Snare": {
		"description": "The creature's animated hair lashes out to ensnare a target within 15 feet. The target must succeed on a Strength saving throw or be grappled and restrained. While restrained, the creature can't use its hair to snare additional creatures. A restrained creature can use its action to make a Strength (Athletics) check against the save DC to escape. The creature can release a grappled creature at will.",
		"action_type": "Action",
		"recharge": "",
		"range": "15 ft.",
		"duration": "Until escaped or creature releases",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "2d6+4",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Grappled", "Restrained"],
		"effect": "On a failed STR save, target is grappled and restrained by the creature's animated hair. While a creature is held this way, the hair cannot snare another. Target can attempt a STR (Athletics) check as an action to escape.",
	},
	"Grasping Tendrils": {
		"description": "The creature extends grasping tendrils to seize a creature within 10 feet. On a hit, the target is grappled and restrained. While grappled, the restrained creature takes necrotic damage at the start of each of the creature's turns. A grappled creature can use its action to make a Strength (Athletics) check against the creature's STR to escape. The creature can grapple one target per tendril and the number of tendrils it possesses is defined per-creature.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "Until escaped or creature dies",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "STR",
		"damage_dice": "2d8+5",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Grappled", "Restrained"],
		"effect": "On a hit, target is grappled and restrained. While restrained, the target takes 2d8+5 bludgeoning damage at the start of each of the creature's turns. Target can escape with a STR (Athletics) check as an action. Number of simultaneous targets is defined per-creature.",
	},
	"Web": {
		"description": "The creature hurls a glob of sticky webbing at a point within range. One Large or smaller creature in contact with the webbing must succeed on a Strength saving throw or be restrained by it. A creature restrained by the web can use its action to make a Strength check, freeing itself on a success. The web can also be attacked and destroyed (AC 10, 5 hit points, vulnerability to fire damage).",
		"action_type": "Action",
		"recharge": "5-6",
		"range": "30/60 ft.",
		"duration": "1 hour",
		"target": "One Large or smaller creature",
		"saving_throw": "STR",
		"save_dc_stat": "CON",
		"damage_dice": "",
		"damage_type": "",
		"conditions_applied": ["Restrained"],
		"effect": "Hurls webbing that restrains one Large or smaller creature on a failed STR save. Restrained creature can escape with a STR check as an action. The web can be destroyed (AC 10, 5 HP, vulnerable to fire).",
	},
	"Shadow Webs": {
		"description": "The creature unleashes tendrils of living shadow that deal necrotic damage and attempt to restrain a target within 30 feet. The target must succeed on a Strength saving throw or be restrained and blinded while entangled in the shadow webs. The shadow webs are invisible in dim light or darkness. A restrained creature can use its action to make a Strength check to escape. The webs last up to 1 minute.",
		"action_type": "Action",
		"recharge": "",
		"range": "30 ft.",
		"duration": "Concentration, up to 1 minute",
		"target": "One creature",
		"saving_throw": "STR",
		"save_dc_stat": "CHA",
		"damage_dice": "2d8",
		"damage_type": "necrotic",
		"conditions_applied": ["Restrained", "Blinded (while in shadow web)"],
		"effect": "Deals 2d8 necrotic damage. On a failed STR save, target is restrained and blinded by shadow webs for up to 1 minute. Shadow webs are invisible in dim light or darkness. Target can escape with a STR check as an action.",
	},
	"Paralyzing Tentacles": {
		"description": "The creature lashes out with venom-coated tentacles. On a hit, the target must succeed on a Constitution saving throw or become paralyzed by injected venom. The paralysis lasts up to 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on a success. Unlike a standard paralyzing attack, these tentacles can be extended or projected at range.",
		"action_type": "Action",
		"recharge": "",
		"range": "10 ft.",
		"duration": "1 minute",
		"target": "One creature",
		"saving_throw": "CON",
		"save_dc_stat": "CON",
		"damage_dice": "2d6+4",
		"damage_type": "bludgeoning",
		"conditions_applied": ["Paralyzed"],
		"effect": "Melee tentacle attack that deals bludgeoning damage. On a hit, target must succeed on a CON save or be paralyzed for up to 1 minute. Target re-saves at end of each turn.",
	},
}
