const DATA: Dictionary = {
	"Beholder": {
		"max_health": 180, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 500,
		"weapons": ["Eye Rays", "Bite"],
		"abilities": ["Eye Rays", "Antimagic Cone"],
		"armor": ["Natural Armor"],
	},
	"Aboleth": {
		"max_health": 135, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 425,
		"weapons": ["Tentacle", "Tail"],
		"abilities": ["Enslave", "Mucous Cloud", "Probing Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Balhannoth": {
		"max_health": 114, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 3.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 475,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Legendary Resistance", "Reality Rewrite", "Warp Space"],
		"armor": ["Natural Armor"],
	},
	"Berbalang": {
		"max_health": 38, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": -1.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 80,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Spectral Duplicate", "Psychic Feast"],
		"armor": ["Natural Armor"],
	},
	"Blue Slaad": {
		"max_health": 123, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": -2.0, "charisma": -1.0,
		"gold_value": 275,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Magic Resistance", "Implant Egg", "Regeneration"],
		"armor": ["Natural Armor"],
	},
	"Chaos Quadrapod": {
		"max_health": 114, "armor_class": 15, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 425,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Disintegrating Beam", "Tentacle Whip"],
		"armor": ["Natural Armor"],
	},
	"Choker": {
		"max_health": 13, "armor_class": 16, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Tentacle"],
		"abilities": ["Aberrant Quickness", "Boneless", "Spider Climb"],
		"armor": ["Natural Armor"],
	},
	"Chuul": {
		"max_health": 93, "armor_class": 16, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 150,
		"weapons": ["Pincer", "Tentacle"],
		"abilities": ["Amphibious", "Sense Magic", "Paralyzing Tentacles"],
		"armor": ["Natural Armor"],
	},
	"Cloaker": {
		"max_health": 78, "armor_class": 14, "damage_amount": 3.5, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 325,
		"weapons": ["Bite", "Tail"],
		"abilities": ["False Appearance", "Moan", "Phantasms", "Light Sensitivity"],
		"armor": ["Natural Armor"],
	},
	"Darkweaver": {
		"max_health": 52, "armor_class": 14, "damage_amount": 2.5, "element_type": "shadow",
		"strength": 0.0, "dexterity": 4.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 150,
		"weapons": ["Claw", "Web Strand"],
		"abilities": ["Shadow Webs", "Darkness"],
		"armor": ["Natural Armor"],
	},
	"Death Kiss": {
		"max_health": 161, "armor_class": 16, "damage_amount": 4.0, "element_type": "storm",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 425,
		"weapons": ["Tentacle", "Blood Drain"],
		"abilities": ["Blood Drain", "Lightning Blood"],
		"armor": ["Natural Armor"],
	},
	"Death Slaad": {
		"max_health": 170, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 3.0,
		"gold_value": 425,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Magic Resistance", "Regeneration", "Shapechange"],
		"armor": ["Natural Armor"],
	},
	"Derro": {
		"max_health": 13, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": -3.0, "charisma": -1.0,
		"gold_value": 25,
		"weapons": ["Hooked Spear", "Light Crossbow"],
		"abilities": ["Magic Resistance", "Sunlight Sensitivity"],
		"armor": ["Leather"],
	},
	"Dolgrim": {
		"max_health": 13, "armor_class": 15, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Morningstar", "Hand Crossbow", "Claw"],
		"abilities": ["Dual Minds", "Multiple Limbs"],
		"armor": ["Natural Armor"],
	},
	"Elder Brain": {
		"max_health": 210, "armor_class": 10, "damage_amount": 5.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 5.0, "wisdom": 4.0, "charisma": 7.0,
		"gold_value": 625,
		"weapons": ["Tentacle"],
		"abilities": ["Creature Sense", "Legendary Resistance", "Mind Blast", "Psychic Link", "Dominate"],
		"armor": ["Natural Armor"],
	},
	"Elder Brain Dragon": {
		"max_health": 350, "armor_class": 19, "damage_amount": 6.0, "element_type": "none",
		"strength": 7.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": 6.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 800,
		"weapons": ["Bite", "Claw", "Tail"],
		"abilities": ["Mind Blast", "Psychic Breath", "Fly", "Telepathy"],
		"armor": ["Dragon Scales"],
	},
	"Eye Monger": {
		"max_health": 71, "armor_class": 13, "damage_amount": 3.0, "element_type": "none",
		"strength": 4.0, "dexterity": -2.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Eye Rays", "Antimagic Field"],
		"armor": ["Natural Armor"],
	},
	"Eye of Flame": {
		"max_health": 66, "armor_class": 13, "damage_amount": 3.0, "element_type": "fire",
		"strength": 0.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Fire Eye Rays", "Levitate"],
		"armor": ["Natural Armor"],
	},
	"Eyedrake": {
		"max_health": 85, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 225,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Eye Rays", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Feyr": {
		"max_health": 52, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 150,
		"weapons": ["Claw"],
		"abilities": ["Amorphous", "Fear Aura", "Invisibility"],
		"armor": ["Natural Armor"],
	},
	"Flumph": {
		"max_health": 7, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Tendril"],
		"abilities": ["Advanced Telepathy", "Stench Spray", "Telepathic Shroud"],
		"armor": ["Natural Armor"],
	},
	"Gargantua": {
		"max_health": 310, "armor_class": 15, "damage_amount": 6.0, "element_type": "none",
		"strength": 8.0, "dexterity": -2.0, "constitution": 8.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 800,
		"weapons": ["Slam", "Bite", "Tentacle"],
		"abilities": ["Siege Monster", "Tremorsense"],
		"armor": ["Natural Armor"],
	},
	"Gauth": {
		"max_health": 67, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 225,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Eye Rays", "Stunning Gaze"],
		"armor": ["Natural Armor"],
	},
	"Gazer": {
		"max_health": 13, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": -4.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Eye Rays", "Mimicry"],
		"armor": ["Natural Armor"],
	},
	"Giant Intellect Devourer": {
		"max_health": 55, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Claws"],
		"abilities": ["Detect Sentience", "Devour Intellect", "Body Thief"],
		"armor": ["Natural Armor"],
	},
	"Gibbering Mouther": {
		"max_health": 67, "armor_class": 9, "damage_amount": 2.0, "element_type": "none",
		"strength": 0.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 80,
		"weapons": ["Bite", "Blinding Spittle"],
		"abilities": ["Aberrant Ground", "Gibbering"],
		"armor": ["Natural Armor"],
	},
	"Gith": {
		"max_health": 28, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 55,
		"weapons": ["Greatsword", "Longbow"],
		"abilities": ["Psionics", "Teleport"],
		"armor": ["Natural Armor"],
	},
	"Githyanki": {
		"max_health": 49, "armor_class": 17, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 130,
		"weapons": ["Greatsword", "Longbow"],
		"abilities": ["Psionics", "War Magic", "Telekinetic Leap"],
		"armor": ["Half Plate"],
	},
	"Githzerai": {
		"max_health": 38, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": 3.0, "wisdom": 3.0, "charisma": 0.0,
		"gold_value": 90,
		"weapons": ["Unarmed Strike", "Shortsword"],
		"abilities": ["Psionics", "Psychic Defense", "Telekinetic Leap"],
		"armor": ["Natural Armor"],
	},
	"Gnome Ceremorph": {
		"max_health": 60, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 150,
		"weapons": ["Tentacle", "Claw"],
		"abilities": ["Mind Blast", "Innate Spellcasting", "Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Gnome Squidling": {
		"max_health": 27, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 80,
		"weapons": ["Tentacle", "Dagger"],
		"abilities": ["Telepathy", "Partial Transformation"],
		"armor": ["Natural Armor"],
	},
	"Gray Slaad": {
		"max_health": 127, "armor_class": 18, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": -1.0, "charisma": 2.0,
		"gold_value": 375,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Shapechanger", "Magic Resistance", "Regeneration"],
		"armor": ["Natural Armor"],
	},
	"Green Slaad": {
		"max_health": 127, "armor_class": 16, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": 1.0,
		"gold_value": 325,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Shapechanger", "Magic Resistance", "Regeneration"],
		"armor": ["Natural Armor"],
	},
	"Grell": {
		"max_health": 55, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 120,
		"weapons": ["Tentacle", "Beak"],
		"abilities": ["Blind Sight", "Paralyzing Tentacles", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Grimlock": {
		"max_health": 11, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 20,
		"weapons": ["Spiked Bone Club"],
		"abilities": ["Blind Senses", "Keen Hearing and Smell", "Stone Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Intellect Devourer": {
		"max_health": 21, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 80,
		"weapons": ["Claws"],
		"abilities": ["Detect Sentience", "Devour Intellect", "Body Thief"],
		"armor": ["Natural Armor"],
	},
	"Ixitxachitl": {
		"max_health": 18, "armor_class": 14, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 25,
		"weapons": ["Bite", "Barbed Tail"],
		"abilities": ["Blood Frenzy", "Water Breathing", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Kuo-toa": {
		"max_health": 18, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 30,
		"weapons": ["Bite", "Spear", "Net"],
		"abilities": ["Amphibious", "Otherworldly Perception", "Slippery", "Sunlight Sensitivity"],
		"armor": ["Natural Armor", "Shield"],
	},
	"Living Web": {
		"max_health": 52, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 120,
		"weapons": ["Slam", "Web Strand"],
		"abilities": ["Amorphous", "Web Walk", "Entangle"],
		"armor": ["Natural Armor"],
	},
	"Mind Flayer": {
		"max_health": 71, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 275,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Mind Blast", "Extract Brain", "Innate Spellcasting", "Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Mind Flayer Clairvoyant": {
		"max_health": 71, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 325,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Mind Blast", "Clairvoyance", "Scrying", "Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Mindwitness": {
		"max_health": 75, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 200,
		"weapons": ["Tentacle", "Eye Rays"],
		"abilities": ["Eye Rays", "Telepathic Hub", "Shared Senses"],
		"armor": ["Natural Armor"],
	},
	"Morkoth": {
		"max_health": 130, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 5.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 475,
		"weapons": ["Bite", "Tentacle"],
		"abilities": ["Amphibious", "Hypnosis", "Reflect Spell", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Mutate": {
		"max_health": 45, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 85,
		"weapons": ["Claw", "Slam"],
		"abilities": ["Aberrant Mutations", "Unpredictable Attack"],
		"armor": ["Natural Armor"],
	},
	"Neh-thalggu": {
		"max_health": 178, "armor_class": 15, "damage_amount": 5.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 6.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 575,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Brain Collection", "Collected Brains", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Neo-otyugh": {
		"max_health": 110, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 375,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Limited Telepathy", "Diseased Bite", "Psionics"],
		"armor": ["Natural Armor"],
	},
	"Neogi": {
		"max_health": 33, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": -2.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 120,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Mental Bondage", "Spider Climb", "Web"],
		"armor": ["Natural Armor"],
	},
	"Neothelid": {
		"max_health": 325, "armor_class": 16, "damage_amount": 5.0, "element_type": "none",
		"strength": 8.0, "dexterity": -2.0, "constitution": 7.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 575,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Psychic Spittle", "Swallow", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Nothic": {
		"max_health": 45, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 80,
		"weapons": ["Claw"],
		"abilities": ["Keen Sight", "Weird Insight", "Rotting Gaze"],
		"armor": ["Natural Armor"],
	},
	"Otyugh": {
		"max_health": 114, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Limited Telepathy", "Diseased Bite"],
		"armor": ["Natural Armor"],
	},
	"Phaerimm": {
		"max_health": 204, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 6.0, "intelligence": 7.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 675,
		"weapons": ["Bite", "Tail Spine"],
		"abilities": ["Innate Spellcasting", "Life Drain", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Psurlon": {
		"max_health": 52, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 120,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Psionic Powers", "Detect Magic", "Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Red Slaad": {
		"max_health": 93, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": -2.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Magic Resistance", "Implant Egg", "Regeneration"],
		"armor": ["Natural Armor"],
	},
	"Roper": {
		"max_health": 93, "armor_class": 20, "damage_amount": 3.0, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 3.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Tendril", "Bite"],
		"abilities": ["False Appearance", "Grasping Tendrils", "Spider Climb"],
		"armor": ["Natural Armor"],
	},
	"Skittering Horror": {
		"max_health": 45, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 100,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Spider Climb", "Pack Tactics", "Skitter"],
		"armor": ["Natural Armor"],
	},
	"Skum": {
		"max_health": 13, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 25,
		"weapons": ["Bite", "Claw", "Spear"],
		"abilities": ["Amphibious", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Slaad": {
		"max_health": 93, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": -2.0, "charisma": -2.0,
		"gold_value": 150,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Magic Resistance", "Regeneration"],
		"armor": ["Natural Armor"],
	},
	"Spectator": {
		"max_health": 39, "armor_class": 14, "damage_amount": 2.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 120,
		"weapons": ["Bite", "Eye Rays"],
		"abilities": ["Eye Rays", "Telepathy"],
		"armor": ["Natural Armor"],
	},
	"Star Spawn": {
		"max_health": 100, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 250,
		"weapons": ["Slam", "Tentacle"],
		"abilities": ["Psychic Orb", "Void Touch"],
		"armor": ["Natural Armor"],
	},
	"Star Spawn Hulk": {
		"max_health": 136, "armor_class": 16, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 425,
		"weapons": ["Slam"],
		"abilities": ["Psychic Mirror", "Reaping Arms", "Whirlwind of Madness"],
		"armor": ["Natural Armor"],
	},
	"Star Spawn Mangler": {
		"max_health": 71, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": -1.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Claw"],
		"abilities": ["Ambusher", "Darkness Aura", "Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Star Spawn Seer": {
		"max_health": 153, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 6.0, "wisdom": 4.0, "charisma": 3.0,
		"gold_value": 575,
		"weapons": ["Staff", "Tentacle"],
		"abilities": ["Bolts of Madness", "Psychic Orb", "Void Passage", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Tsucora Quori": {
		"max_health": 78, "armor_class": 16, "damage_amount": 3.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 275,
		"weapons": ["Claw", "Dream Touch"],
		"abilities": ["Psionic Powers", "Fear", "Incorporate"],
		"armor": ["Natural Armor"],
	},
	"Ulitharid": {
		"max_health": 127, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 375,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Mind Blast", "Extract Brain", "Psionic Hub", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Woe Strider": {
		"max_health": 133, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 475,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Inescapable Stride", "Pacify", "Unhappy Ending"],
		"armor": ["Natural Armor"],
	},
}
