const DATA: Dictionary = {
	"Goat": {
		"max_health": 10, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 50,
		"weapons": ["Headbutt", "Horn Attack", "Hoof Strike"],
		"abilities": ["Charge", "Buck"],
		"armor": ["Fur", "Hide"],
		"should_bob": false,
		"terrain_multipliers": { "mud": 0.5, "puddle": 0.7, "grass": 1.2, "stone": 1.0, "fire": 1.3 },
		"comm_signal": "screamed",
		"comm_range": 15.0,
		"comm_probability": 0.25,
		"charge_speed_base": 25.0,
		"charge_speed_per_str": 5.0,
		"charge_distance_base": 5.0,
		"charge_dist_per_str": 1.0,
		"ai_behaviors": ["flock", "rowdy", "charge_on_sight"],
		"flock_leader_type": "goat",
		"flock_min_distance": 1.0,
		"flock_max_distance": 5.0,
		"rowdy_radius": 8.0,
		"rowdy_bonus_per_actor": 0.25,
		"rowdy_actor_filter": "goat",
		"charge_alert_duration": 1.0,
		"charge_cooldown_duration": 3.0,
		"ability_pool": ["goat_charge"],
	},
	"Chicken": {
		"max_health": 4, "armor_class": 8, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Peck", "Talon Scratch"],
		"abilities": ["Flee", "Cluck Aura"],
		"armor": ["Feathers"],
	},
	"Cow": {
		"max_health": 15, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Headbutt", "Gore"],
		"abilities": ["Stampede", "Moo"],
		"armor": ["Hide"],
	},
	"Pig": {
		"max_health": 11, "armor_class": 9, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 30,
		"weapons": ["Bite", "Tusk Slam"],
		"abilities": ["Root", "Mudroll"],
		"armor": ["Hide"],
	},
	"Sheep": {
		"max_health": 8, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -1.0,
		"gold_value": 20,
		"weapons": ["Headbutt", "Hoof Strike"],
		"abilities": ["Herd Mentality"],
		"armor": ["Wool", "Fleece"],
	},
	"Wolf": {
		"max_health": 11, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pack Tactics", "Howl"],
		"armor": ["Fur"],
	},
	"Earthworm": {
		"max_health": 8, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": -1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Constrict"],
		"abilities": ["Burrow"],
		"armor": ["Slime Coat"],
	},
	"Alioramus": {
		"max_health": 38, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 90,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Allosaurus": {
		"max_health": 51, "armor_class": 13, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Charge", "Pounce"],
		"armor": ["Natural Armor"],
	},
	"Almiraj": {
		"max_health": 3, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 15,
		"weapons": ["Horn"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Angler Fish": {
		"max_health": 2, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": -1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Ankylosaurus": {
		"max_health": 68, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 150,
		"weapons": ["Tail Club"],
		"abilities": ["Tail Attack"],
		"armor": ["Natural Armor"],
	},
	"Ape": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Fist", "Rock Throw"],
		"abilities": ["Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Giant Ape": {
		"max_health": 157, "armor_class": 12, "damage_amount": 3.5, "element_type": "none",
		"strength": 7.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 275,
		"weapons": ["Fist", "Rock Throw"],
		"abilities": ["Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Archaeus": {
		"max_health": 45, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 100,
		"weapons": ["Bite", "Constrict"],
		"abilities": ["Keen Smell"],
		"armor": ["Scales"],
	},
	"Arctic Blindfish": {
		"max_health": 1, "armor_class": 6, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -1.0, "constitution": -2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Arctic Char": {
		"max_health": 1, "armor_class": 6, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 0.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Arctic Fox": {
		"max_health": 2, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Fur"],
	},
	"Arctic Goby": {
		"max_health": 1, "armor_class": 6, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 0.0, "constitution": -2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Arctic Skate": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Tail Barb"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Arctic Stink Squirrel": {
		"max_health": 2, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": ["Stench"],
		"armor": ["Fur"],
	},
	"Aurochs": {
		"max_health": 38, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 85,
		"weapons": ["Gore", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Hide"],
	},
	"Axe Beak": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Beak"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Baboon": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Badger": {
		"max_health": 3, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Burrow", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Barnacle": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -5.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Barovian Nightcrawler": {
		"max_health": 7, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Burrow"],
		"armor": ["Natural Armor"],
	},
	"Bat": {
		"max_health": 1, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Echolocation", "Keen Hearing"],
		"armor": ["Natural Armor"],
	},
	"Giant Bat": {
		"max_health": 22, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Echolocation", "Keen Hearing"],
		"armor": ["Natural Armor"],
	},
	"Bear": {
		"max_health": 34, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 70,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Beaver": {
		"max_health": 7, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Dam Builder"],
		"armor": ["Natural Armor"],
	},
	"Giant Fire Beetle": {
		"max_health": 4, "armor_class": 13, "damage_amount": 0.5, "element_type": "fire",
		"strength": -2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Illumination"],
		"armor": ["Chitin"],
	},
	"Beholderfish": {
		"max_health": 10, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 30,
		"weapons": ["Bite", "Eye Ray"],
		"abilities": ["Eye Ray"],
		"armor": ["Natural Armor"],
	},
	"Bestial Spirit": {
		"max_health": 30, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Claw", "Bite"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Black Bear": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Blood Hawk": {
		"max_health": 7, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 15,
		"weapons": ["Beak"],
		"abilities": ["Keen Sight", "Pack Tactics"],
		"armor": ["Feathers"],
	},
	"Blue King Crab": {
		"max_health": 13, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Claw"],
		"abilities": ["Water Breathing"],
		"armor": ["Shell"],
	},
	"Boar": {
		"max_health": 11, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Tusk"],
		"abilities": ["Charge", "Relentless"],
		"armor": ["Natural Armor"],
	},
	"Brontosaurus": {
		"max_health": 121, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 8.0, "dexterity": -2.0, "constitution": 6.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 200,
		"weapons": ["Stomp", "Tail"],
		"abilities": ["Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Brown Bear": {
		"max_health": 34, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Camel": {
		"max_health": 15, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": 3.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Cave Bear": {
		"max_health": 42, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 90,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Centipede": {
		"max_health": 2, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": ["Poison"],
		"armor": ["Chitin"],
	},
	"Chionthar Dusthawk": {
		"max_health": 7, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 12,
		"weapons": ["Talons", "Beak"],
		"abilities": ["Keen Sight"],
		"armor": ["Feathers"],
	},
	"Chiton": {
		"max_health": 1, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -3.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Giant Clam": {
		"max_health": 3, "armor_class": 17, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": -5.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 10,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Shell"],
	},
	"Coelacanth": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Combustion Belly Spiderling": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.5, "element_type": "fire",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Combustion", "Web"],
		"armor": ["Chitin"],
	},
	"Common Trollslyer": {
		"max_health": 4, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 8,
		"weapons": ["Bite", "Sting"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Cooshee": {
		"max_health": 11, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 30,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Crab": {
		"max_health": 2, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Giant Crab": {
		"max_health": 13, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Cranium Rat": {
		"max_health": 2, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Telepathy", "Shared Defense"],
		"armor": ["Natural Armor"],
	},
	"Giant Crayfish": {
		"max_health": 45, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 85,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Crocodile": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 40,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Giant Crocodile": {
		"max_health": 114, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 7.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 200,
		"weapons": ["Bite", "Tail"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Deep Rothé": {
		"max_health": 15, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 30,
		"weapons": ["Gore", "Hoof Strike"],
		"abilities": ["Darkvision"],
		"armor": ["Hide"],
	},
	"Deepfathom Devilfish": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite", "Tentacle"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Deer": {
		"max_health": 4, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Deinonychus": {
		"max_health": 26, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Pounce", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Devilfish": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite", "Tentacle"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Diatryma": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Beak", "Kick"],
		"abilities": [],
		"armor": ["Feathers"],
	},
	"Dimetrodon": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": [],
		"armor": ["Scales"],
	},
	"Dinosaur": {
		"max_health": 68, "armor_class": 13, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 150,
		"weapons": ["Bite", "Stomp"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Dire Badger": {
		"max_health": 27, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 55,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Burrow", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Dire Boar": {
		"max_health": 42, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 90,
		"weapons": ["Tusk"],
		"abilities": ["Charge", "Relentless"],
		"armor": ["Natural Armor"],
	},
	"Dire Wolf": {
		"max_health": 37, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Bite"],
		"abilities": ["Pack Tactics", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Dolphin": {
		"max_health": 11, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 20,
		"weapons": ["Ram"],
		"abilities": ["Echolocation", "Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Dragon Goby": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Eagle": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 10,
		"weapons": ["Talons"],
		"abilities": ["Keen Sight"],
		"armor": ["Feathers"],
	},
	"Giant Eagle": {
		"max_health": 26, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 60,
		"weapons": ["Talons", "Beak"],
		"abilities": ["Keen Sight"],
		"armor": ["Feathers"],
	},
	"Elephant": {
		"max_health": 76, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 8.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 150,
		"weapons": ["Gore", "Stomp"],
		"abilities": ["Trampling Charge"],
		"armor": ["Natural Armor"],
	},
	"Elk": {
		"max_health": 13, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Ram", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Giant Elk": {
		"max_health": 42, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 5.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 85,
		"weapons": ["Ram", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Emperor Crab": {
		"max_health": 27, "armor_class": 17, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 55,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Enchodus": {
		"max_health": 10, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Endoceras": {
		"max_health": 45, "armor_class": 14, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 100,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Shell"],
	},
	"Falcon": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Talons"],
		"abilities": ["Keen Sight", "Dive Attack"],
		"armor": ["Feathers"],
	},
	"Fireshear Petrel": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 5,
		"weapons": ["Beak"],
		"abilities": ["Keen Sight"],
		"armor": ["Feathers"],
	},
	"Flailfish": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Tail Flail"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Giant Fly": {
		"max_health": 3, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": [],
		"armor": ["Chitin"],
	},
	"Flying Monkey": {
		"max_health": 5, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 15,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Fly"],
		"armor": ["Natural Armor"],
	},
	"Fox": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Fur"],
	},
	"Giant Frog": {
		"max_health": 18, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Amphibious", "Swallow", "Tongue"],
		"armor": ["Natural Armor"],
	},
	"Frozenfar Flathead": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 0.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Frozenfar Quipper": {
		"max_health": 1, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Frozenfar Steelhead": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Giant Constrictor Snake": {
		"max_health": 60, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 85,
		"weapons": ["Bite", "Constrict"],
		"abilities": [],
		"armor": ["Scales"],
	},
	"Giant Devilfish": {
		"max_health": 27, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 55,
		"weapons": ["Bite", "Tentacle"],
		"abilities": ["Water Breathing", "Ink Cloud"],
		"armor": ["Natural Armor"],
	},
	"Giant Dragonfly": {
		"max_health": 13, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Fly"],
		"armor": ["Chitin"],
	},
	"Giant Eel": {
		"max_health": 27, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 45,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Giant Flying Spider": {
		"max_health": 16, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 30,
		"weapons": ["Bite"],
		"abilities": ["Web", "Fly", "Spider Climb"],
		"armor": ["Chitin"],
	},
	"Giant Plaice": {
		"max_health": 11, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Giant Snail": {
		"max_health": 13, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": -2.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Giant Venomous Snake": {
		"max_health": 52, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 85,
		"weapons": ["Bite"],
		"abilities": ["Poison"],
		"armor": ["Scales"],
	},
	"Giant Wolf Spider": {
		"max_health": 11, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Spider Climb", "Web Sense"],
		"armor": ["Chitin"],
	},
	"Glacefish": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Giant Goat": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 35,
		"weapons": ["Ram"],
		"abilities": ["Charge", "Sure-Footed"],
		"armor": ["Natural Armor"],
	},
	"Goblin Shark": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 30,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Goose": {
		"max_health": 4, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": ["Bite", "Wing Buffet"],
		"abilities": [],
		"armor": ["Feathers"],
	},
	"Gorgonocephalus": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Gorilla": {
		"max_health": 27, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 55,
		"weapons": ["Fist", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Gurry Shark": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Hadrosaurus": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Tail", "Hoof Strike"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Halibut": {
		"max_health": 4, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Hare": {
		"max_health": 1, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Hawk": {
		"max_health": 1, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 8,
		"weapons": ["Talons"],
		"abilities": ["Keen Sight"],
		"armor": ["Feathers"],
	},
	"Horse": {
		"max_health": 13, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Hoof Strike"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"House Cat": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 5,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Hyaenodon": {
		"max_health": 27, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 55,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Hyena": {
		"max_health": 5, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Ice Climber": {
		"max_health": 5, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Spider Climb"],
		"armor": ["Chitin"],
	},
	"Ice Spider": {
		"max_health": 10, "armor_class": 13, "damage_amount": 1.0, "element_type": "ice",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Spider Climb", "Web", "Poison"],
		"armor": ["Chitin"],
	},
	"Icebound Whelk": {
		"max_health": 3, "armor_class": 14, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": -2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Icewind Eel": {
		"max_health": 5, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Icewind Smelt": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Jackal": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Jaculi": {
		"max_health": 16, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Bite"],
		"abilities": ["Standing Leap"],
		"armor": ["Scales"],
	},
	"Killer Whale": {
		"max_health": 90, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 130,
		"weapons": ["Bite"],
		"abilities": ["Echolocation", "Hold Breath", "Keen Hearing"],
		"armor": ["Natural Armor"],
	},
	"Krill": {
		"max_health": 1, "armor_class": 5, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -1.0, "constitution": -3.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Lancetfish": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Lantern Fish": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -2.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing", "Bioluminescence"],
		"armor": ["Natural Armor"],
	},
	"Leech": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 2,
		"weapons": ["Bite"],
		"abilities": ["Blood Drain"],
		"armor": ["Natural Armor"],
	},
	"Lion": {
		"max_health": 26, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Pack Tactics", "Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Lizard": {
		"max_health": 2, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": [],
		"armor": ["Scales"],
	},
	"Giant Lizard": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 30,
		"weapons": ["Bite"],
		"abilities": [],
		"armor": ["Scales"],
	},
	"Lovely Emperor Beetle": {
		"max_health": 3, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": [],
		"abilities": [],
		"armor": ["Chitin"],
	},
	"Lugworm": {
		"max_health": 1, "armor_class": 5, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -1.0, "constitution": -2.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Mackerel Icefish": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Mammoth": {
		"max_health": 126, "armor_class": 13, "damage_amount": 4.0, "element_type": "none",
		"strength": 8.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 240,
		"weapons": ["Gore", "Stomp"],
		"abilities": ["Trampling Charge"],
		"armor": ["Natural Armor"],
	},
	"Mastiff": {
		"max_health": 5, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Megalodon": {
		"max_health": 155, "armor_class": 14, "damage_amount": 5.0, "element_type": "none",
		"strength": 8.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 450,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Monkfish": {
		"max_health": 4, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Monstrous Centipede": {
		"max_health": 10, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Poison", "Burrow"],
		"armor": ["Chitin"],
	},
	"Monstrous Scorpion": {
		"max_health": 13, "armor_class": 14, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 30,
		"weapons": ["Claw", "Sting"],
		"abilities": ["Poison"],
		"armor": ["Chitin"],
	},
	"Moonglow Herring": {
		"max_health": 1, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing", "Bioluminescence"],
		"armor": ["Natural Armor"],
	},
	"Moose": {
		"max_health": 42, "armor_class": 11, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 90,
		"weapons": ["Antler Gore", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Mountain Goat": {
		"max_health": 13, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Ram"],
		"abilities": ["Sure-Footed", "Charge"],
		"armor": ["Natural Armor"],
	},
	"Mule": {
		"max_health": 11, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 15,
		"weapons": ["Hoof Strike"],
		"abilities": ["Beast of Burden"],
		"armor": ["Natural Armor"],
	},
	"Myrmidon": {
		"max_health": 7, "armor_class": 14, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Claw"],
		"abilities": ["Pack Tactics"],
		"armor": ["Shell"],
	},
		"Nautilus": {
		"max_health": 5, "armor_class": 16, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Tentacle"],
		"abilities": ["Water Breathing"],
		"armor": ["Shell"],
	},
	"Nelma": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Ninespine Stickleback": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Northern Haddock": {
		"max_health": 3, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Northern Pike": {
		"max_health": 7, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Northern Seahorse": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Northern Squid": {
		"max_health": 5, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Tentacle"],
		"abilities": ["Water Breathing", "Ink Cloud"],
		"armor": ["Natural Armor"],
	},
	"Northern Whelk": {
		"max_health": 2, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": -1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Octopus": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Tentacle"],
		"abilities": ["Ink Cloud", "Underwater Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Giant Octopus": {
		"max_health": 52, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 60,
		"weapons": ["Tentacle", "Bite"],
		"abilities": ["Ink Cloud", "Underwater Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Otter": {
		"max_health": 3, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Owl": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 3.0, "charisma": -2.0,
		"gold_value": 8,
		"weapons": ["Talons"],
		"abilities": ["Keen Hearing and Sight", "Flyby"],
		"armor": ["Feathers"],
	},
	"Giant Owl": {
		"max_health": 19, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": -1.0,
		"gold_value": 25,
		"weapons": ["Talons"],
		"abilities": ["Keen Hearing and Sight", "Flyby"],
		"armor": ["Feathers"],
	},
	"Ox": {
		"max_health": 15, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Gore"],
		"abilities": ["Beast of Burden"],
		"armor": ["Natural Armor"],
	},
	"Panther": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 25,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Peacock": {
		"max_health": 4, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 10,
		"weapons": ["Beak"],
		"abilities": [],
		"armor": ["Feathers"],
	},
	"Plesiosaurus": {
		"max_health": 68, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 90,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Polar Bear": {
		"max_health": 42, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 90,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Fur"],
	},
	"Polar Oarfish": {
		"max_health": 13, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Pteranodon": {
		"max_health": 13, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Fly"],
		"armor": ["Natural Armor"],
	},
	"Queen's Knife": {
		"max_health": 7, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Quetzalcoatlus": {
		"max_health": 30, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 85,
		"weapons": ["Bite"],
		"abilities": ["Fly", "Dive Attack"],
		"armor": ["Natural Armor"],
	},
	"Quipper": {
		"max_health": 1, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Rat": {
		"max_health": 1, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Giant Rat": {
		"max_health": 7, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Raven": {
		"max_health": 1, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 5,
		"weapons": ["Beak"],
		"abilities": ["Mimicry"],
		"armor": ["Feathers"],
	},
	"Giant Raven": {
		"max_health": 13, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Beak", "Talon"],
		"abilities": ["Mimicry", "Keen Sight"],
		"armor": ["Feathers"],
	},
	"Razor Clam": {
		"max_health": 2, "armor_class": 14, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": -2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Reef Clam": {
		"max_health": 1, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": -3.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": [],
		"armor": ["Shell"],
	},
	"Reindeer": {
		"max_health": 13, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Antler Gore", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Rhinoceros": {
		"max_health": 45, "armor_class": 11, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 90,
		"weapons": ["Gore"],
		"abilities": ["Trampling Charge"],
		"armor": ["Natural Armor"],
	},
	"Rock Lobster": {
		"max_health": 13, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Rot Grub": {
		"max_health": 1, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 2,
		"weapons": ["Bite"],
		"abilities": ["Burrow", "Infestation"],
		"armor": ["Natural Armor"],
	},
	"Rothé": {
		"max_health": 22, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Gore", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Hide"],
	},
	"Saber-toothed Tiger": {
		"max_health": 52, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 90,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Scorpion": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 0.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 3,
		"weapons": ["Sting"],
		"abilities": ["Poison"],
		"armor": ["Chitin"],
	},
	"Sea Deva": {
		"max_health": 45, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 80,
		"weapons": ["Bite", "Ram"],
		"abilities": ["Hold Breath", "Echolocation"],
		"armor": ["Natural Armor"],
	},
	"Sea Gull": {
		"max_health": 1, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 3,
		"weapons": ["Beak"],
		"abilities": [],
		"armor": ["Feathers"],
	},
	"Sea Nettle": {
		"max_health": 3, "armor_class": 7, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 3,
		"weapons": ["Stinging Tentacles"],
		"abilities": ["Poison"],
		"armor": ["Natural Armor"],
	},
	"Seal": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Serpent Star": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Shaengarne Salmon": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Shark": {
		"max_health": 22, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 40,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Silvertail Barracuda": {
		"max_health": 5, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Skipjack Tuna": {
		"max_health": 5, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Sleeper Shark": {
		"max_health": 45, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 100,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Blood Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Snake": {
		"max_health": 2, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Poison"],
		"armor": ["Scales"],
	},
	"Constrictor Snake": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Bite", "Constrict"],
		"abilities": [],
		"armor": ["Scales"],
	},
	"Flying Snake": {
		"max_health": 5, "armor_class": 14, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 4.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Flyby", "Poison"],
		"armor": ["Scales"],
	},
	"Giant Snapping Turtle": {
		"max_health": 75, "armor_class": 17, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 130,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath", "Steady"],
		"armor": ["Shell"],
	},
	"Snow Leopard": {
		"max_health": 19, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 45,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Snowbarb": {
		"max_health": 1, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Sorcerer Shrimp": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": 1.0,
		"gold_value": 8,
		"weapons": [],
		"abilities": ["Minor Magic"],
		"armor": ["Natural Armor"],
	},
	"Sorcery Crow": {
		"max_health": 3, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 10,
		"weapons": ["Beak"],
		"abilities": ["Minor Spellcasting", "Mimicry"],
		"armor": ["Feathers"],
	},
	"Space Guppy": {
		"max_health": 1, "armor_class": 9, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Giant Space Hamster": {
		"max_health": 52, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 130,
		"weapons": ["Bite"],
		"abilities": ["Keen Smell"],
		"armor": ["Fur"],
	},
	"Sperm Whale": {
		"max_health": 97, "armor_class": 13, "damage_amount": 4.0, "element_type": "none",
		"strength": 9.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 350,
		"weapons": ["Bite", "Fluke"],
		"abilities": ["Echolocation", "Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Spider": {
		"max_health": 1, "armor_class": 12, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": ["Spider Climb", "Web Sense", "Poison"],
		"armor": ["Chitin"],
	},
	"Giant Spider": {
		"max_health": 26, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 60,
		"weapons": ["Bite"],
		"abilities": ["Spider Climb", "Web", "Poison"],
		"armor": ["Chitin"],
	},
	"Spiny Dogfish": {
		"max_health": 10, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Spotted Eelpout": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Spotted Lion": {
		"max_health": 26, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pack Tactics", "Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Stegosaurus": {
		"max_health": 76, "armor_class": 13, "damage_amount": 3.0, "element_type": "none",
		"strength": 6.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 150,
		"weapons": ["Tail Spikes"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Stirge": {
		"max_health": 2, "armor_class": 14, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Blood Drain"],
		"abilities": ["Blood Drain"],
		"armor": ["Natural Armor"],
	},
	"Sturgeon": {
		"max_health": 10, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Surface Rothé": {
		"max_health": 22, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Gore", "Hoof Strike"],
		"abilities": ["Charge"],
		"armor": ["Hide"],
	},
	"Swordsea Hake": {
		"max_health": 3, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Thayan Glassfish": {
		"max_health": 2, "armor_class": 9, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Tiger": {
		"max_health": 37, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pounce", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Titanothere": {
		"max_health": 52, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 6.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 110,
		"weapons": ["Gore", "Stomp"],
		"abilities": ["Trampling Charge"],
		"armor": ["Natural Armor"],
	},
	"Toad": {
		"max_health": 1, "armor_class": 11, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": 0.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Amphibious"],
		"armor": ["Natural Armor"],
	},
	"Giant Toad": {
		"max_health": 39, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 55,
		"weapons": ["Bite"],
		"abilities": ["Amphibious", "Swallow", "Tongue"],
		"armor": ["Natural Armor"],
	},
	"Torchlight Loosejaw": {
		"max_health": 2, "armor_class": 9, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing", "Bioluminescence"],
		"armor": ["Natural Armor"],
	},
	"Trackless Cod": {
		"max_health": 3, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Trackless Sailfish": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bill Strike"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Triceratops": {
		"max_health": 114, "armor_class": 13, "damage_amount": 3.5, "element_type": "none",
		"strength": 7.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 200,
		"weapons": ["Gore"],
		"abilities": ["Trampling Charge"],
		"armor": ["Natural Armor"],
	},
	"Trout": {
		"max_health": 2, "armor_class": 8, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 3,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Twohorn Sculpin": {
		"max_health": 2, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -3.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 2,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Natural Armor"],
	},
	"Tyrannosaurus": {
		"max_health": 136, "armor_class": 13, "damage_amount": 4.0, "element_type": "none",
		"strength": 7.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 300,
		"weapons": ["Bite", "Tail"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Valkur's Fish": {
		"max_health": 3, "armor_class": 9, "damage_amount": 0.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Velociraptor": {
		"max_health": 10, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Venomous Snake": {
		"max_health": 5, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Poison"],
		"armor": ["Scales"],
	},
	"Ventdiver": {
		"max_health": 5, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 8,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Vulture": {
		"max_health": 5, "armor_class": 10, "damage_amount": 0.0, "element_type": "none",
		"strength": -1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 8,
		"weapons": ["Beak", "Talon"],
		"abilities": ["Keen Sight and Smell", "Pack Tactics"],
		"armor": ["Feathers"],
	},
	"Giant Vulture": {
		"max_health": 22, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 30,
		"weapons": ["Beak", "Talon"],
		"abilities": ["Keen Sight and Smell", "Pack Tactics"],
		"armor": ["Feathers"],
	},
	"Walrus": {
		"max_health": 27, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 45,
		"weapons": ["Tusk"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Giant Wasp": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 30,
		"weapons": ["Sting"],
		"abilities": ["Poison", "Fly"],
		"armor": ["Chitin"],
	},
	"Waxworm": {
		"max_health": 1, "armor_class": 5, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -1.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -5.0, "charisma": -5.0,
		"gold_value": 1,
		"weapons": [],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Weasel": {
		"max_health": 1, "armor_class": 13, "damage_amount": 0.0, "element_type": "none",
		"strength": -4.0, "dexterity": 3.0, "constitution": -2.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 5,
		"weapons": ["Bite"],
		"abilities": ["Keen Hearing and Smell"],
		"armor": ["Natural Armor"],
	},
	"Giant Weasel": {
		"max_health": 9, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Keen Hearing and Smell"],
		"armor": ["Natural Armor"],
	},
	"Wolf Eel": {
		"max_health": 13, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Wolffish": {
		"max_health": 7, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite"],
		"abilities": ["Water Breathing"],
		"armor": ["Scales"],
	},
	"Wooly Crab": {
		"max_health": 19, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Yak": {
		"max_health": 19, "armor_class": 10, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Gore"],
		"abilities": [],
		"armor": ["Hide"],
	},
	"Yeti Crab": {
		"max_health": 13, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 20,
		"weapons": ["Claw"],
		"abilities": ["Amphibious"],
		"armor": ["Shell"],
	},
	"Zebra": {
		"max_health": 13, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Hoof Strike", "Bite"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
}
