const DATA: Dictionary = {
	"Angel": {
		"max_health": 136, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 400,
		"weapons": ["Divine Strike", "Radiant Blade"],
		"abilities": ["Healing Touch", "Divine Aura", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Animal Lord": {
		"max_health": 130, "armor_class": 17, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 4.0, "charisma": 3.0,
		"gold_value": 375,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Shapechanger", "Command Animals", "Keen Senses"],
		"armor": ["Natural Armor"],
	},
	"Arcane": {
		"max_health": 189, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 8.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 600,
		"weapons": ["Arcane Blast"],
		"abilities": ["Innate Spellcasting", "Legendary Resistance", "Telepathy"],
		"armor": ["Celestial Hide"],
	},
	"Aurumach": {
		"max_health": 204, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 5.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 5.0, "charisma": 5.0,
		"gold_value": 600,
		"weapons": ["Golden Blade", "Radiant Strike"],
		"abilities": ["Legendary Resistance", "Spellcasting", "Telepathy"],
		"armor": ["Celestial Hide"],
	},
	"Avoral": {
		"max_health": 119, "armor_class": 17, "damage_amount": 3.5, "element_type": "none",
		"strength": 2.0, "dexterity": 5.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 375,
		"weapons": ["Talon", "Wing Buffet"],
		"abilities": ["Fly", "Keen Sight", "Spellcasting"],
		"armor": ["Feathers"],
	},
	"Bariaur": {
		"max_health": 68, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Ram", "Hoof Strike", "Longbow"],
		"abilities": ["Charge", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Celestial": {
		"max_health": 71, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 250,
		"weapons": ["Divine Strike"],
		"abilities": ["Healing Touch", "Divine Aura"],
		"armor": ["Celestial Hide"],
	},
	"Cosmic Stag": {
		"max_health": 67, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Antler Gore", "Hoof Strike"],
		"abilities": ["Charge", "Divine Aura"],
		"armor": ["Natural Armor"],
	},
	"Couatl": {
		"max_health": 97, "armor_class": 19, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 5.0, "constitution": 3.0, "intelligence": 4.0, "wisdom": 5.0, "charisma": 5.0,
		"gold_value": 150,
		"weapons": ["Bite", "Constrict"],
		"abilities": ["Innate Spellcasting", "Magic Weapons", "Shielded Mind"],
		"armor": ["Natural Armor"],
	},
	"Cuprilach": {
		"max_health": 136, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 3.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 4.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 400,
		"weapons": ["Copper Blade", "Radiant Strike"],
		"abilities": ["Spellcasting", "Telepathy"],
		"armor": ["Celestial Hide"],
	},
	"Dabus": {
		"max_health": 93, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 275,
		"weapons": ["Staff"],
		"abilities": ["Rebus Speech", "Levitate", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Deva": {
		"max_health": 136, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 400,
		"weapons": ["Mace"],
		"abilities": ["Healing Touch", "Innate Spellcasting", "Magic Resistance", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Empyrean": {
		"max_health": 313, "armor_class": 22, "damage_amount": 6.0, "element_type": "none",
		"strength": 10.0, "dexterity": 2.0, "constitution": 8.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 9.0,
		"gold_value": 900,
		"weapons": ["Maul", "Bolt"],
		"abilities": ["Legendary Resistance", "Divine Aura", "Innate Spellcasting", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Empyrean Iota": {
		"max_health": 27, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 80,
		"weapons": ["Divine Touch"],
		"abilities": ["Divine Aura", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Equinal": {
		"max_health": 93, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 275,
		"weapons": ["Hoof Strike", "Ram"],
		"abilities": ["Charge", "Magic Resistance", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Fensir": {
		"max_health": 78, "armor_class": 14, "damage_amount": 3.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 225,
		"weapons": ["Axe", "Slam"],
		"abilities": ["Divine Resistance", "Keen Senses"],
		"armor": ["Natural Armor"],
	},
	"Ferrumach": {
		"max_health": 171, "armor_class": 18, "damage_amount": 4.5, "element_type": "none",
		"strength": 5.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 500,
		"weapons": ["Iron Blade", "Radiant Strike"],
		"abilities": ["Legendary Resistance", "Spellcasting", "Telepathy"],
		"armor": ["Celestial Hide"],
	},
	"Guardian Naga": {
		"max_health": 127, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 3.0, "dexterity": 4.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 5.0, "charisma": 5.0,
		"gold_value": 400,
		"weapons": ["Bite", "Spit Poison"],
		"abilities": ["Rejuvenation", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Hollyphant": {
		"max_health": 35, "armor_class": 18, "damage_amount": 2.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 200,
		"weapons": ["Tusk", "Trumpet"],
		"abilities": ["Innate Spellcasting", "Trumpet of Blasting", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Hound Archon": {
		"max_health": 97, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 225,
		"weapons": ["Bite", "Greatsword"],
		"abilities": ["Keen Smell", "Magic Resistance", "Shapechanger"],
		"armor": ["Natural Armor"],
	},
	"Ki-rin": {
		"max_health": 152, "armor_class": 20, "damage_amount": 4.5, "element_type": "none",
		"strength": 5.0, "dexterity": 4.0, "constitution": 5.0, "intelligence": 5.0, "wisdom": 6.0, "charisma": 6.0,
		"gold_value": 500,
		"weapons": ["Hooves", "Horn"],
		"abilities": ["Innate Spellcasting", "Magic Resistance", "Legendary Resistance", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Kindori": {
		"max_health": 127, "armor_class": 12, "damage_amount": 3.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 4.0, "charisma": 2.0,
		"gold_value": 375,
		"weapons": ["Ram", "Tail Slap"],
		"abilities": ["Divinity Aura", "Healing Spores", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Lantern Archon": {
		"max_health": 27, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": -2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 80,
		"weapons": ["Light Ray"],
		"abilities": ["Aura of Menace", "Radiance"],
		"armor": ["Celestial Hide"],
	},
	"Musteval": {
		"max_health": 60, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 0.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 150,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell", "Magic Resistance", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Pegasus": {
		"max_health": 59, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 80,
		"weapons": ["Hooves"],
		"abilities": ["Fly"],
		"armor": ["Natural Armor"],
	},
	"Petitioner": {
		"max_health": 13, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Unarmed Strike"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"Planetar": {
		"max_health": 200, "armor_class": 19, "damage_amount": 5.5, "element_type": "none",
		"strength": 7.0, "dexterity": 4.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 6.0, "charisma": 6.0,
		"gold_value": 650,
		"weapons": ["Greatsword"],
		"abilities": ["Divine Awareness", "Healing Touch", "Innate Spellcasting", "Magic Resistance", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Reigar": {
		"max_health": 156, "armor_class": 20, "damage_amount": 4.5, "element_type": "none",
		"strength": 3.0, "dexterity": 5.0, "constitution": 3.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 7.0,
		"gold_value": 500,
		"weapons": ["Talarith", "Radiant Strike"],
		"abilities": ["Artistic Magnificence", "Innate Spellcasting", "Legendary Resistance"],
		"armor": ["Celestial Hide"],
	},
	"Rilmani": {
		"max_health": 117, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 4.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 400,
		"weapons": ["Radiant Strike"],
		"abilities": ["Spellcasting", "Telepathy", "Magic Resistance"],
		"armor": ["Celestial Hide"],
	},
	"Solar": {
		"max_health": 243, "armor_class": 21, "damage_amount": 6.0, "element_type": "none",
		"strength": 10.0, "dexterity": 6.0, "constitution": 8.0, "intelligence": 6.0, "wisdom": 6.0, "charisma": 7.0,
		"gold_value": 850,
		"weapons": ["Greatsword", "Slaying Longbow"],
		"abilities": ["Divine Awareness", "Healing Touch", "Legendary Resistance", "Innate Spellcasting", "Magic Resistance", "Fly"],
		"armor": ["Celestial Hide"],
	},
	"Sphinx": {
		"max_health": 199, "armor_class": 17, "damage_amount": 5.5, "element_type": "none",
		"strength": 8.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 5.0, "wisdom": 5.0, "charisma": 6.0,
		"gold_value": 700,
		"weapons": ["Claw"],
		"abilities": ["Inscrutable", "Legendary Resistance", "Spellcasting", "Roar"],
		"armor": ["Natural Armor"],
	},
	"Sphinx of Wonder": {
		"max_health": 136, "armor_class": 16, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 5.0, "charisma": 5.0,
		"gold_value": 450,
		"weapons": ["Claw"],
		"abilities": ["Inscrutable", "Spellcasting", "Roar"],
		"armor": ["Natural Armor"],
	},
	"Unicorn": {
		"max_health": 67, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 200,
		"weapons": ["Hooves", "Horn"],
		"abilities": ["Charge", "Healing Horn", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Warden Archon": {
		"max_health": 180, "armor_class": 18, "damage_amount": 5.0, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 3.0, "wisdom": 5.0, "charisma": 4.0,
		"gold_value": 575,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Keen Smell", "Magic Resistance", "Spellcasting"],
		"armor": ["Celestial Hide"],
	},
}
