const DATA: Dictionary = {
	"Scarecrow": {
		"max_health": 36, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 45,
		"weapons": ["Claw", "Slam"],
		"abilities": ["Horrifying Visage", "Scare"],
		"armor": ["Natural Armor"],
	},
	"Homunculus": {
		"max_health": 5, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Telepathic Bond"],
		"armor": ["Natural Armor"],
	},
	"Monodrone": {
		"max_health": 5, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 15,
		"weapons": ["Fist", "Javelin"],
		"abilities": ["Axiomatic Mind", "Disintegration"],
		"armor": ["Natural Armor"],
	},
	"Flying Sword": {
		"max_health": 17, "armor_class": 17, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -3.0, "charisma": -5.0,
		"gold_value": 20,
		"weapons": ["Longsword"],
		"abilities": ["Antimagic Susceptibility", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Duodrone": {
		"max_health": 11, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 20,
		"weapons": ["Fist"],
		"abilities": ["Axiomatic Mind", "Disintegration"],
		"armor": ["Natural Armor"],
	},
	"Tridrone": {
		"max_health": 16, "armor_class": 15, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 35,
		"weapons": ["Fist", "Javelin"],
		"abilities": ["Axiomatic Mind", "Disintegration"],
		"armor": ["Natural Armor"],
	},
	"Guardian Portrait": {
		"max_health": 22, "armor_class": 5, "damage_amount": 2.0, "element_type": "none",
		"strength": -5.0, "dexterity": -5.0, "constitution": 0.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 40,
		"weapons": ["Telekinesis"],
		"abilities": ["Antimagic Susceptibility", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Stone Cursed": {
		"max_health": 19, "armor_class": 17, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": -3.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 40,
		"weapons": ["Claw"],
		"abilities": ["Petrifying Touch"],
		"armor": ["Natural Armor"],
	},
	"Animated Armor": {
		"max_health": 33, "armor_class": 18, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 40,
		"weapons": ["Slam"],
		"abilities": ["Antimagic Susceptibility", "False Appearance"],
		"armor": ["Plate Armor"],
	},
	"Quadrone": {
		"max_health": 22, "armor_class": 16, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 50,
		"weapons": ["Fist", "Shortbow"],
		"abilities": ["Axiomatic Mind", "Disintegration"],
		"armor": ["Natural Armor"],
	},
	"Rug of Smothering": {
		"max_health": 33, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 100,
		"weapons": ["Smother"],
		"abilities": ["Antimagic Susceptibility", "Damage Transfer", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Pentadrone": {
		"max_health": 32, "armor_class": 16, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 100,
		"weapons": ["Arm"],
		"abilities": ["Axiomatic Mind", "Disintegration", "Paralysis Gas"],
		"armor": ["Natural Armor"],
	},
	"Helmed Horror": {
		"max_health": 60, "armor_class": 20, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 175,
		"weapons": ["Longsword"],
		"abilities": ["Magic Resistance", "Spell Immunity"],
		"armor": ["Plate Armor"],
	},
	"Nimblewright": {
		"max_health": 45, "armor_class": 18, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 175,
		"weapons": ["Rapier"],
		"abilities": ["Magic Resistance", "Sure-Footed"],
		"armor": ["Natural Armor"],
	},
	"Stone Defender": {
		"max_health": 52, "armor_class": 16, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 175,
		"weapons": ["Shield Slam"],
		"abilities": ["Magic Resistance", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Flesh Golem": {
		"max_health": 93, "armor_class": 9, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 200,
		"weapons": ["Slam"],
		"abilities": ["Berserk", "Lightning Absorption", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Gorgon": {
		"max_health": 114, "armor_class": 19, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 200,
		"weapons": ["Gore", "Hooves"],
		"abilities": ["Trampling Charge", "Petrifying Breath"],
		"armor": ["Natural Armor"],
	},
	"Shield Guardian": {
		"max_health": 142, "armor_class": 17, "damage_amount": 4.5, "element_type": "none",
		"strength": 4.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 300,
		"weapons": ["Fist"],
		"abilities": ["Bound", "Regeneration", "Shield", "Spell Storing"],
		"armor": ["Natural Armor"],
	},
	"Clay Golem": {
		"max_health": 133, "armor_class": 14, "damage_amount": 5.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -5.0,
		"gold_value": 425,
		"weapons": ["Slam"],
		"abilities": ["Acid Absorption", "Berserk", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Tomb Tapper": {
		"max_health": 145, "armor_class": 17, "damage_amount": 6.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 450,
		"weapons": ["Claw", "Abdominal Bite"],
		"abilities": ["Siege Monster", "Stone Shape", "Tunneling"],
		"armor": ["Natural Armor"],
	},
	"Stone Golem": {
		"max_health": 178, "armor_class": 17, "damage_amount": 6.0, "element_type": "none",
		"strength": 6.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -5.0,
		"gold_value": 450,
		"weapons": ["Slam"],
		"abilities": ["Immutable Form", "Magic Resistance", "Magic Weapons", "Slow"],
		"armor": ["Natural Armor"],
	},
	"Kolyarut": {
		"max_health": 143, "armor_class": 19, "damage_amount": 7.0, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 5.0,
		"gold_value": 600,
		"weapons": ["Longsword", "Enervating Touch"],
		"abilities": ["Innate Spellcasting", "Magic Resistance", "Magic Weapons"],
		"armor": ["Natural Armor"],
	},
	"Cadaver Collector": {
		"max_health": 189, "armor_class": 17, "damage_amount": 7.5, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 700,
		"weapons": ["Slam"],
		"abilities": ["Magic Resistance", "Paralyzing Field", "Summon Specters"],
		"armor": ["Natural Armor"],
	},
	"Retriever": {
		"max_health": 210, "armor_class": 19, "damage_amount": 7.5, "element_type": "none",
		"strength": 6.0, "dexterity": 3.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 700,
		"weapons": ["Foreleg", "Web"],
		"abilities": ["Magic Weapons", "Spell Storing"],
		"armor": ["Natural Armor"],
	},
	"Iron Golem": {
		"max_health": 210, "armor_class": 20, "damage_amount": 9.0, "element_type": "none",
		"strength": 7.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -5.0,
		"gold_value": 1000,
		"weapons": ["Slam", "Sword"],
		"abilities": ["Fire Absorption", "Immutable Form", "Magic Resistance", "Magic Weapons", "Poison Breath"],
		"armor": ["Natural Armor"],
	},
	"Steel Predator": {
		"max_health": 207, "armor_class": 20, "damage_amount": 9.0, "element_type": "none",
		"strength": 7.0, "dexterity": 3.0, "constitution": 6.0, "intelligence": 0.0, "wisdom": 3.0, "charisma": 0.0,
		"gold_value": 1000,
		"weapons": ["Bite", "Claw"],
		"abilities": ["Magic Resistance", "Selective Senses", "Stunning Screech"],
		"armor": ["Natural Armor"],
	},
	"Marut": {
		"max_health": 432, "armor_class": 22, "damage_amount": 14.0, "element_type": "none",
		"strength": 9.0, "dexterity": 1.0, "constitution": 8.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 3000,
		"weapons": ["Unerring Slam"],
		"abilities": ["Immutable Form", "Innate Spellcasting", "Magic Resistance", "Magic Weapons"],
		"armor": ["Natural Armor"],
	},
	"Living Unseen Servant": {
		"max_health": 2, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": 0.0, "constitution": -1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Slam"],
		"abilities": ["Invisibility"],
		"armor": ["Natural Armor"],
	},
	"Metallic Warbler": {
		"max_health": 7, "armor_class": 13, "damage_amount": 0.75, "element_type": "none",
		"strength": -2.0, "dexterity": 3.0, "constitution": -1.0, "intelligence": -3.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 20,
		"weapons": ["Beak"],
		"abilities": ["Dragon Bond", "Mimicry"],
		"armor": ["Natural Armor"],
	},
	"Skull Flier": {
		"max_health": 13, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": -2.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 30,
		"weapons": ["Stinger"],
		"abilities": ["Flyby"],
		"armor": ["Natural Armor"],
	},
	"Hypnos Magen": {
		"max_health": 9, "armor_class": 11, "damage_amount": 2.0, "element_type": "none",
		"strength": -1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 40,
		"weapons": ["Psychic Crush"],
		"abilities": ["Hypnotic Touch", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Carrionette": {
		"max_health": 21, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 40,
		"weapons": ["Needles", "Silver Needle"],
		"abilities": ["Soul Swap", "Paralyzing Needles"],
		"armor": ["Natural Armor"],
	},
	"Fiendish Icon": {
		"max_health": 22, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 40,
		"weapons": ["Fiery Eruption"],
		"abilities": ["False Appearance", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Stained Glass Golem": {
		"max_health": 33, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 100,
		"weapons": ["Shard Slash"],
		"abilities": ["False Appearance", "Light Refraction"],
		"armor": ["Natural Armor"],
	},
	"Clockwork Horror": {
		"max_health": 30, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 100,
		"weapons": ["Bite", "Razor Saw"],
		"abilities": ["Hive Mind", "Lightning Bolt"],
		"armor": ["Natural Armor"],
	},
	"Demos Magen": {
		"max_health": 51, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Longsword"],
		"abilities": ["Fiery Blood", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Snow Golem": {
		"max_health": 52, "armor_class": 13, "damage_amount": 3.0, "element_type": "ice",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -5.0,
		"gold_value": 120,
		"weapons": ["Slam", "Snowball"],
		"abilities": ["Cold Absorption", "False Appearance", "Snowblind Strike"],
		"armor": ["Natural Armor"],
	},
	"Galvan Magen": {
		"max_health": 58, "armor_class": 12, "damage_amount": 3.0, "element_type": "storm",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 120,
		"weapons": ["Electric Touch"],
		"abilities": ["Electrified Blood", "Lightning Bolt", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Iron Cobra": {
		"max_health": 45, "armor_class": 13, "damage_amount": 3.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 175,
		"weapons": ["Bite"],
		"abilities": ["Magic Resistance", "Poison Bite", "Locate Creature"],
		"armor": ["Natural Armor"],
	},
	"Metallic Peacekeeper": {
		"max_health": 55, "armor_class": 16, "damage_amount": 3.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 175,
		"weapons": ["Fist"],
		"abilities": ["Dragon Bond", "Soothing Mist"],
		"armor": ["Natural Armor"],
	},
	"Living Bigby's Hand": {
		"max_health": 95, "armor_class": 10, "damage_amount": 3.5, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -5.0,
		"gold_value": 175,
		"weapons": ["Forceful Hand"],
		"abilities": ["Grasping Hand", "Interposing Hand"],
		"armor": ["Natural Armor"],
	},
	"Decaton": {
		"max_health": 119, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 350,
		"weapons": ["Tentacle"],
		"abilities": ["Axiomatic Mind", "Innate Spellcasting", "Disintegration"],
		"armor": ["Natural Armor"],
	},
	"Scaladar": {
		"max_health": 133, "armor_class": 19, "damage_amount": 5.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -5.0,
		"gold_value": 350,
		"weapons": ["Claw", "Sting"],
		"abilities": ["Lightning Absorption", "Scaladar Link"],
		"armor": ["Natural Armor"],
	},
	"Fiendish Flesh Golem": {
		"max_health": 139, "armor_class": 9, "damage_amount": 5.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 350,
		"weapons": ["Slam"],
		"abilities": ["Berserk", "Fire Resistance", "Lightning Absorption", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Nonaton": {
		"max_health": 178, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 450,
		"weapons": ["Tentacle"],
		"abilities": ["Axiomatic Mind", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Crystal Golem": {
		"max_health": 133, "armor_class": 17, "damage_amount": 6.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 450,
		"weapons": ["Crystal Shard", "Crystal Dart"],
		"abilities": ["Crystal Burst", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Chardalyn Dragon": {
		"max_health": 202, "armor_class": 18, "damage_amount": 6.5, "element_type": "shadow",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 500,
		"weapons": ["Bite", "Claw", "Tail"],
		"abilities": ["Chardalyn Aura", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Dragonbone Golem": {
		"max_health": 161, "armor_class": 17, "damage_amount": 6.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 500,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Aura of Doom", "Petrifying Breath", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Octon": {
		"max_health": 209, "armor_class": 18, "damage_amount": 6.5, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 3.0, "charisma": 2.0,
		"gold_value": 500,
		"weapons": ["Tentacle"],
		"abilities": ["Axiomatic Mind", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Stone Juggernaut": {
		"max_health": 175, "armor_class": 15, "damage_amount": 7.0, "element_type": "none",
		"strength": 5.0, "dexterity": -3.0, "constitution": 5.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 550,
		"weapons": ["Slam"],
		"abilities": ["Crushing Advance", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Septon": {
		"max_health": 225, "armor_class": 19, "damage_amount": 7.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 550,
		"weapons": ["Claw"],
		"abilities": ["Axiomatic Mind", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Hexton": {
		"max_health": 240, "armor_class": 19, "damage_amount": 7.0, "element_type": "none",
		"strength": 5.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 600,
		"weapons": ["Fist", "Claw"],
		"abilities": ["Axiomatic Mind", "Innate Spellcasting", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Canopic Golem": {
		"max_health": 178, "armor_class": 16, "damage_amount": 7.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 600,
		"weapons": ["Fist", "Crystal Dart"],
		"abilities": ["Immutable Form", "Magic Resistance", "Spell Redirect"],
		"armor": ["Natural Armor"],
	},
	"Hellfire Engine": {
		"max_health": 216, "armor_class": 18, "damage_amount": 9.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -4.0,
		"gold_value": 1000,
		"weapons": ["Hellfire Flail", "Thunder Cannon"],
		"abilities": ["Hellfire", "Immutable Form", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Walking Statue of Waterdeep": {
		"max_health": 314, "armor_class": 17, "damage_amount": 11.0, "element_type": "none",
		"strength": 7.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -5.0,
		"gold_value": 1500,
		"weapons": ["Slam"],
		"abilities": ["False Appearance", "Immutable Form", "Magic Resistance", "Truesight"],
		"armor": ["Natural Armor"],
	},
	"Stone Colossus": {
		"max_health": 432, "armor_class": 20, "damage_amount": 14.0, "element_type": "none",
		"strength": 8.0, "dexterity": -2.0, "constitution": 8.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -5.0,
		"gold_value": 3000,
		"weapons": ["Fist"],
		"abilities": ["Immutable Form", "Magic Resistance", "Magic Weapons", "Terror Aura"],
		"armor": ["Natural Armor"],
	},
}
