const DATA: Dictionary = {
	"Fire Dragon": {
		"max_health": 256, "armor_class": 19, "damage_amount": 6.0, "element_type": "fire",
		"strength": 9.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 4.0,
		"gold_value": 600,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Fly", "Roar"],
		"armor": ["Dragon Scales"],
	},
	"Ice Dragon": {
		"max_health": 225, "armor_class": 18, "damage_amount": 5.5, "element_type": "ice",
		"strength": 8.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 580,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Frost Breath", "Fly", "Roar"],
		"armor": ["Dragon Scales"],
	},
	"Storm Dragon": {
		"max_health": 243, "armor_class": 19, "damage_amount": 6.0, "element_type": "storm",
		"strength": 8.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 620,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Lightning Breath", "Fly", "Roar"],
		"armor": ["Dragon Scales"],
	},
	"Shadow Dragon": {
		"max_health": 189, "armor_class": 19, "damage_amount": 5.0, "element_type": "shadow",
		"strength": 7.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 5.0,
		"gold_value": 650,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Shadow Breath", "Fly", "Living Shadow"],
		"armor": ["Dragon Scales"],
	},
	"Pseudodragon": {
		"max_health": 7, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": -2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Sting", "Bite"],
		"abilities": ["Telepathic Bond", "Magic Resistance"],
		"armor": ["Natural Armor"],
		# Hornbound — house-cat-sized red-brown dragon, leathery wings, scorpion tail.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 0.40,
			"palette.primary": Color(0.62, 0.30, 0.18),    # rusty red-brown
			"palette.secondary": Color(0.40, 0.18, 0.10),
			"palette.accent": Color(0.85, 0.65, 0.30),     # gold belly
			"palette.eye": Color(0.95, 0.78, 0.20),
			"ornaments.tags": ["wings", "horns", "tail"],
		},
	},
	"Ambush Drake": {
		"max_health": 18, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Bite"],
		"abilities": ["Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Faerie Dragon": {
		"max_health": 14, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": 5.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 35,
		"weapons": ["Bite"],
		"abilities": ["Superior Invisibility", "Magic Resistance", "Euphoria Breath"],
		"armor": ["Natural Armor"],
	},
	"Brass Dragon Wyrmling": {
		"max_health": 16, "armor_class": 16, "damage_amount": 1.5, "element_type": "fire",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 40,
		"weapons": ["Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Copper Dragon Wyrmling": {
		"max_health": 22, "armor_class": 16, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 40,
		"weapons": ["Bite"],
		"abilities": ["Acid Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Guard Drake": {
		"max_health": 52, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Bite", "Tail"],
		"abilities": [],
		"armor": ["Natural Armor"],
	},
	"White Dragon Wyrmling": {
		"max_health": 32, "armor_class": 16, "damage_amount": 2.0, "element_type": "ice",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 65,
		"weapons": ["Bite"],
		"abilities": ["Frost Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Black Dragon Wyrmling": {
		"max_health": 33, "armor_class": 17, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 65,
		"weapons": ["Bite"],
		"abilities": ["Acid Breath", "Fly", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Bronze Dragon Wyrmling": {
		"max_health": 32, "armor_class": 17, "damage_amount": 2.0, "element_type": "storm",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 65,
		"weapons": ["Bite"],
		"abilities": ["Lightning Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Silver Dragon Wyrmling": {
		"max_health": 45, "armor_class": 17, "damage_amount": 2.5, "element_type": "ice",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 70,
		"weapons": ["Bite"],
		"abilities": ["Frost Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Green Dragon Wyrmling": {
		"max_health": 38, "armor_class": 17, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 65,
		"weapons": ["Bite"],
		"abilities": ["Poison Breath", "Fly", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Blue Dragon Wyrmling": {
		"max_health": 52, "armor_class": 17, "damage_amount": 2.5, "element_type": "storm",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 90,
		"weapons": ["Bite"],
		"abilities": ["Lightning Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Gold Dragon Wyrmling": {
		"max_health": 60, "armor_class": 17, "damage_amount": 2.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 3.0,
		"gold_value": 100,
		"weapons": ["Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Red Dragon Wyrmling": {
		"max_health": 75, "armor_class": 17, "damage_amount": 3.0, "element_type": "fire",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 130,
		"weapons": ["Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Wyvern": {
		"max_health": 110, "armor_class": 13, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 185,
		"weapons": ["Bite", "Claws", "Stinger"],
		"abilities": ["Fly"],
		"armor": ["Natural Armor"],
		# Hornbound — drake: dusk-grey scales, big leathery wings, venomous stinger tail. No front legs.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 1.65,
			"palette.primary": Color(0.42, 0.40, 0.45),    # dusk grey
			"palette.secondary": Color(0.24, 0.22, 0.28),
			"palette.accent": Color(0.62, 0.30, 0.45),     # poison-purple stinger
			"palette.eye": Color(0.95, 0.65, 0.10),
			"face.eye_glow": true,
			"ornaments.tags": ["wings", "tail", "bone_protrusion"],
		},
	},
	"Brass Dragon Young": {
		"max_health": 110, "armor_class": 17, "damage_amount": 4.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 190,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"White Dragon Young": {
		"max_health": 133, "armor_class": 17, "damage_amount": 4.5, "element_type": "ice",
		"strength": 4.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 190,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Frost Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Copper Dragon Young": {
		"max_health": 119, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 225,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Acid Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Black Dragon Young": {
		"max_health": 127, "armor_class": 18, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 220,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Acid Breath", "Fly", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Green Dragon Young": {
		"max_health": 136, "armor_class": 18, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 255,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Poison Breath", "Fly", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Bronze Dragon Young": {
		"max_health": 142, "armor_class": 18, "damage_amount": 5.5, "element_type": "storm",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 260,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Lightning Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Silver Dragon Young": {
		"max_health": 168, "armor_class": 18, "damage_amount": 5.5, "element_type": "ice",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 4.0,
		"gold_value": 285,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Frost Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Blue Dragon Young": {
		"max_health": 152, "armor_class": 17, "damage_amount": 5.5, "element_type": "storm",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 280,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Lightning Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Gold Dragon Young": {
		"max_health": 178, "armor_class": 18, "damage_amount": 6.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 5.0,
		"gold_value": 315,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Fire Breath", "Weakening Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"Red Dragon Young": {
		"max_health": 178, "armor_class": 18, "damage_amount": 6.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 4.0,
		"gold_value": 310,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Dragon Scales"],
	},
	"White Dragon Adult": {
		"max_health": 200, "armor_class": 18, "damage_amount": 7.0, "element_type": "ice",
		"strength": 6.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 420,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Frost Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge: pure white scales tinged blue-silver, ice-blue glowing eyes, frost crystals.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.20,
			"palette.primary": Color(0.92, 0.95, 0.99),    # frost white
			"palette.secondary": Color(0.55, 0.78, 0.92),  # icy blue shadow
			"palette.accent": Color(0.30, 0.85, 1.0),      # bright cyan
			"palette.eye": Color(0.45, 0.95, 1.0),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "crystal_growth"],
		},
	},
	"Brass Dragon Adult": {
		"max_health": 172, "armor_class": 18, "damage_amount": 7.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 415,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Black Dragon Adult": {
		"max_health": 195, "armor_class": 19, "damage_amount": 7.5, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 435,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Acid Breath", "Fly", "Legendary Resistance", "Frightful Presence", "Amphibious"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge swamp dragon: oil-black scales, single curving horn, sickly green acid eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.30,
			"palette.primary": Color(0.08, 0.10, 0.08),    # oil-black
			"palette.secondary": Color(0.20, 0.18, 0.14),
			"palette.accent": Color(0.45, 0.62, 0.30),     # acid swamp green
			"palette.eye": Color(0.40, 0.95, 0.30),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "spike_ridge"],
		},
	},
	"Copper Dragon Adult": {
		"max_health": 184, "armor_class": 18, "damage_amount": 7.5, "element_type": "none",
		"strength": 6.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 440,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Acid Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Bronze Dragon Adult": {
		"max_health": 212, "armor_class": 19, "damage_amount": 7.5, "element_type": "storm",
		"strength": 7.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 460,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Lightning Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge sea-dragon: weathered bronze scales, ridged frill of horns, sea-green eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.30,
			"palette.primary": Color(0.65, 0.45, 0.18),    # weathered bronze
			"palette.secondary": Color(0.42, 0.28, 0.10),
			"palette.accent": Color(0.40, 0.78, 0.72),     # sea-green patina
			"palette.eye": Color(0.30, 0.85, 0.75),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "spike_ridge"],
		},
	},
	"Green Dragon Adult": {
		"max_health": 207, "armor_class": 19, "damage_amount": 7.5, "element_type": "none",
		"strength": 6.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 455,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Poison Breath", "Fly", "Legendary Resistance", "Frightful Presence", "Amphibious"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge forest dragon: emerald-jade scales, antler-horns, golden cunning eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.30,
			"palette.primary": Color(0.18, 0.42, 0.20),    # jade green
			"palette.secondary": Color(0.10, 0.25, 0.10),
			"palette.accent": Color(0.65, 0.85, 0.32),
			"palette.eye": Color(0.95, 0.78, 0.20),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "spike_ridge"],
		},
	},
	"Silver Dragon Adult": {
		"max_health": 243, "armor_class": 19, "damage_amount": 8.0, "element_type": "ice",
		"strength": 8.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 5.0,
		"gold_value": 490,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Frost Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge: polished silver-mirror scales, frill of curved horns, frost-blue eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.35,
			"palette.primary": Color(0.82, 0.85, 0.92),    # polished silver
			"palette.secondary": Color(0.55, 0.60, 0.68),
			"palette.accent": Color(0.95, 0.97, 1.0),
			"palette.eye": Color(0.65, 0.92, 1.0),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "crystal_growth"],
		},
	},
	"Blue Dragon Adult": {
		"max_health": 225, "armor_class": 19, "damage_amount": 8.0, "element_type": "storm",
		"strength": 7.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 485,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Lightning Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge: deep azure scales, single massive horn on snout, lightning-blue accents.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.35,
			"palette.primary": Color(0.18, 0.32, 0.68),    # deep azure
			"palette.secondary": Color(0.10, 0.18, 0.42),
			"palette.accent": Color(0.40, 0.85, 1.0),      # lightning crackle
			"palette.eye": Color(0.92, 0.95, 0.30),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "spike_ridge"],
		},
	},
	"Gold Dragon Adult": {
		"max_health": 256, "armor_class": 19, "damage_amount": 8.5, "element_type": "fire",
		"strength": 8.0, "dexterity": 2.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 7.0,
		"gold_value": 525,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Weakening Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge majestic gold dragon: brilliant gold scales, regal mane of horns, halo glow.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.45,
			"palette.primary": Color(0.95, 0.75, 0.20),    # brilliant gold
			"palette.secondary": Color(0.65, 0.45, 0.08),
			"palette.accent": Color(1.0, 0.95, 0.55),
			"palette.eye": Color(1.0, 0.95, 0.30),
			"face.eye_glow": true,
			"ornaments.tags": ["tail", "wings", "horns", "halo"],
		},
	},
	"Red Dragon Adult": {
		"max_health": 256, "armor_class": 19, "damage_amount": 8.5, "element_type": "fire",
		"strength": 8.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 5.0,
		"gold_value": 520,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
		# Hornbound — Huge: crimson scales, smoldering gold belly, massive horns, ember-glow eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 2.40,
			"palette.primary": Color(0.65, 0.10, 0.05),    # crimson scales
			"palette.secondary": Color(0.35, 0.04, 0.02),  # deeper red shadow
			"palette.accent": Color(0.95, 0.78, 0.25),     # gold belly / ember
			"palette.eye": Color(1.0, 0.85, 0.15),
			"face.eye_glow": true,
			"face.eye_radius": 0.080,
			"ornaments.tags": ["tail", "wings", "horns", "spike_ridge"],
		},
	},
	"Dragon Turtle": {
		"max_health": 341, "armor_class": 20, "damage_amount": 8.5, "element_type": "none",
		"strength": 7.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 510,
		"weapons": ["Bite", "Claws", "Tail"],
		"abilities": ["Steam Breath", "Amphibious"],
		"armor": ["Natural Armor"],
	},
	"White Dragon Ancient": {
		"max_health": 333, "armor_class": 20, "damage_amount": 9.5, "element_type": "ice",
		"strength": 8.0, "dexterity": 0.0, "constitution": 8.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 700,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Frost Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Brass Dragon Ancient": {
		"max_health": 297, "armor_class": 20, "damage_amount": 9.5, "element_type": "fire",
		"strength": 8.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 700,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Black Dragon Ancient": {
		"max_health": 367, "armor_class": 22, "damage_amount": 10.0, "element_type": "none",
		"strength": 8.0, "dexterity": 2.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 735,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Acid Breath", "Fly", "Legendary Resistance", "Frightful Presence", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Copper Dragon Ancient": {
		"max_health": 350, "armor_class": 21, "damage_amount": 10.0, "element_type": "none",
		"strength": 8.0, "dexterity": 1.0, "constitution": 7.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 740,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Acid Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Green Dragon Ancient": {
		"max_health": 385, "armor_class": 21, "damage_amount": 10.5, "element_type": "none",
		"strength": 8.0, "dexterity": 1.0, "constitution": 7.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 760,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Poison Breath", "Fly", "Legendary Resistance", "Frightful Presence", "Amphibious"],
		"armor": ["Dragon Scales"],
	},
	"Bronze Dragon Ancient": {
		"max_health": 444, "armor_class": 22, "damage_amount": 10.5, "element_type": "storm",
		"strength": 9.0, "dexterity": 0.0, "constitution": 8.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 5.0,
		"gold_value": 765,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Lightning Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Silver Dragon Ancient": {
		"max_health": 487, "armor_class": 22, "damage_amount": 11.0, "element_type": "ice",
		"strength": 10.0, "dexterity": 0.0, "constitution": 9.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 6.0,
		"gold_value": 790,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Frost Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Blue Dragon Ancient": {
		"max_health": 481, "armor_class": 22, "damage_amount": 11.0, "element_type": "storm",
		"strength": 9.0, "dexterity": 0.0, "constitution": 8.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 5.0,
		"gold_value": 785,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Lightning Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Jabberwock": {
		"max_health": 310, "armor_class": 18, "damage_amount": 11.0, "element_type": "none",
		"strength": 8.0, "dexterity": 2.0, "constitution": 6.0, "intelligence": -3.0, "wisdom": 2.0, "charisma": 5.0,
		"gold_value": 800,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Vorpal Jaws", "Fly", "Frightful Presence", "Legendary Resistance"],
		"armor": ["Natural Armor"],
	},
	"Gold Dragon Ancient": {
		"max_health": 546, "armor_class": 22, "damage_amount": 11.5, "element_type": "fire",
		"strength": 10.0, "dexterity": 2.0, "constitution": 9.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 8.0,
		"gold_value": 825,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Weakening Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Red Dragon Ancient": {
		"max_health": 546, "armor_class": 22, "damage_amount": 11.5, "element_type": "fire",
		"strength": 10.0, "dexterity": 0.0, "constitution": 9.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 6.0,
		"gold_value": 820,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Fly", "Legendary Resistance", "Frightful Presence"],
		"armor": ["Dragon Scales"],
	},
	"Tiamat": {
		"max_health": 615, "armor_class": 25, "damage_amount": 15.0, "element_type": "fire",
		"strength": 10.0, "dexterity": 0.0, "constitution": 10.0, "intelligence": 8.0, "wisdom": 8.0, "charisma": 8.0,
		"gold_value": 3000,
		"weapons": ["Claw", "Bite", "Tail Swipe"],
		"abilities": ["Fire Breath", "Frost Breath", "Acid Breath", "Lightning Breath", "Poison Breath", "Fly", "Legendary Resistance", "Divine Presence"],
		"armor": ["Dragon Scales"],
	},
}
