const DATA: Dictionary = {
	"Fireworm": {
		"max_health": 22, "armor_class": 12, "damage_amount": 2.5, "element_type": "fire",
		"strength": 1.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 55,
		"weapons": ["Flame Bite", "Constrict"],
		"abilities": ["Fire Spit", "Burrow"],
		"armor": ["Fire Scales"],
	},
	"Iceworm": {
		"max_health": 22, "armor_class": 12, "damage_amount": 2.5, "element_type": "ice",
		"strength": 1.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 55,
		"weapons": ["Frost Bite", "Constrict"],
		"abilities": ["Freeze Spit", "Burrow"],
		"armor": ["Ice Scales"],
	},
	"Dust Mephit": {
		"max_health": 17, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Claws"],
		"abilities": ["Death Burst", "Blinding Breath"],
		"armor": ["Natural Armor"],
	},
	"Ice Mephit": {
		"max_health": 21, "armor_class": 11, "damage_amount": 1.0, "element_type": "ice",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 20,
		"weapons": ["Claws"],
		"abilities": ["Death Burst", "Frost Breath"],
		"armor": ["Natural Armor"],
	},
	"Magma Mephit": {
		"max_health": 22, "armor_class": 11, "damage_amount": 1.0, "element_type": "fire",
		"strength": -1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Claws"],
		"abilities": ["Death Burst", "Fire Breath", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Mud Mephit": {
		"max_health": 27, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": -1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 20,
		"weapons": ["Fists"],
		"abilities": ["Death Burst", "Mud Breath", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Smoke Mephit": {
		"max_health": 22, "armor_class": 12, "damage_amount": 1.0, "element_type": "fire",
		"strength": -2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Claws"],
		"abilities": ["Death Burst", "Cinder Breath", "Invisibility"],
		"armor": ["Natural Armor"],
	},
	"Steam Mephit": {
		"max_health": 21, "armor_class": 10, "damage_amount": 1.0, "element_type": "fire",
		"strength": -3.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 20,
		"weapons": ["Claws"],
		"abilities": ["Death Burst", "Steam Breath"],
		"armor": ["Natural Armor"],
	},
	"Magmin": {
		"max_health": 9, "armor_class": 14, "damage_amount": 1.0, "element_type": "fire",
		"strength": -2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 25,
		"weapons": ["Burning Touch"],
		"abilities": ["Death Burst", "Fiery Aura"],
		"armor": ["Natural Armor"],
	},
	"Fire Snake": {
		"max_health": 22, "armor_class": 14, "damage_amount": 1.5, "element_type": "fire",
		"strength": 1.0, "dexterity": 4.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 35,
		"weapons": ["Bite"],
		"abilities": ["Heated Body"],
		"armor": ["Natural Armor"],
	},
	"Thoqqua": {
		"max_health": 22, "armor_class": 15, "damage_amount": 1.5, "element_type": "fire",
		"strength": 2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 35,
		"weapons": ["Slam"],
		"abilities": ["Heated Body"],
		"armor": ["Natural Armor"],
	},
	"Azer": {
		"max_health": 39, "armor_class": 17, "damage_amount": 2.0, "element_type": "fire",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 65,
		"weapons": ["Warhammer"],
		"abilities": ["Heated Body", "Heated Weapons", "Illumination"],
		"armor": ["Natural Armor"],
	},
	"Gargoyle": {
		"max_health": 52, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 70,
		"weapons": ["Bite", "Claws", "Horn"],
		"abilities": ["False Appearance", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Water Weird": {
		"max_health": 58, "armor_class": 13, "damage_amount": 2.5, "element_type": "ice",
		"strength": 3.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 95,
		"weapons": ["Constrict"],
		"abilities": ["Invisible in Water", "Water Bound"],
		"armor": ["Natural Armor"],
	},
	"Air Elemental": {
		"max_health": 90, "armor_class": 15, "damage_amount": 4.0, "element_type": "storm",
		"strength": 2.0, "dexterity": 5.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 160,
		"weapons": ["Slam"],
		"abilities": ["Air Form", "Whirlwind"],
		"armor": ["Natural Armor"],
	},
	"Earth Elemental": {
		"max_health": 126, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 160,
		"weapons": ["Slam"],
		"abilities": ["Earth Glide", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Fire Elemental": {
		"max_health": 102, "armor_class": 13, "damage_amount": 4.0, "element_type": "fire",
		"strength": 0.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 160,
		"weapons": ["Touch"],
		"abilities": ["Fire Form", "Illumination"],
		"armor": ["Natural Armor"],
	},
	"Water Elemental": {
		"max_health": 114, "armor_class": 14, "damage_amount": 4.0, "element_type": "ice",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 160,
		"weapons": ["Slam"],
		"abilities": ["Water Form", "Freeze"],
		"armor": ["Natural Armor"],
	},
	"Salamander": {
		"max_health": 90, "armor_class": 15, "damage_amount": 4.0, "element_type": "fire",
		"strength": 4.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 165,
		"weapons": ["Spear", "Tail"],
		"abilities": ["Heated Body", "Heated Weapons"],
		"armor": ["Natural Armor"],
	},
	"Xorn": {
		"max_health": 73, "armor_class": 19, "damage_amount": 4.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 165,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Earth Glide", "Treasure Sense"],
		"armor": ["Natural Armor"],
	},
	"Galeb Duhr": {
		"max_health": 85, "armor_class": 16, "damage_amount": 4.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 190,
		"weapons": ["Slam"],
		"abilities": ["False Appearance", "Rolling Charge", "Animate Boulders"],
		"armor": ["Natural Armor"],
	},
	"Invisible Stalker": {
		"max_health": 104, "armor_class": 14, "damage_amount": 4.5, "element_type": "storm",
		"strength": 3.0, "dexterity": 4.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 195,
		"weapons": ["Slam"],
		"abilities": ["Invisibility", "Faultless Tracker"],
		"armor": ["Natural Armor"],
	},
	"Air Elemental Myrmidon": {
		"max_health": 117, "armor_class": 18, "damage_amount": 5.0, "element_type": "storm",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 230,
		"weapons": ["Flail"],
		"abilities": ["Whirlwind Strike", "Fly"],
		"armor": ["Half Plate"],
	},
	"Earth Elemental Myrmidon": {
		"max_health": 127, "armor_class": 18, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 230,
		"weapons": ["Maul"],
		"abilities": ["Magic Weapons", "Earth Shaker"],
		"armor": ["Half Plate"],
	},
	"Fire Elemental Myrmidon": {
		"max_health": 117, "armor_class": 18, "damage_amount": 5.0, "element_type": "fire",
		"strength": 1.0, "dexterity": 4.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 230,
		"weapons": ["Scimitar"],
		"abilities": ["Heated Weapons", "Blazing Presence"],
		"armor": ["Half Plate"],
	},
	"Water Elemental Myrmidon": {
		"max_health": 127, "armor_class": 18, "damage_amount": 5.0, "element_type": "ice",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 230,
		"weapons": ["Trident"],
		"abilities": ["Amphibious", "Watery Strikes"],
		"armor": ["Half Plate"],
	},
	"Dao": {
		"max_health": 187, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 6.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 340,
		"weapons": ["Maul"],
		"abilities": ["Earth Glide", "Elemental Demise", "Sure-Footed"],
		"armor": ["Natural Armor"],
	},
	"Djinni": {
		"max_health": 161, "armor_class": 17, "damage_amount": 6.0, "element_type": "storm",
		"strength": 5.0, "dexterity": 2.0, "constitution": 6.0, "intelligence": 2.0, "wisdom": 3.0, "charisma": 5.0,
		"gold_value": 350,
		"weapons": ["Scimitar"],
		"abilities": ["Whirlwind", "Elemental Demise", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Efreeti": {
		"max_health": 200, "armor_class": 17, "damage_amount": 6.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 1.0, "constitution": 7.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 355,
		"weapons": ["Scimitar"],
		"abilities": ["Fire Immunity", "Elemental Demise", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Marid": {
		"max_health": 229, "armor_class": 17, "damage_amount": 6.0, "element_type": "ice",
		"strength": 6.0, "dexterity": 1.0, "constitution": 8.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 360,
		"weapons": ["Trident"],
		"abilities": ["Amphibious", "Water Mastery", "Elemental Demise", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Phoenix": {
		"max_health": 175, "armor_class": 18, "damage_amount": 8.0, "element_type": "fire",
		"strength": 4.0, "dexterity": 8.0, "constitution": 5.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": 4.0,
		"gold_value": 510,
		"weapons": ["Talons"],
		"abilities": ["Fire Form", "Legendary Resistance", "Fiery Death and Rebirth", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Leviathan": {
		"max_health": 328, "armor_class": 17, "damage_amount": 9.5, "element_type": "ice",
		"strength": 10.0, "dexterity": 2.0, "constitution": 10.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 670,
		"weapons": ["Bite", "Tail"],
		"abilities": ["Amphibious", "Siege Monster", "Legendary Resistance", "Tidal Wave"],
		"armor": ["Natural Armor"],
	},
	"Zaratan": {
		"max_health": 312, "armor_class": 21, "damage_amount": 10.5, "element_type": "none",
		"strength": 10.0, "dexterity": -2.0, "constitution": 10.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 760,
		"weapons": ["Bite", "Stomp"],
		"abilities": ["Amphibious", "Siege Monster", "Legendary Resistance"],
		"armor": ["Natural Armor"],
	},
	"Elder Tempest": {
		"max_health": 174, "armor_class": 14, "damage_amount": 11.0, "element_type": "storm",
		"strength": 6.0, "dexterity": 4.0, "constitution": 5.0, "intelligence": -5.0, "wisdom": 2.0, "charisma": -3.0,
		"gold_value": 820,
		"weapons": ["Slam"],
		"abilities": ["Fly", "Storm Aura", "Legendary Resistance"],
		"armor": ["Natural Armor"],
	},
}
