const DATA: Dictionary = {
	"Boggle": {
		"max_health": 18, "armor_class": 14, "damage_amount": 0.25, "element_type": "none",
		"strength": -1.0, "dexterity": 4.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Claws"],
		"abilities": ["Slippery", "Oil Puddle"],
		"armor": ["Natural Armor"],
	},
	"Blink Dog": {
		"max_health": 22, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Bite"],
		"abilities": ["Teleport", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Pixie": {
		"max_health": 1, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": 5.0, "constitution": -1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 15,
		"weapons": ["Longsword"],
		"abilities": ["Superior Invisibility", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
		# Hornbound
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 0.35,
			"palette.primary": Color(0.95, 0.85, 0.95),  # Pale fairy
			"palette.accent": Color(1.0, 0.65, 0.85),
			"face.eye_glow": true,
		},
	},
	"Sprite": {
		"max_health": 2, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": 4.0, "constitution": 0.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Longsword", "Shortbow"],
		"abilities": ["Heart Sight", "Superior Invisibility"],
		"armor": ["Leather Armor"],
	},
	"Satyr": {
		"max_health": 31, "armor_class": 14, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 25,
		"weapons": ["Ram", "Shortsword"],
		"abilities": ["Magic Resistance"],
		"armor": ["Natural Armor"],
		# Hornbound — half-human half-goat: tanned olive skin upper, shaggy brown goat legs,
		# curling ram-horns, golden mischievous eyes.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 1.00,
			"palette.primary": Color(0.78, 0.62, 0.42),    # tanned skin
			"palette.secondary": Color(0.45, 0.28, 0.15),  # goat-leg fur
			"palette.accent": Color(0.92, 0.78, 0.42),     # golden ram horns
			"palette.eye": Color(0.95, 0.78, 0.18),
			"ornaments.tags": ["horns", "tail"],
		},
	},
	"Darkling": {
		"max_health": 13, "armor_class": 14, "damage_amount": 1.0, "element_type": "shadow",
		"strength": -1.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 25,
		"weapons": ["Dagger"],
		"abilities": ["Death Flash", "Light Sensitivity"],
		"armor": ["Leather Armor"],
	},
	"Dryad": {
		"max_health": 22, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 5.0,
		"gold_value": 35,
		"weapons": ["Club"],
		"abilities": ["Speak with Beasts and Plants", "Tree Stride", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
		# Hornbound — tree spirit: wood-brown skin patterned with bark, green leafy hair,
		# flowers crowning the head, soft glowing forest-green eyes.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 0.95,
			"palette.primary": Color(0.55, 0.42, 0.25),    # wood-brown skin
			"palette.secondary": Color(0.30, 0.48, 0.20),  # leafy hair
			"palette.accent": Color(0.95, 0.50, 0.78),     # pink blossoms
			"palette.eye": Color(0.50, 0.92, 0.45),
			"face.eye_glow": true,
			"ornaments.tags": ["flowering_accents", "mane"],
		},
	},
	"Quickling": {
		"max_health": 10, "armor_class": 16, "damage_amount": 1.5, "element_type": "none",
		"strength": -3.0, "dexterity": 6.0, "constitution": -1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 40,
		"weapons": ["Dagger"],
		"abilities": ["Blur", "Evasion", "Speedy"],
		"armor": ["Natural Armor"],
	},
	"Centaur": {
		"max_health": 45, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 60,
		"weapons": ["Pike", "Hooves"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Darkling Elder": {
		"max_health": 27, "armor_class": 15, "damage_amount": 2.0, "element_type": "shadow",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 65,
		"weapons": ["Shortsword"],
		"abilities": ["Death Flash", "Darkness", "Light Sensitivity"],
		"armor": ["Leather Armor"],
	},
	"Meenlock": {
		"max_health": 31, "armor_class": 13, "damage_amount": 2.0, "element_type": "shadow",
		"strength": -2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Claws"],
		"abilities": ["Fear Aura", "Shadow Teleportation"],
		"armor": ["Natural Armor"],
	},
	"Sea Hag": {
		"max_health": 52, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 70,
		"weapons": ["Claws"],
		"abilities": ["Death Glare", "Horrific Appearance", "Shared Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Green Hag": {
		"max_health": 82, "armor_class": 17, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 100,
		"weapons": ["Claws"],
		"abilities": ["Mimicry", "Invisible Passage", "Innate Spellcasting", "Shared Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Redcap": {
		"max_health": 45, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 105,
		"weapons": ["Sickle", "Boots"],
		"abilities": ["Blood Frenzy", "Iron Boots"],
		"armor": ["Natural Armor"],
	},
	"Yeth Hound": {
		"max_health": 51, "armor_class": 14, "damage_amount": 3.5, "element_type": "shadow",
		"strength": 4.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 140,
		"weapons": ["Bite"],
		"abilities": ["Baleful Baying", "Sunlight Banishment", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Annis Hag": {
		"max_health": 75, "armor_class": 17, "damage_amount": 4.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Iron Token", "Change Shape", "Shared Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Korred": {
		"max_health": 93, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": 0.0,
		"gold_value": 235,
		"weapons": ["Club"],
		"abilities": ["Hair Snare", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Bheur Hag": {
		"max_health": 45, "armor_class": 17, "damage_amount": 5.0, "element_type": "ice",
		"strength": 1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 240,
		"weapons": ["Claws", "Graystaff"],
		"abilities": ["Graystaff Magic", "Ride the Wind", "Shared Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Autumn Eladrin": {
		"max_health": 127, "armor_class": 19, "damage_amount": 6.0, "element_type": "none",
		"strength": 1.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 330,
		"weapons": ["Longsword"],
		"abilities": ["Fey Step", "Sorrowful Presence", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Spring Eladrin": {
		"max_health": 127, "armor_class": 19, "damage_amount": 6.0, "element_type": "none",
		"strength": 1.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 330,
		"weapons": ["Longsword"],
		"abilities": ["Fey Step", "Joyful Presence", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Summer Eladrin": {
		"max_health": 127, "armor_class": 19, "damage_amount": 6.0, "element_type": "fire",
		"strength": 4.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 4.0,
		"gold_value": 330,
		"weapons": ["Longsword"],
		"abilities": ["Fey Step", "Fearsome Presence", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Winter Eladrin": {
		"max_health": 127, "armor_class": 19, "damage_amount": 7.0, "element_type": "ice",
		"strength": 0.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 415,
		"weapons": ["Longsword"],
		"abilities": ["Fey Step", "Mournful Presence", "Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
}
