const DATA: Dictionary = {
	"Lemure": {
		"max_health": 13, "armor_class": 7, "damage_amount": 0.25, "element_type": "fire",
		"strength": 0.0, "dexterity": -3.0, "constitution": 0.0, "intelligence": -5.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 5,
		"weapons": ["Fist"],
		"abilities": ["Devil's Sight", "Hellfire Vulnerability"],
		"armor": ["Natural Armor"],
	},
	"Manes": {
		"max_health": 9, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": -1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 8,
		"weapons": ["Claws"],
		"abilities": ["Death Throes"],
		"armor": ["Natural Armor"],
	},
	"Dretch": {
		"max_health": 18, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Fetid Cloud"],
		"armor": ["Natural Armor"],
	},
	"Imp": {
		"max_health": 10, "armor_class": 13, "damage_amount": 1.5, "element_type": "fire",
		"strength": -2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 30,
		"weapons": ["Sting"],
		"abilities": ["Devil's Sight", "Magic Resistance", "Shapechanger", "Invisibility"],
		"armor": ["Natural Armor"],
	},
	"Quasit": {
		"max_health": 7, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": -3.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 30,
		"weapons": ["Claws"],
		"abilities": ["Magic Resistance", "Shapechanger", "Invisibility"],
		"armor": ["Natural Armor"],
	},
	"Spined Devil": {
		"max_health": 22, "armor_class": 13, "damage_amount": 2.0, "element_type": "fire",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Fork"],
		"abilities": ["Flyby", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Bearded Devil": {
		"max_health": 52, "armor_class": 13, "damage_amount": 2.5, "element_type": "fire",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Glaive", "Beard"],
		"abilities": ["Magic Resistance", "Steadfast"],
		"armor": ["Natural Armor"],
	},
	"Hell Hound": {
		"max_health": 45, "armor_class": 15, "damage_amount": 2.5, "element_type": "fire",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 95,
		"weapons": ["Bite"],
		"abilities": ["Fire Breath", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Barghest": {
		"max_health": 90, "armor_class": 17, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 130,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Feed", "Shapechanger", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Shadow Demon": {
		"max_health": 66, "armor_class": 13, "damage_amount": 3.5, "element_type": "shadow",
		"strength": -5.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 130,
		"weapons": ["Claws"],
		"abilities": ["Amorphous", "Shadow Stealth", "Vulnerability to Radiance"],
		"armor": ["Natural Armor"],
	},
	"Succubus": {
		"max_health": 82, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": -1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 5.0,
		"gold_value": 130,
		"weapons": ["Claw"],
		"abilities": ["Shapechanger", "Draining Kiss", "Etherealness", "Charm"],
		"armor": ["Natural Armor"],
	},
	"Babau": {
		"max_health": 82, "armor_class": 16, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 130,
		"weapons": ["Spear", "Claws"],
		"abilities": ["Weakening Gaze", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Barbed Devil": {
		"max_health": 110, "armor_class": 15, "damage_amount": 4.0, "element_type": "fire",
		"strength": 3.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 165,
		"weapons": ["Tail", "Claws"],
		"abilities": ["Barbed Hide", "Magic Resistance", "Steadfast"],
		"armor": ["Natural Armor"],
	},
	"Barlgura": {
		"max_health": 68, "armor_class": 15, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 165,
		"weapons": ["Fist", "Bite"],
		"abilities": ["Reckless", "Running Leap", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Cambion": {
		"max_health": 82, "armor_class": 19, "damage_amount": 4.0, "element_type": "fire",
		"strength": 4.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 170,
		"weapons": ["Spear"],
		"abilities": ["Magic Resistance", "Fly", "Fiendish Blessing"],
		"armor": ["Natural Armor"],
	},
	"Mezzoloth": {
		"max_health": 75, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 165,
		"weapons": ["Trident"],
		"abilities": ["Magic Resistance", "Magic Weapons", "Teleport"],
		"armor": ["Natural Armor"],
	},
	"Night Hag": {
		"max_health": 112, "armor_class": 17, "damage_amount": 4.0, "element_type": "shadow",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 170,
		"weapons": ["Claws"],
		"abilities": ["Nightmare Haunting", "Magic Resistance", "Heartstone", "Etherealness"],
		"armor": ["Natural Armor"],
	},
	"Chasme": {
		"max_health": 84, "armor_class": 15, "damage_amount": 4.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 195,
		"weapons": ["Proboscis"],
		"abilities": ["Drone", "Fly", "Magic Resistance"],
		"armor": ["Natural Armor"],
	},
	"Vrock": {
		"max_health": 104, "armor_class": 15, "damage_amount": 4.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 195,
		"weapons": ["Talons", "Beak"],
		"abilities": ["Magic Resistance", "Spores", "Stunning Screech", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Chain Devil": {
		"max_health": 85, "armor_class": 16, "damage_amount": 5.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 265,
		"weapons": ["Chain"],
		"abilities": ["Magic Resistance", "Unnerving Mask", "Animate Chains"],
		"armor": ["Natural Armor"],
	},
	"Hezrou": {
		"max_health": 136, "armor_class": 16, "damage_amount": 5.5, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 265,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Magic Resistance", "Stench"],
		"armor": ["Natural Armor"],
	},
	"Bone Devil": {
		"max_health": 142, "armor_class": 19, "damage_amount": 5.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 285,
		"weapons": ["Claw", "Sting"],
		"abilities": ["Devil's Sight", "Magic Resistance", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Glabrezu": {
		"max_health": 157, "armor_class": 17, "damage_amount": 5.5, "element_type": "none",
		"strength": 5.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 290,
		"weapons": ["Pincer", "Fist"],
		"abilities": ["Magic Resistance", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Nycaloth": {
		"max_health": 123, "armor_class": 18, "damage_amount": 5.5, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 290,
		"weapons": ["Greataxe", "Claw"],
		"abilities": ["Fly", "Magic Resistance", "Magic Weapons", "Teleport"],
		"armor": ["Natural Armor"],
	},
	"Horned Devil": {
		"max_health": 148, "armor_class": 18, "damage_amount": 6.0, "element_type": "fire",
		"strength": 6.0, "dexterity": 3.0, "constitution": 5.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 340,
		"weapons": ["Fork", "Tail"],
		"abilities": ["Magic Resistance", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Erinyes": {
		"max_health": 153, "armor_class": 18, "damage_amount": 6.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 380,
		"weapons": ["Longsword", "Longbow"],
		"abilities": ["Magic Resistance", "Fly", "Poisoned Arrow"],
		"armor": ["Plate Armor"],
	},
	"Arcanaloth": {
		"max_health": 104, "armor_class": 17, "damage_amount": 6.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 380,
		"weapons": ["Claws"],
		"abilities": ["Magic Resistance", "Magic Weapons", "Innate Spellcasting", "Shapechanger"],
		"armor": ["Natural Armor"],
	},
	"Ice Devil": {
		"max_health": 180, "armor_class": 18, "damage_amount": 7.5, "element_type": "ice",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 440,
		"weapons": ["Claws", "Tail", "Ice Spear"],
		"abilities": ["Devil's Sight", "Magic Resistance", "Wall of Ice"],
		"armor": ["Natural Armor"],
	},
	"Nalfeshnee": {
		"max_health": 184, "armor_class": 16, "damage_amount": 7.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 4.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 410,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Magic Resistance", "Innate Spellcasting", "Horrid Touch"],
		"armor": ["Natural Armor"],
	},
	"Rakshasa": {
		"max_health": 110, "armor_class": 16, "damage_amount": 7.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 5.0,
		"gold_value": 415,
		"weapons": ["Claws"],
		"abilities": ["Limited Magic Immunity", "Innate Spellcasting", "Shapechanger"],
		"armor": ["Natural Armor"],
	},
	"Ultroloth": {
		"max_health": 153, "armor_class": 19, "damage_amount": 7.0, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 415,
		"weapons": ["Longsword"],
		"abilities": ["Magic Resistance", "Innate Spellcasting", "Hypnotic Gaze", "Teleport"],
		"armor": ["Natural Armor"],
	},
	"Marilith": {
		"max_health": 189, "armor_class": 18, "damage_amount": 8.0, "element_type": "none",
		"strength": 4.0, "dexterity": 5.0, "constitution": 5.0, "intelligence": 4.0, "wisdom": 3.0, "charisma": 5.0,
		"gold_value": 510,
		"weapons": ["Longsword", "Tail"],
		"abilities": ["Magic Resistance", "Magic Weapons", "Reactive"],
		"armor": ["Natural Armor"],
	},
	"Goristro": {
		"max_health": 310, "armor_class": 19, "damage_amount": 8.5, "element_type": "none",
		"strength": 7.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 525,
		"weapons": ["Fist", "Gore", "Hooves"],
		"abilities": ["Magic Resistance", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Balor": {
		"max_health": 262, "armor_class": 19, "damage_amount": 9.0, "element_type": "fire",
		"strength": 8.0, "dexterity": 2.0, "constitution": 7.0, "intelligence": 5.0, "wisdom": 2.0, "charisma": 6.0,
		"gold_value": 670,
		"weapons": ["Longsword", "Whip"],
		"abilities": ["Fire Aura", "Magic Resistance", "Magic Weapons", "Fly", "Death Throes"],
		"armor": ["Natural Armor"],
	},
	"Pit Fiend": {
		"max_health": 300, "armor_class": 19, "damage_amount": 9.5, "element_type": "fire",
		"strength": 8.0, "dexterity": 2.0, "constitution": 7.0, "intelligence": 6.0, "wisdom": 4.0, "charisma": 7.0,
		"gold_value": 700,
		"weapons": ["Bite", "Claw", "Mace", "Tail"],
		"abilities": ["Aura of Fear", "Magic Resistance", "Magic Weapons", "Innate Spellcasting", "Fly"],
		"armor": ["Natural Armor"],
	},
}
