const DATA: Dictionary = {
	"Ogre": {
		"max_health": 59, "armor_class": 11, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 90,
		"weapons": ["Greatclub", "Javelin"],
		"abilities": ["Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Troll": {
		"max_health": 84, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 130,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Regeneration", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Firbolg": {
		"max_health": 52, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 3.0, "charisma": 0.0,
		"gold_value": 95,
		"weapons": ["Greatclub", "Longbow"],
		"abilities": ["Magic Resistance", "Hidden Step", "Detect Magic", "Disguise Self"],
		"armor": ["Natural Armor"],
	},
	"Ettin": {
		"max_health": 85, "armor_class": 12, "damage_amount": 3.5, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 130,
		"weapons": ["Battleaxe", "Morningstar"],
		"abilities": ["Two Heads", "Wakeful"],
		"armor": ["Natural Armor"],
	},
	"Verbeeg": {
		"max_health": 92, "armor_class": 13, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 130,
		"weapons": ["Spear"],
		"abilities": ["Cunning Action"],
		"armor": ["Natural Armor"],
	},
	"Hill Giant": {
		"max_health": 105, "armor_class": 13, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 165,
		"weapons": ["Greatclub", "Rock"],
		"abilities": ["Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Cyclops": {
		"max_health": 138, "armor_class": 14, "damage_amount": 4.5, "element_type": "none",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": -1.0, "charisma": -2.0,
		"gold_value": 195,
		"weapons": ["Greatclub", "Rock"],
		"abilities": ["Poor Depth Perception", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Mouth of Grolantor": {
		"max_health": 114, "armor_class": 14, "damage_amount": 4.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": -3.0, "wisdom": -3.0, "charisma": -2.0,
		"gold_value": 195,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Hunger Frenzy"],
		"armor": ["Natural Armor"],
	},
	"Stone Giant": {
		"max_health": 126, "armor_class": 17, "damage_amount": 5.0, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 230,
		"weapons": ["Greatclub", "Rock"],
		"abilities": ["Stone Camouflage", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Oni": {
		"max_health": 110, "armor_class": 16, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 235,
		"weapons": ["Glaive", "Claws"],
		"abilities": ["Regeneration", "Magic Weapons", "Innate Spellcasting", "Shapechanger", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Venom Troll": {
		"max_health": 94, "armor_class": 15, "damage_amount": 5.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": -2.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 235,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Regeneration", "Venom Splash", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Fomorian": {
		"max_health": 149, "armor_class": 14, "damage_amount": 5.5, "element_type": "none",
		"strength": 6.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": -2.0,
		"gold_value": 265,
		"weapons": ["Greatclub"],
		"abilities": ["Curse Gaze", "Evil Eye"],
		"armor": ["Natural Armor"],
	},
	"Frost Giant": {
		"max_health": 138, "armor_class": 15, "damage_amount": 5.5, "element_type": "ice",
		"strength": 6.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 265,
		"weapons": ["Greataxe", "Rock"],
		"abilities": ["Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Fire Giant": {
		"max_health": 162, "armor_class": 18, "damage_amount": 5.5, "element_type": "fire",
		"strength": 7.0, "dexterity": -1.0, "constitution": 6.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 295,
		"weapons": ["Greatsword", "Rock"],
		"abilities": ["Siege Monster"],
		"armor": ["Plate Mail"],
	},
	"Cloud Giant": {
		"max_health": 200, "armor_class": 14, "damage_amount": 5.5, "element_type": "storm",
		"strength": 8.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 295,
		"weapons": ["Morningstar", "Rock"],
		"abilities": ["Keen Smell", "Innate Spellcasting", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Rot Troll": {
		"max_health": 138, "armor_class": 16, "damage_amount": 5.5, "element_type": "none",
		"strength": 6.0, "dexterity": 1.0, "constitution": 6.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 290,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Regeneration", "Rotting Presence", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Stone Giant Dreamwalker": {
		"max_health": 161, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 6.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": 2.0,
		"gold_value": 315,
		"weapons": ["Greatclub", "Rock"],
		"abilities": ["Siege Monster", "Dreamer Curse", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Spirit Troll": {
		"max_health": 97, "armor_class": 11, "damage_amount": 6.0, "element_type": "shadow",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 340,
		"weapons": ["Claw"],
		"abilities": ["Regeneration", "Incorporeal Movement", "Horrifying Visage"],
		"armor": ["Natural Armor"],
	},
	"Cloud Giant Smiling One": {
		"max_health": 262, "armor_class": 14, "damage_amount": 6.0, "element_type": "storm",
		"strength": 8.0, "dexterity": 0.0, "constitution": 6.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 345,
		"weapons": ["Morningstar", "Rock"],
		"abilities": ["Innate Spellcasting", "Keen Smell", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Storm Giant": {
		"max_health": 230, "armor_class": 16, "damage_amount": 7.0, "element_type": "storm",
		"strength": 9.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 415,
		"weapons": ["Greatsword", "Rock"],
		"abilities": ["Amphibious", "Innate Spellcasting", "Siege Monster", "Lightning Strike"],
		"armor": ["Natural Armor"],
	},
	"Storm Giant Quintessent": {
		"max_health": 230, "armor_class": 12, "damage_amount": 8.0, "element_type": "storm",
		"strength": 9.0, "dexterity": 2.0, "constitution": 5.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 510,
		"weapons": ["Greatsword"],
		"abilities": ["Amphibious", "Innate Spellcasting", "Air Form", "Lightning Touch"],
		"armor": ["Natural Armor"],
	},
}
