const DATA: Dictionary = {
	"Farmer": {
		"max_health": 8, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Pitchfork", "Scythe"],
		"abilities": ["Hard Work"],
		"armor": ["Cloth"],
	},
	"Knight": {
		"max_health": 52, "armor_class": 18, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 120,
		"weapons": ["Longsword", "Lance"],
		"abilities": ["Parry", "Rally"],
		"armor": ["Plate", "Shield"],
	},
	"Mage": {
		"max_health": 18, "armor_class": 12, "damage_amount": 4.0, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 5.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Staff", "Dagger"],
		"abilities": ["Fireball", "Shield", "Magic Missile"],
		"armor": ["Robes"],
	},
	"Ranger": {
		"max_health": 33, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 80,
		"weapons": ["Longbow", "Shortsword"],
		"abilities": ["Hunter's Mark", "Favored Enemy"],
		"armor": ["Leather", "Scale Mail"],
	},
	"Goblin": {
		"max_health": 7, "armor_class": 15, "damage_amount": 1.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.5, "constitution": 0.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Scimitar", "Shortbow"],
		"abilities": ["Nimble Escape"],
		"armor": ["Leather", "Shield"],
		"should_bob": false,
		"fixed_move_speed": 3.0,
		"ai_behaviors": ["nimble_escape"],
		"nimble_escape_disengage_range": 4.0,
		"nimble_escape_hide_range": 8.0,
		"faction": "GOBLINS",
		"hp_dice_count": 2,
		"hp_dice_sides": 6,
		"armor_pool": ["none", "leather", "chain shirt"],
		"weapon_pool": ["Dagger", "Scimitar", "Shortbow"],
		"ability_pool": ["nimble_escape", "redirect_attack"],
		"ammo_dice_count": 2,
		"ammo_dice_sides": 10,
	},
	"Kobold": {
		"max_health": 5, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -1.0, "wisdom": -2.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Dagger", "Sling"],
		"abilities": ["Pack Tactics", "Sunlight Sensitivity"],
		"armor": ["Leather"],
	},
	"Orc": {
		"max_health": 15, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": -1.0, "charisma": -1.0,
		"gold_value": 55,
		"weapons": ["Greataxe", "Javelin"],
		"abilities": ["Aggressive", "Relentless"],
		"armor": ["Hide", "Shield"],
	},
	"Gnoll": {
		"max_health": 22, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 50,
		"weapons": ["Bite", "Spear"],
		"abilities": ["Rampage"],
		"armor": ["Hide", "Shield"],
	},
	"Bugbear": {
		"max_health": 27, "armor_class": 16, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 70,
		"weapons": ["Morningstar", "Javelin"],
		"abilities": ["Brute", "Surprise Attack"],
		"armor": ["Hide", "Shield"],
	},
	"Merfolk": {
		"max_health": 11, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 8,
		"weapons": ["Spear"],
		"abilities": ["Amphibious"],
		"armor": ["Natural Armor"],
	},
	"Bandit": {
		"max_health": 11, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 10,
		"weapons": ["Scimitar", "Light Crossbow"],
		"abilities": [],
		"armor": ["Leather Armor"],
	},
	"Guard": {
		"max_health": 11, "armor_class": 16, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 10,
		"weapons": ["Spear"],
		"abilities": [],
		"armor": ["Chain Shirt"],
	},
	"Cultist": {
		"max_health": 9, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 8,
		"weapons": ["Scimitar"],
		"abilities": ["Dark Devotion"],
		"armor": ["Leather Armor"],
	},
	"Troglodyte": {
		"max_health": 13, "armor_class": 11, "damage_amount": 0.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Stench", "Sunlight Sensitivity"],
		"armor": ["Natural Armor"],
	},
	"Bullywug": {
		"max_health": 11, "armor_class": 15, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 10,
		"weapons": ["Quarterstaff", "Bite"],
		"abilities": ["Amphibious", "Standing Leap", "Speak with Frogs"],
		"armor": ["Natural Armor"],
	},
	"Kenku": {
		"max_health": 13, "armor_class": 13, "damage_amount": 0.5, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 10,
		"weapons": ["Shortsword", "Shortbow"],
		"abilities": ["Ambushers", "Mimicry"],
		"armor": ["Leather Armor"],
	},
	"Drow": {
		"max_health": 13, "armor_class": 15, "damage_amount": 0.5, "element_type": "shadow",
		"strength": 0.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 10,
		"weapons": ["Shortsword", "Hand Crossbow"],
		"abilities": ["Fey Ancestry", "Sunlight Sensitivity", "Innate Spellcasting"],
		"armor": ["Chain Shirt"],
	},
	"Thug": {
		"max_health": 32, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Mace", "Heavy Crossbow"],
		"abilities": ["Pack Tactics"],
		"armor": ["Leather Armor"],
	},
	"Scout": {
		"max_health": 16, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 20,
		"weapons": ["Shortsword", "Longbow"],
		"abilities": ["Keen Hearing and Sight"],
		"armor": ["Leather Armor"],
	},
	"Hobgoblin": {
		"max_health": 11, "armor_class": 18, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 20,
		"weapons": ["Longsword", "Longbow"],
		"abilities": ["Martial Advantage"],
		"armor": ["Chain Mail"],
	},
	"Lizardfolk": {
		"max_health": 22, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 20,
		"weapons": ["Bite", "Claws", "Javelin"],
		"abilities": ["Hold Breath"],
		"armor": ["Natural Armor"],
	},
	"Sahuagin": {
		"max_health": 22, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 20,
		"weapons": ["Claws", "Bite", "Spear"],
		"abilities": ["Blood Frenzy", "Shark Telepathy", "Limited Amphibiousness"],
		"armor": ["Natural Armor"],
	},
	"Deep Gnome": {
		"max_health": 16, "armor_class": 15, "damage_amount": 1.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 20,
		"weapons": ["War Pick", "Dart"],
		"abilities": ["Stone Camouflage", "Gnome Cunning"],
		"armor": ["Chain Shirt"],
	},
	"Goblin Boss": {
		"max_health": 21, "armor_class": 17, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": 0.0,
		"gold_value": 30,
		"weapons": ["Scimitar", "Javelin"],
		"abilities": ["Nimble Escape", "Redirect Attack"],
		"armor": ["Chain Shirt"],
	},
	"Spy": {
		"max_health": 27, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 30,
		"weapons": ["Shortsword", "Hand Crossbow"],
		"abilities": ["Cunning Action", "Sneak Attack"],
		"armor": ["Leather Armor"],
	},
	"Kobold Dragonshield": {
		"max_health": 44, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": -1.0, "wisdom": -1.0, "charisma": 0.0,
		"gold_value": 30,
		"weapons": ["Shortsword"],
		"abilities": ["Pack Tactics", "Heart of the Dragon"],
		"armor": ["Natural Armor"],
	},
	"Yuan-ti Pureblood": {
		"max_health": 40, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 35,
		"weapons": ["Scimitar", "Shortbow"],
		"abilities": ["Magic Resistance", "Innate Spellcasting", "Poison Immunity"],
		"armor": ["Natural Armor"],
	},
	"Bandit Captain": {
		"max_health": 65, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 60,
		"weapons": ["Scimitar", "Dagger"],
		"abilities": ["Multiattack"],
		"armor": ["Studded Leather"],
	},
	"Gnoll Pack Lord": {
		"max_health": 49, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Glaive", "Bite", "Flail"],
		"abilities": ["Rampage"],
		"armor": ["Chain Shirt"],
	},
	"Orc Eye of Gruumsh": {
		"max_health": 45, "armor_class": 16, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 60,
		"weapons": ["Spear", "Javelin"],
		"abilities": ["Aggressive", "Gruumsh's Fury", "Innate Spellcasting"],
		"armor": ["Chain Mail"],
	},
	"Priest": {
		"max_health": 27, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 1.0,
		"gold_value": 55,
		"weapons": ["Mace"],
		"abilities": ["Divine Eminence", "Spellcasting"],
		"armor": ["Chain Shirt"],
	},
	"Sahuagin Priestess": {
		"max_health": 33, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 60,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Blood Frenzy", "Shark Telepathy", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Lizardfolk Shaman": {
		"max_health": 27, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Hold Breath", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Hobgoblin Captain": {
		"max_health": 52, "armor_class": 17, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 95,
		"weapons": ["Greatsword", "Javelin"],
		"abilities": ["Martial Advantage"],
		"armor": ["Half Plate"],
	},
	"Bugbear Chief": {
		"max_health": 65, "armor_class": 17, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Morningstar", "Javelin"],
		"abilities": ["Brute", "Surprise Attack"],
		"armor": ["Chain Mail"],
	},
	"Veteran": {
		"max_health": 58, "armor_class": 17, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Longsword", "Shortsword", "Heavy Crossbow"],
		"abilities": ["Multiattack"],
		"armor": ["Splint Armor"],
	},
	"Gnoll Fang of Yeenoghu": {
		"max_health": 65, "armor_class": 14, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 130,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Rampage", "Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Lizardfolk King": {
		"max_health": 78, "armor_class": 15, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 130,
		"weapons": ["Trident", "Bite", "Claws"],
		"abilities": ["Hold Breath", "Spellcasting", "Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Orc War Chief": {
		"max_health": 93, "armor_class": 16, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 4.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Greataxe", "Javelin"],
		"abilities": ["Aggressive", "Gruumsh's Fury", "Battle Cry"],
		"armor": ["Plate Armor"],
	},
	"Drow Elite Warrior": {
		"max_health": 71, "armor_class": 18, "damage_amount": 4.0, "element_type": "shadow",
		"strength": 1.0, "dexterity": 4.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 165,
		"weapons": ["Shortsword", "Hand Crossbow"],
		"abilities": ["Fey Ancestry", "Sunlight Sensitivity", "Innate Spellcasting", "Parry"],
		"armor": ["Chain Mail"],
	},
	"Sahuagin Baron": {
		"max_health": 76, "armor_class": 16, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 165,
		"weapons": ["Claws", "Bite", "Trident"],
		"abilities": ["Blood Frenzy", "Shark Telepathy", "Multiattack"],
		"armor": ["Natural Armor"],
	},
	"Gladiator": {
		"max_health": 112, "armor_class": 16, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 165,
		"weapons": ["Spear", "Shield Bash"],
		"abilities": ["Brave", "Brute", "Parry"],
		"armor": ["Studded Leather"],
	},
	"Hobgoblin Warlord": {
		"max_health": 97, "armor_class": 20, "damage_amount": 4.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": 0.0, "charisma": 2.0,
		"gold_value": 200,
		"weapons": ["Longsword", "Longbow"],
		"abilities": ["Martial Advantage", "Leadership"],
		"armor": ["Plate Armor"],
	},
	"Drow Mage": {
		"max_health": 45, "armor_class": 12, "damage_amount": 5.0, "element_type": "shadow",
		"strength": -1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 230,
		"weapons": ["Staff of Striking"],
		"abilities": ["Fey Ancestry", "Sunlight Sensitivity", "Innate Spellcasting", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Drow Priestess of Lolth": {
		"max_health": 71, "armor_class": 16, "damage_amount": 5.5, "element_type": "shadow",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 265,
		"weapons": ["Scourge"],
		"abilities": ["Fey Ancestry", "Sunlight Sensitivity", "Innate Spellcasting", "Spellcasting"],
		"armor": ["Scale Mail"],
	},
	"Assassin": {
		"max_health": 78, "armor_class": 15, "damage_amount": 5.5, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 265,
		"weapons": ["Shortsword", "Light Crossbow"],
		"abilities": ["Assassinate", "Evasion", "Sneak Attack"],
		"armor": ["Studded Leather"],
	},
	"Archmage": {
		"max_health": 99, "armor_class": 12, "damage_amount": 6.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 5.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 385,
		"weapons": ["Dagger"],
		"abilities": ["Magic Resistance", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
}
