const DATA: Dictionary = {
	"Farmer": {
		"max_health": 8, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 15,
		"weapons": ["Pitchfork", "Scythe"],
		"abilities": ["Hard Work"],
		"armor": ["Cloth"],
	},
	"Knight": {
		"max_health": 52, "armor_class": 18, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 120,
		"weapons": ["Longsword", "Lance"],
		"abilities": ["Parry", "Rally"],
		"armor": ["Plate", "Shield"],
	},
	"Mage": {
		"max_health": 18, "armor_class": 12, "damage_amount": 4.0, "element_type": "none",
		"strength": -1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 5.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 100,
		"weapons": ["Staff", "Dagger"],
		"abilities": ["Fireball", "Shield", "Magic Missile"],
		"armor": ["Robes"],
	},
	"Ranger": {
		"max_health": 33, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 1.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 80,
		"weapons": ["Longbow", "Shortsword"],
		"abilities": ["Hunter's Mark", "Favored Enemy"],
		"armor": ["Leather", "Scale Mail"],
	},
	"Goblin": {
		"max_health": 7, "armor_class": 15, "damage_amount": 1.5, "element_type": "none",
		"strength": -1.0, "dexterity": 2.5, "constitution": 0.0, "intelligence": 0.0, "wisdom": -1.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Scimitar", "Shortbow"],
		"abilities": ["Nimble Escape"],
		"armor": ["Leather", "Shield"],
		"should_bob": false,
		"fixed_move_speed": 3.0,
		"ai_behaviors": ["nimble_escape"],
		"nimble_escape_disengage_range": 4.0,
		"nimble_escape_hide_range": 8.0,
		"faction": "GOBLINS",
		"hp_dice_count": 2,
		"hp_dice_sides": 6,
		"armor_pool": ["none", "leather", "chain shirt"],
		"weapon_pool": ["Dagger", "Scimitar", "Shortbow"],
		"ability_pool": ["nimble_escape", "redirect_attack"],
		"ammo_dice_count": 2,
		"ammo_dice_sides": 10,
	},
	"Kobold": {
		"max_health": 5, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": -3.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -1.0, "wisdom": -2.0, "charisma": -2.0,
		"gold_value": 25,
		"weapons": ["Dagger", "Sling"],
		"abilities": ["Pack Tactics", "Sunlight Sensitivity"],
		"armor": ["Leather"],
	},
	"Orc": {
		"max_health": 15, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": -1.0, "charisma": -1.0,
		"gold_value": 55,
		"weapons": ["Greataxe", "Javelin"],
		"abilities": ["Aggressive", "Relentless"],
		"armor": ["Hide", "Shield"],
	},
	"Gnoll": {
		"max_health": 22, "armor_class": 15, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 50,
		"weapons": ["Bite", "Spear"],
		"abilities": ["Rampage"],
		"armor": ["Hide", "Shield"],
	},
	"Bugbear": {
		"max_health": 27, "armor_class": 16, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 70,
		"weapons": ["Morningstar", "Javelin"],
		"abilities": ["Brute", "Surprise Attack"],
		"armor": ["Hide", "Shield"],
	},
}
