const DATA: Dictionary = {
	"Mimic": {
		"max_health": 58, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 80,
		"weapons": ["Pseudopod", "Bite"],
		"abilities": ["False Appearance", "Adhesive"],
		"armor": ["Natural Armor"],
	},
	"Minotaur": {
		"max_health": 76, "armor_class": 14, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 120,
		"weapons": ["Greataxe", "Gore"],
		"abilities": ["Charge", "Labyrinthine Recall"],
		"armor": ["Natural Armor"],
		# Hornbound — bull-headed humanoid: dark brown muscular body, massive curved bull horns,
		# blood-red eyes, bull-tail. Holds a greataxe.
		"capture_archetype": "counter_charge",
		"body_plan_modifiers": {
			"base.scale": 1.40,
			"palette.primary": Color(0.42, 0.30, 0.18),    # bull-brown hide
			"palette.secondary": Color(0.25, 0.16, 0.08),
			"palette.accent": Color(0.92, 0.88, 0.78),     # ivory horns
			"palette.eye": Color(0.95, 0.20, 0.10),
			"face.eye_glow": true,
			"ornaments.tags": ["horns", "tail", "metallic_plate"],
		},
	},
	"Basilisk": {
		"max_health": 52, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 100,
		"weapons": ["Bite"],
		"abilities": ["Petrifying Gaze"],
		"armor": ["Natural Armor"],
	},
	"Medusa": {
		"max_health": 127, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": -1.0, "charisma": 1.0,
		"gold_value": 200,
		"weapons": ["Shortsword", "Longbow"],
		"abilities": ["Petrifying Gaze", "Snake Hair"],
		"armor": ["Natural Armor"],
	},
	"Werewolf": {
		"max_health": 58, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 110,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Lycanthropy", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Sandworm": {
		"max_health": 247, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 8.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 400,
		"weapons": ["Bite", "Swallow"],
		"abilities": ["Tunneler", "Tremorsense"],
		"armor": ["Hardened Hide"],
	},
	"Cockatrice": {
		"max_health": 27, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Beak"],
		"abilities": ["Petrifying Bite"],
		"armor": ["Natural Armor"],
	},
	"Darkmantle": {
		"max_health": 22, "armor_class": 11, "damage_amount": 1.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 20,
		"weapons": ["Tentacle"],
		"abilities": ["Darkness Aura", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Rust Monster": {
		"max_health": 27, "armor_class": 14, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 20,
		"weapons": ["Bite", "Antennae"],
		"abilities": ["Iron Scent", "Rust Metal"],
		"armor": ["Natural Armor"],
	},
	"Harpy": {
		"max_health": 38, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 30,
		"weapons": ["Claws", "Club"],
		"abilities": ["Luring Song", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Hippogriff": {
		"max_health": 19, "armor_class": 11, "damage_amount": 1.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 30,
		"weapons": ["Claws", "Beak"],
		"abilities": ["Fly"],
		"armor": ["Natural Armor"],
	},
	"Death Dog": {
		"max_health": 39, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 30,
		"weapons": ["Bite"],
		"abilities": ["Two-Headed", "Keen Hearing and Smell"],
		"armor": ["Natural Armor"],
	},
	"Ankheg": {
		"max_health": 39, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 60,
		"weapons": ["Bite"],
		"abilities": ["Acid Spray"],
		"armor": ["Natural Armor"],
	},
	"Carrion Crawler": {
		"max_health": 51, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 60,
		"weapons": ["Tentacles", "Bite"],
		"abilities": ["Keen Smell", "Spider Climb"],
		"armor": ["Natural Armor"],
	},
	"Ettercap": {
		"max_health": 44, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Claws"],
		"abilities": ["Spider Climb", "Web Sense", "Web Walker"],
		"armor": ["Natural Armor"],
	},
	"Griffin": {
		"max_health": 59, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Claws", "Beak"],
		"abilities": ["Keen Sight", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Merrow": {
		"max_health": 45, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Claws", "Harpoon"],
		"abilities": ["Amphibious"],
		"armor": ["Natural Armor"],
	},
	"Peryton": {
		"max_health": 33, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 60,
		"weapons": ["Dive Attack", "Bite", "Talons"],
		"abilities": ["Dive Attack", "Fly", "Keen Sight and Smell"],
		"armor": ["Natural Armor"],
	},
	"Grick": {
		"max_health": 27, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": -3.0,
		"gold_value": 60,
		"weapons": ["Tentacles", "Beak"],
		"abilities": ["Stone Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Wererat": {
		"max_health": 33, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Bite", "Shortsword", "Hand Crossbow"],
		"abilities": ["Shapechanger", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Displacer Beast": {
		"max_health": 85, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 100,
		"weapons": ["Tentacle"],
		"abilities": ["Avoidance", "Displacement"],
		"armor": ["Natural Armor"],
	},
	"Hook Horror": {
		"max_health": 75, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 100,
		"weapons": ["Hook"],
		"abilities": ["Echolocation", "Keen Hearing"],
		"armor": ["Natural Armor"],
	},
	"Manticore": {
		"max_health": 68, "armor_class": 14, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 100,
		"weapons": ["Claws", "Bite", "Tail Spike"],
		"abilities": ["Tail Spike Volley", "Fly"],
		"armor": ["Natural Armor"],
		# Hornbound — chimeric: tawny lion body, bat-wings, human-like maned face, spike-tail.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 1.45,
			"palette.primary": Color(0.68, 0.45, 0.22),    # tawny lion coat
			"palette.secondary": Color(0.42, 0.25, 0.10),
			"palette.accent": Color(0.92, 0.88, 0.78),     # ivory spikes
			"palette.eye": Color(0.92, 0.20, 0.10),
			"face.eye_glow": true,
			"ornaments.tags": ["wings", "tail", "mane", "spike_ridge"],
		},
	},
	"Owlbear": {
		"max_health": 59, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 100,
		"weapons": ["Claws", "Beak"],
		"abilities": ["Keen Sight and Smell"],
		"armor": ["Natural Armor"],
		# Hornbound — bear-owl hybrid: russet-brown bear body, huge feathered owl head, hooked beak,
		# huge golden owl eyes, taloned forepaws.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 1.55,
			"palette.primary": Color(0.42, 0.30, 0.18),    # russet bear fur
			"palette.secondary": Color(0.65, 0.50, 0.32),  # lighter belly
			"palette.accent": Color(0.92, 0.78, 0.18),     # golden beak
			"palette.eye": Color(0.95, 0.80, 0.20),
			"face.eye_glow": true,
			"face.eye_radius": 0.085,                       # giant owl eyes
			"ornaments.tags": ["tail", "wings"],
		},
	},
	"Phase Spider": {
		"max_health": 32, "armor_class": 13, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 100,
		"weapons": ["Bite"],
		"abilities": ["Ethereal Jaunt", "Spider Climb", "Web Walker"],
		"armor": ["Natural Armor"],
	},
	"Yuan-ti Malison": {
		"max_health": 66, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 2.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 100,
		"weapons": ["Scimitar", "Shortbow"],
		"abilities": ["Magic Resistance", "Innate Spellcasting", "Poison Immunity"],
		"armor": ["Natural Armor"],
	},
	"Yeti": {
		"max_health": 51, "armor_class": 12, "damage_amount": 2.5, "element_type": "ice",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 100,
		"weapons": ["Claw"],
		"abilities": ["Chilling Gaze", "Fear of Fire", "Keen Smell", "Snow Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Lamia": {
		"max_health": 97, "armor_class": 13, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 2.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Claws", "Dagger"],
		"abilities": ["Innate Spellcasting", "Intoxicating Touch"],
		"armor": ["Natural Armor"],
	},
	"Wereboar": {
		"max_health": 78, "armor_class": 11, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 130,
		"weapons": ["Maul", "Tusks"],
		"abilities": ["Shapechanger", "Charge", "Relentless"],
		"armor": ["Natural Armor"],
	},
	"Weretiger": {
		"max_health": 120, "armor_class": 12, "damage_amount": 3.5, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 130,
		"weapons": ["Scimitar", "Claws", "Bite"],
		"abilities": ["Shapechanger", "Keen Hearing and Smell", "Pounce"],
		"armor": ["Natural Armor"],
	},
	"Bulette": {
		"max_health": 94, "armor_class": 17, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 165,
		"weapons": ["Bite"],
		"abilities": ["Standing Leap", "Deadly Leap"],
		"armor": ["Natural Armor"],
	},
	"Catoblepas": {
		"max_health": 84, "armor_class": 14, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 165,
		"weapons": ["Tail"],
		"abilities": ["Stench", "Death Ray"],
		"armor": ["Natural Armor"],
	},
	"Umber Hulk": {
		"max_health": 93, "armor_class": 18, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 165,
		"weapons": ["Claws", "Mandibles"],
		"abilities": ["Confusing Gaze", "Tunneler"],
		"armor": ["Natural Armor"],
	},
	"Werebear": {
		"max_health": 135, "armor_class": 11, "damage_amount": 4.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 1.0,
		"gold_value": 165,
		"weapons": ["Greataxe", "Claws", "Bite"],
		"abilities": ["Shapechanger", "Keen Smell"],
		"armor": ["Natural Armor"],
	},
	"Chimera": {
		"max_health": 114, "armor_class": 14, "damage_amount": 4.5, "element_type": "fire",
		"strength": 4.0, "dexterity": 0.0, "constitution": 4.0, "intelligence": -4.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 195,
		"weapons": ["Horns", "Claws", "Bite"],
		"abilities": ["Fire Breath", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Grick Alpha": {
		"max_health": 75, "armor_class": 18, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 230,
		"weapons": ["Tentacles", "Beak"],
		"abilities": ["Stone Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Yuan-ti Abomination": {
		"max_health": 127, "armor_class": 15, "damage_amount": 5.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 4.0,
		"gold_value": 230,
		"weapons": ["Scimitar", "Longbow"],
		"abilities": ["Magic Resistance", "Innate Spellcasting", "Poison Immunity"],
		"armor": ["Natural Armor"],
	},
	"Hydra": {
		"max_health": 172, "armor_class": 15, "damage_amount": 5.5, "element_type": "none",
		"strength": 5.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 260,
		"weapons": ["Bite"],
		"abilities": ["Hold Breath", "Multiple Heads", "Reactive Heads", "Wakeful"],
		"armor": ["Natural Armor"],
	},
	"Abominable Yeti": {
		"max_health": 137, "armor_class": 15, "damage_amount": 5.5, "element_type": "ice",
		"strength": 7.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 295,
		"weapons": ["Claw"],
		"abilities": ["Chilling Gaze", "Fear of Fire", "Keen Smell", "Snow Camouflage"],
		"armor": ["Natural Armor"],
	},
	"Froghemoth": {
		"max_health": 184, "armor_class": 14, "damage_amount": 6.0, "element_type": "none",
		"strength": 6.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 330,
		"weapons": ["Tentacle", "Bite", "Tongue"],
		"abilities": ["Amphibious", "Shock Susceptibility"],
		"armor": ["Natural Armor"],
	},
	"Guardian Naga": {
		"max_health": 120, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 4.0, "dexterity": 4.0, "constitution": 3.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 330,
		"weapons": ["Bite", "Spit Poison"],
		"abilities": ["Rejuvenation", "Magic Weapons", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Behir": {
		"max_health": 168, "armor_class": 17, "damage_amount": 6.0, "element_type": "storm",
		"strength": 6.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": -2.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 365,
		"weapons": ["Bite", "Constrict"],
		"abilities": ["Lightning Breath"],
		"armor": ["Natural Armor"],
	},
	"Remorhaz": {
		"max_health": 195, "armor_class": 17, "damage_amount": 6.0, "element_type": "fire",
		"strength": 7.0, "dexterity": 1.0, "constitution": 5.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 365,
		"weapons": ["Bite"],
		"abilities": ["Heated Body"],
		"armor": ["Natural Armor"],
	},
	"Roc": {
		"max_health": 248, "armor_class": 15, "damage_amount": 6.0, "element_type": "none",
		"strength": 9.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 365,
		"weapons": ["Beak", "Talons"],
		"abilities": ["Keen Sight", "Fly"],
		"armor": ["Natural Armor"],
	},
	"Gynosphinx": {
		"max_health": 136, "armor_class": 17, "damage_amount": 6.0, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 4.0, "wisdom": 4.0, "charisma": 4.0,
		"gold_value": 365,
		"weapons": ["Claws"],
		"abilities": ["Inscrutable", "Magic Weapons", "Innate Spellcasting", "Legendary Resistance"],
		"armor": ["Natural Armor"],
	},
	"Spirit Naga": {
		"max_health": 75, "armor_class": 15, "damage_amount": 7.0, "element_type": "none",
		"strength": 4.0, "dexterity": 3.0, "constitution": 2.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 465,
		"weapons": ["Bite"],
		"abilities": ["Rejuvenation", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Androsphinx": {
		"max_health": 199, "armor_class": 17, "damage_amount": 8.5, "element_type": "none",
		"strength": 6.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 3.0, "wisdom": 4.0, "charisma": 6.0,
		"gold_value": 665,
		"weapons": ["Claws"],
		"abilities": ["Inscrutable", "Magic Weapons", "Roar", "Innate Spellcasting", "Legendary Resistance"],
		"armor": ["Natural Armor"],
	},
	"Kraken": {
		"max_health": 472, "armor_class": 18, "damage_amount": 11.0, "element_type": "storm",
		"strength": 10.0, "dexterity": 0.0, "constitution": 7.0, "intelligence": 6.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 1100,
		"weapons": ["Tentacle", "Bite", "Fling"],
		"abilities": ["Amphibious", "Freedom of Movement", "Legendary Resistance", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
	"Tarrasque": {
		"max_health": 676, "armor_class": 25, "damage_amount": 15.0, "element_type": "none",
		"strength": 10.0, "dexterity": 0.0, "constitution": 10.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 3000,
		"weapons": ["Bite", "Claws", "Horns", "Tail"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Reflective Carapace", "Siege Monster"],
		"armor": ["Natural Armor"],
	},
}
