const DATA: Dictionary = {
	"Mimic": {
		"max_health": 58, "armor_class": 12, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 80,
		"weapons": ["Pseudopod", "Bite"],
		"abilities": ["False Appearance", "Adhesive"],
		"armor": ["Natural Armor"],
	},
	"Minotaur": {
		"max_health": 76, "armor_class": 14, "damage_amount": 4.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 120,
		"weapons": ["Greataxe", "Gore"],
		"abilities": ["Charge", "Labyrinthine Recall"],
		"armor": ["Natural Armor"],
	},
	"Basilisk": {
		"max_health": 52, "armor_class": 15, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": -1.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 100,
		"weapons": ["Bite"],
		"abilities": ["Petrifying Gaze"],
		"armor": ["Natural Armor"],
	},
	"Medusa": {
		"max_health": 127, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": 2.0, "wisdom": -1.0, "charisma": 1.0,
		"gold_value": 200,
		"weapons": ["Shortsword", "Longbow"],
		"abilities": ["Petrifying Gaze", "Snake Hair"],
		"armor": ["Natural Armor"],
	},
	"Werewolf": {
		"max_health": 58, "armor_class": 12, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 0.0,
		"gold_value": 110,
		"weapons": ["Claw", "Bite"],
		"abilities": ["Lycanthropy", "Pack Tactics"],
		"armor": ["Natural Armor"],
	},
	"Sandworm": {
		"max_health": 247, "armor_class": 18, "damage_amount": 6.0, "element_type": "none",
		"strength": 8.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 400,
		"weapons": ["Bite", "Swallow"],
		"abilities": ["Tunneler", "Tremorsense"],
		"armor": ["Hardened Hide"],
	},
}
