const DATA: Dictionary = {
	"Oblex Spawn": {
		"max_health": 18, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": -1.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 15,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Sulfurous Impersonation"],
		"armor": ["Natural Armor"],
	},
	"Gray Ooze": {
		"max_health": 22, "armor_class": 8, "damage_amount": 1.5, "element_type": "none",
		"strength": 1.0, "dexterity": -2.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -4.0,
		"gold_value": 25,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Corrode Metal", "False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Ochre Jelly": {
		"max_health": 45, "armor_class": 8, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": -2.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -5.0,
		"gold_value": 60,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Spider Climb", "Split"],
		"armor": ["Natural Armor"],
	},
	"Gelatinous Cube": {
		"max_health": 84, "armor_class": 6, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": -4.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -5.0,
		"gold_value": 65,
		"weapons": ["Pseudopod"],
		"abilities": ["Ooze Cube", "Transparent", "Engulf"],
		"armor": ["Natural Armor"],
	},
	"Slithering Tracker": {
		"max_health": 10, "armor_class": 14, "damage_amount": 2.5, "element_type": "none",
		"strength": 1.0, "dexterity": 4.0, "constitution": 0.0, "intelligence": -1.0, "wisdom": 1.0, "charisma": -3.0,
		"gold_value": 95,
		"weapons": ["Slam"],
		"abilities": ["Amorphous", "Ambusher", "Damage Transfer", "False Appearance", "Spider Climb", "Liquid Form"],
		"armor": ["Natural Armor"],
	},
	"Black Pudding": {
		"max_health": 85, "armor_class": 7, "damage_amount": 3.0, "element_type": "none",
		"strength": 3.0, "dexterity": -3.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": -2.0, "charisma": -5.0,
		"gold_value": 130,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Corrosive Form", "Spider Climb", "Split"],
		"armor": ["Natural Armor"],
	},
	"Adult Oblex": {
		"max_health": 75, "armor_class": 9, "damage_amount": 3.5, "element_type": "none",
		"strength": -1.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 180,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Eat Memories", "Sulfurous Impersonation", "Innate Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Elder Oblex": {
		"max_health": 115, "armor_class": 9, "damage_amount": 5.0, "element_type": "none",
		"strength": 1.0, "dexterity": -1.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 330,
		"weapons": ["Pseudopod"],
		"abilities": ["Amorphous", "Eat Memories", "Sulfurous Impersonation", "Innate Spellcasting", "Instill Oblex"],
		"armor": ["Natural Armor"],
	},
	"Juiblex": {
		"max_health": 400, "armor_class": 18, "damage_amount": 11.0, "element_type": "none",
		"strength": 8.0, "dexterity": -3.0, "constitution": 10.0, "intelligence": 5.0, "wisdom": 7.0, "charisma": 5.0,
		"gold_value": 1100,
		"weapons": ["Acid Touch", "Eject Slime"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Spider Climb", "Regeneration"],
		"armor": ["Natural Armor"],
	},
}
