const DATA: Dictionary = {
	"Mushroom": {
		"max_health": 15, "armor_class": 10, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 35,
		"weapons": ["Spore Burst", "Root Slam"],
		"abilities": ["Poison Spores", "Regrowth"],
		"armor": ["Natural Armor"],
	},
	"Shrieker": {
		"max_health": 13, "armor_class": 5, "damage_amount": 0.0, "element_type": "none",
		"strength": -5.0, "dexterity": -5.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 5,
		"weapons": [],
		"abilities": ["False Appearance", "Shriek"],
		"armor": ["Natural Armor"],
	},
	"Myconid Sprout": {
		"max_health": 8, "armor_class": 10, "damage_amount": 0.5, "element_type": "none",
		"strength": -1.0, "dexterity": 0.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 5,
		"weapons": ["Fist"],
		"abilities": ["Distress Spores", "Rapport Spores", "Sun Sickness"],
		"armor": ["Natural Armor"],
	},
	"Awakened Shrub": {
		"max_health": 10, "armor_class": 9, "damage_amount": 0.5, "element_type": "none",
		"strength": -4.0, "dexterity": -1.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 5,
		"weapons": ["Rake"],
		"abilities": ["False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Twig Blight": {
		"max_health": 4, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 10,
		"weapons": ["Claws"],
		"abilities": ["False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Needle Blight": {
		"max_health": 11, "armor_class": 12, "damage_amount": 1.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": -1.0, "charisma": -4.0,
		"gold_value": 15,
		"weapons": ["Claws", "Needles"],
		"abilities": ["False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Violet Fungus": {
		"max_health": 18, "armor_class": 5, "damage_amount": 1.0, "element_type": "none",
		"strength": -4.0, "dexterity": -5.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 15,
		"weapons": ["Rotting Touch"],
		"abilities": ["False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Vegepygmy": {
		"max_health": 9, "armor_class": 13, "damage_amount": 1.0, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 15,
		"weapons": ["Claws", "Spit Spores"],
		"abilities": ["Plant Camouflage", "Regeneration", "Spore Infection"],
		"armor": ["Natural Armor"],
	},
	"Gas Spore": {
		"max_health": 1, "armor_class": 5, "damage_amount": 1.0, "element_type": "none",
		"strength": -3.0, "dexterity": -5.0, "constitution": 1.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -5.0,
		"gold_value": 25,
		"weapons": ["Death Burst"],
		"abilities": ["Death Burst", "Eerie Resemblance", "Spores"],
		"armor": ["Natural Armor"],
	},
	"Vine Blight": {
		"max_health": 26, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": -1.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 25,
		"weapons": ["Constrict"],
		"abilities": ["False Appearance", "Rooted"],
		"armor": ["Natural Armor"],
	},
	"Myconid Adult": {
		"max_health": 22, "armor_class": 12, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 1.0, "constitution": 1.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 25,
		"weapons": ["Fist"],
		"abilities": ["Distress Spores", "Rapport Spores", "Pacifying Spores", "Sun Sickness"],
		"armor": ["Natural Armor"],
	},
	"Thorny": {
		"max_health": 27, "armor_class": 14, "damage_amount": 1.5, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 35,
		"weapons": ["Claws"],
		"abilities": ["Plant Camouflage", "Regeneration", "Thorn Burst"],
		"armor": ["Natural Armor"],
	},
	"Awakened Tree": {
		"max_health": 59, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": -2.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": -2.0,
		"gold_value": 65,
		"weapons": ["Slam"],
		"abilities": ["False Appearance"],
		"armor": ["Natural Armor"],
	},
	"Vegepygmy Chief": {
		"max_health": 33, "armor_class": 14, "damage_amount": 2.0, "element_type": "none",
		"strength": 2.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": -1.0,
		"gold_value": 65,
		"weapons": ["Claws", "Spit Spores"],
		"abilities": ["Plant Camouflage", "Regeneration", "Spore Infection"],
		"armor": ["Natural Armor"],
	},
	"Myconid Sovereign": {
		"max_health": 60, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 1.0, "constitution": 2.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 1.0,
		"gold_value": 65,
		"weapons": ["Fist"],
		"abilities": ["Distress Spores", "Rapport Spores", "Pacifying Spores", "Animating Spores", "Hallucination Spores", "Sun Sickness"],
		"armor": ["Natural Armor"],
	},
	"Wood Woad": {
		"max_health": 75, "armor_class": 18, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -1.0, "wisdom": 2.0, "charisma": -1.0,
		"gold_value": 180,
		"weapons": ["Club", "Slam"],
		"abilities": ["Magic Weapons", "Plant Camouflage", "Regeneration", "Tree Stride"],
		"armor": ["Natural Armor"],
	},
	"Corpse Flower": {
		"max_health": 127, "armor_class": 12, "damage_amount": 4.5, "element_type": "none",
		"strength": 4.0, "dexterity": 2.0, "constitution": 3.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -4.0,
		"gold_value": 260,
		"weapons": ["Tentacle"],
		"abilities": ["Corpses", "Stench of Death"],
		"armor": ["Natural Armor"],
	},
	"Treant": {
		"max_health": 138, "armor_class": 16, "damage_amount": 5.0, "element_type": "none",
		"strength": 6.0, "dexterity": -1.0, "constitution": 5.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 1.0,
		"gold_value": 295,
		"weapons": ["Slam", "Rock"],
		"abilities": ["False Appearance", "Siege Monster", "Animate Trees"],
		"armor": ["Natural Armor"],
	},
}
