const DATA: Dictionary = {
	"Skeleton": {
		"max_health": 13, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": -1.0, "intelligence": -4.0, "wisdom": -2.0, "charisma": -3.0,
		"gold_value": 30,
		"weapons": ["Shortsword", "Shortbow"],
		"abilities": ["Undead Fortitude"],
		"armor": ["Armor Scraps"],
		# Hornbound
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 0.9,
			"palette.primary": Color(0.88, 0.85, 0.78),  # Bone white
			"palette.secondary": Color(0.50, 0.45, 0.38),
			"ornaments.tags": ["bone_protrusion"],
		},
	},
	"Zombie": {
		"max_health": 22, "armor_class": 8, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": -2.0, "constitution": 3.0, "intelligence": -5.0, "wisdom": -4.0, "charisma": -4.0,
		"gold_value": 25,
		"weapons": ["Slam"],
		"abilities": ["Undead Fortitude"],
		"armor": ["Tattered Cloth"],
		# Hornbound
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 1.05,
			"palette.primary": Color(0.45, 0.55, 0.40),  # Sickly green-grey
			"ornaments.tags": ["tattered_cloth", "bone_protrusion"],
		},
	},
	"Ghoul": {
		"max_health": 22, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 60,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Paralyzing Touch", "Undead Fortitude"],
		"armor": ["Natural Armor"],
	},
	"Crawling Claw": {
		"max_health": 2, "armor_class": 12, "damage_amount": 0.5, "element_type": "none",
		"strength": 1.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -3.0, "wisdom": 0.0, "charisma": -3.0,
		"gold_value": 5,
		"weapons": ["Claw"],
		"abilities": ["Turn Immunity"],
		"armor": ["Natural Armor"],
	},
	"Shadow": {
		"max_health": 16, "armor_class": 12, "damage_amount": 1.5, "element_type": "shadow",
		"strength": -2.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 25,
		"weapons": ["Strength Drain"],
		"abilities": ["Shadow Stealth", "Sunlight Weakness", "Amorphous"],
		"armor": ["Natural Armor"],
	},
	"Warhorse Skeleton": {
		"max_health": 22, "armor_class": 13, "damage_amount": 1.5, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 2.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 25,
		"weapons": ["Hooves"],
		"abilities": ["Undead Fortitude"],
		"armor": ["Natural Armor"],
	},
	"Specter": {
		"max_health": 22, "armor_class": 12, "damage_amount": 1.5, "element_type": "shadow",
		"strength": -5.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 35,
		"weapons": ["Life Drain"],
		"abilities": ["Incorporeal Movement", "Sunlight Sensitivity"],
		"armor": ["Natural Armor"],
	},
	"Ghast": {
		"max_health": 36, "armor_class": 13, "damage_amount": 2.0, "element_type": "none",
		"strength": 3.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": -1.0,
		"gold_value": 60,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Stench", "Turning Defiance"],
		"armor": ["Natural Armor"],
	},
	"Minotaur Skeleton": {
		"max_health": 67, "armor_class": 12, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 65,
		"weapons": ["Greataxe", "Gore"],
		"abilities": ["Charge"],
		"armor": ["Natural Armor"],
	},
	"Ogre Zombie": {
		"max_health": 85, "armor_class": 8, "damage_amount": 2.0, "element_type": "none",
		"strength": 4.0, "dexterity": -2.0, "constitution": 3.0, "intelligence": -4.0, "wisdom": -1.0, "charisma": -3.0,
		"gold_value": 65,
		"weapons": ["Morningstar"],
		"abilities": ["Undead Fortitude"],
		"armor": ["Natural Armor"],
	},
	"Will-o'-Wisp": {
		"max_health": 22, "armor_class": 19, "damage_amount": 2.0, "element_type": "none",
		"strength": -5.0, "dexterity": 9.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 0.0,
		"gold_value": 65,
		"weapons": ["Shock"],
		"abilities": ["Consume Life", "Ephemeral", "Incorporeal Movement", "Variable Illumination"],
		"armor": ["Natural Armor"],
	},
	"Poltergeist": {
		"max_health": 22, "armor_class": 12, "damage_amount": 2.0, "element_type": "shadow",
		"strength": -5.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 0.0,
		"gold_value": 65,
		"weapons": ["Forceful Slam"],
		"abilities": ["Incorporeal Movement", "Telekinetic Thrust"],
		"armor": ["Natural Armor"],
	},
	"Mummy": {
		"max_health": 58, "armor_class": 11, "damage_amount": 2.5, "element_type": "none",
		"strength": 3.0, "dexterity": -1.0, "constitution": 2.0, "intelligence": -2.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 95,
		"weapons": ["Rotting Fist"],
		"abilities": ["Mummy Rot"],
		"armor": ["Natural Armor"],
		# Hornbound — bandaged corpse: yellowed wrappings, dust-grey skin, glowing amber eyes.
		"capture_archetype": "weaken",
		"body_plan_modifiers": {
			"base.scale": 1.10,
			"palette.primary": Color(0.78, 0.65, 0.40),    # yellowed wrappings
			"palette.secondary": Color(0.50, 0.38, 0.20),
			"palette.accent": Color(0.92, 0.78, 0.20),     # gold accents
			"palette.eye": Color(0.95, 0.65, 0.18),
			"face.eye_glow": true,
			"ornaments.tags": ["tattered_cloth", "metallic_plate"],
		},
	},
	"Wight": {
		"max_health": 45, "armor_class": 14, "damage_amount": 2.5, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 2.0,
		"gold_value": 95,
		"weapons": ["Longsword", "Longbow", "Life Drain"],
		"abilities": ["Sunlight Sensitivity", "Life Drain"],
		"armor": ["Natural Armor"],
	},
	"Sword Wraith Warrior": {
		"max_health": 45, "armor_class": 16, "damage_amount": 2.5, "element_type": "shadow",
		"strength": 3.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 95,
		"weapons": ["Longsword"],
		"abilities": ["Incorporeal Movement", "Sunlight Sensitivity"],
		"armor": ["Natural Armor"],
	},
	"Vampiric Mist": {
		"max_health": 30, "armor_class": 13, "damage_amount": 2.5, "element_type": "shadow",
		"strength": -2.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": -3.0, "wisdom": 1.0, "charisma": -2.0,
		"gold_value": 95,
		"weapons": ["Blood Drain"],
		"abilities": ["Incorporeal Movement", "Life Drain"],
		"armor": ["Natural Armor"],
	},
	"Banshee": {
		"max_health": 58, "armor_class": 12, "damage_amount": 3.0, "element_type": "shadow",
		"strength": -5.0, "dexterity": 2.0, "constitution": 0.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Corrupting Touch"],
		"abilities": ["Detect Life", "Incorporeal Movement", "Horrifying Visage", "Wail"],
		"armor": ["Natural Armor"],
	},
	"Bone Naga": {
		"max_health": 58, "armor_class": 15, "damage_amount": 3.0, "element_type": "none",
		"strength": 2.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 1.0,
		"gold_value": 130,
		"weapons": ["Bite"],
		"abilities": ["Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Deathlock": {
		"max_health": 36, "armor_class": 13, "damage_amount": 3.0, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 1.0, "intelligence": 3.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Deathly Claw"],
		"abilities": ["Spellcasting", "Turn Resistance"],
		"armor": ["Natural Armor"],
	},
	"Flameskull": {
		"max_health": 40, "armor_class": 13, "damage_amount": 3.0, "element_type": "fire",
		"strength": -5.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Fire Ray"],
		"abilities": ["Illumination", "Magic Resistance", "Regeneration", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Ghost": {
		"max_health": 45, "armor_class": 11, "damage_amount": 3.0, "element_type": "shadow",
		"strength": -2.0, "dexterity": 1.0, "constitution": 0.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 130,
		"weapons": ["Withering Touch"],
		"abilities": ["Ethereal Sight", "Incorporeal Movement", "Possession", "Horrifying Visage"],
		"armor": ["Natural Armor"],
	},
	"Allip": {
		"max_health": 40, "armor_class": 13, "damage_amount": 3.5, "element_type": "shadow",
		"strength": -5.0, "dexterity": 3.0, "constitution": 0.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 5.0,
		"gold_value": 180,
		"weapons": ["Maddening Touch"],
		"abilities": ["Incorporeal Movement", "Whispers of Madness"],
		"armor": ["Natural Armor"],
	},
	"Revenant": {
		"max_health": 136, "armor_class": 13, "damage_amount": 3.5, "element_type": "none",
		"strength": 4.0, "dexterity": 1.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 1.0, "charisma": 3.0,
		"gold_value": 180,
		"weapons": ["Fist"],
		"abilities": ["Regeneration", "Relentless", "Vengeful Tracker"],
		"armor": ["Natural Armor"],
	},
	"Vampire Spawn": {
		"max_health": 82, "armor_class": 15, "damage_amount": 3.5, "element_type": "shadow",
		"strength": 3.0, "dexterity": 3.0, "constitution": 1.0, "intelligence": 0.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 180,
		"weapons": ["Claws", "Bite"],
		"abilities": ["Regeneration", "Spider Climb", "Vampire Weaknesses"],
		"armor": ["Natural Armor"],
	},
	"Wraith": {
		"max_health": 67, "armor_class": 13, "damage_amount": 3.5, "element_type": "shadow",
		"strength": -2.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 1.0, "wisdom": 2.0, "charisma": 2.0,
		"gold_value": 180,
		"weapons": ["Life Drain"],
		"abilities": ["Incorporeal Movement", "Sunlight Sensitivity", "Create Specter"],
		"armor": ["Natural Armor"],
	},
	"Bodak": {
		"max_health": 58, "armor_class": 15, "damage_amount": 4.0, "element_type": "shadow",
		"strength": 2.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": -2.0, "wisdom": 1.0, "charisma": 4.0,
		"gold_value": 200,
		"weapons": ["Fist"],
		"abilities": ["Aura of Annihilation", "Death Gaze", "Sunlight Hypersensitivity"],
		"armor": ["Natural Armor"],
	},
	"Deathlock Mastermind": {
		"max_health": 110, "armor_class": 13, "damage_amount": 4.5, "element_type": "none",
		"strength": 0.0, "dexterity": 2.0, "constitution": 2.0, "intelligence": 4.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 260,
		"weapons": ["Deathly Claw"],
		"abilities": ["Spellcasting", "Magic Resistance", "Turn Resistance"],
		"armor": ["Natural Armor"],
	},
	"Sword Wraith Commander": {
		"max_health": 127, "armor_class": 18, "damage_amount": 5.0, "element_type": "shadow",
		"strength": 5.0, "dexterity": 2.0, "constitution": 4.0, "intelligence": 1.0, "wisdom": 0.0, "charisma": 1.0,
		"gold_value": 260,
		"weapons": ["Battleaxe", "Longbow"],
		"abilities": ["Incorporeal Movement", "Sunlight Sensitivity", "Marshal Undead"],
		"armor": ["Natural Armor"],
	},
	"Vampire": {
		"max_health": 144, "armor_class": 16, "damage_amount": 6.5, "element_type": "shadow",
		"strength": 4.0, "dexterity": 4.0, "constitution": 4.0, "intelligence": 3.0, "wisdom": 2.0, "charisma": 4.0,
		"gold_value": 465,
		"weapons": ["Unarmed Strike", "Bite"],
		"abilities": ["Legendary Resistance", "Misty Escape", "Regeneration", "Spider Climb", "Shapechanger"],
		"armor": ["Natural Armor"],
		# Hornbound — pale aristocrat: chalk-white skin, jet-black hair, blood-red eyes, dark cape.
		"capture_archetype": "kill_lessers",
		"body_plan_modifiers": {
			"base.scale": 1.10,
			"palette.primary": Color(0.88, 0.82, 0.78),    # pale chalk skin
			"palette.secondary": Color(0.08, 0.05, 0.05),  # black hair / cape
			"palette.accent": Color(0.78, 0.05, 0.05),     # blood red
			"palette.eye": Color(0.95, 0.10, 0.10),
			"face.eye_glow": true,
			"ornaments.tags": ["tattered_cloth"],
		},
	},
	"Mummy Lord": {
		"max_health": 97, "armor_class": 17, "damage_amount": 7.0, "element_type": "none",
		"strength": 4.0, "dexterity": 0.0, "constitution": 3.0, "intelligence": 0.0, "wisdom": 4.0, "charisma": 3.0,
		"gold_value": 565,
		"weapons": ["Rotting Fist"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Rejuvenation", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Skull Lord": {
		"max_health": 112, "armor_class": 18, "damage_amount": 7.0, "element_type": "shadow",
		"strength": 3.0, "dexterity": 3.0, "constitution": 4.0, "intelligence": 5.0, "wisdom": 4.0, "charisma": 5.0,
		"gold_value": 565,
		"weapons": ["Bone Staff"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Skull Shard", "Spellcasting"],
		"armor": ["Natural Armor"],
	},
	"Death Knight": {
		"max_health": 180, "armor_class": 20, "damage_amount": 8.0, "element_type": "none",
		"strength": 5.0, "dexterity": 0.0, "constitution": 5.0, "intelligence": 1.0, "wisdom": 3.0, "charisma": 4.0,
		"gold_value": 665,
		"weapons": ["Hellfire Orb", "Longsword"],
		"abilities": ["Magic Resistance", "Spellcasting", "Marshal Undead", "Parry"],
		"armor": ["Plate Armor"],
		# Hornbound — dread warrior in soot-black armor, torn crimson cape, hellfire-red eyes.
		"capture_archetype": "break_armor",
		"body_plan_modifiers": {
			"base.scale": 1.25,
			"palette.primary": Color(0.10, 0.10, 0.14),    # soot-black plate
			"palette.secondary": Color(0.55, 0.08, 0.05),  # crimson cape
			"palette.accent": Color(0.95, 0.30, 0.10),     # hellfire glow
			"palette.eye": Color(1.0, 0.20, 0.10),
			"face.eye_glow": true,
			"face.eye_radius": 0.060,
			"ornaments.tags": ["metallic_plate", "tattered_cloth", "horns"],
		},
	},
	"Demilich": {
		"max_health": 80, "armor_class": 20, "damage_amount": 8.5, "element_type": "none",
		"strength": -5.0, "dexterity": 5.0, "constitution": 7.0, "intelligence": 5.0, "wisdom": 3.0, "charisma": 3.0,
		"gold_value": 715,
		"weapons": ["Devour Soul"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Rejuvenation", "Turn Immunity", "Avoidance"],
		"armor": ["Natural Armor"],
	},
	"Lich": {
		"max_health": 135, "armor_class": 17, "damage_amount": 9.0, "element_type": "none",
		"strength": 0.0, "dexterity": 3.0, "constitution": 3.0, "intelligence": 5.0, "wisdom": 2.0, "charisma": 3.0,
		"gold_value": 900,
		"weapons": ["Paralyzing Touch"],
		"abilities": ["Legendary Resistance", "Magic Resistance", "Rejuvenation", "Spellcasting", "Turn Resistance"],
		"armor": ["Natural Armor"],
		# Hornbound — skeletal sorcerer: parchment skin stretched over bone, dark purple robes,
		# golden crown, necrotic green flames in empty eye sockets.
		"capture_archetype": "kill_lessers",
		"body_plan_modifiers": {
			"base.scale": 1.08,
			"palette.primary": Color(0.78, 0.72, 0.55),    # parchment skin
			"palette.secondary": Color(0.18, 0.08, 0.30),  # dark purple robes
			"palette.accent": Color(0.92, 0.78, 0.20),     # gold crown
			"palette.eye": Color(0.30, 0.95, 0.40),        # necrotic green flames
			"face.eye_glow": true,
			"face.eye_radius": 0.055,
			"ornaments.tags": ["tattered_cloth", "halo", "bone_protrusion"],
		},
	},
}
